gtk-rs/gir

Cargo.lock, Cargo.toml, Gir.toml, src/chunk.rs, src/codegen/mod.rs, src/codegen/widgets.rs, src/config.rs, src/env.rs, src/file_saver.rs, src/gobjects.rs, src/main.rs, src/nameutil.rs
=> Create empty widget file

src/codegen/general.rs, src/codegen/widget.rs, src/library.rs, src/parser.rs
=> Generate static type

.travis.yml
I planing test function generation with fully loaded `Library`.
May be this will be better.
=> Travis build with --release

Gir.toml, src/analysis/general.rs, src/analysis/mod.rs, src/analysis/widget.rs, src/codegen/general.rs, src/codegen/widget.rs, src/codegen/widgets.rs, src/gobjects.rs, src/library.rs
Work in progress.
Again changes in library.
=> Generate upcasts

.gitignore, Gir.toml
Found strange bug, sometimes it analyzing 1-2 files (always including RadioButton).
=> Change default output directory

src/analysis/general.rs, src/codegen/general.rs, src/gobjects.rs
=> Numberic indentation

Gir.toml, src/analysis/object.rs, src/library.rs
=> Count only children, listed in config

src/analysis/functions.rs, src/analysis/rust_type.rs, src/codegen/function.rs, src/codegen/mod.rs, src/codegen/parameter.rs, src/codegen/return_value.rs
Not all. Without trait constraint.
=> Generate parameters values

src/analysis/functions.rs, src/analysis/object.rs, src/analysis/parents.rs, src/analysis/rust_type.rs, src/analysis/type_kind.rs, src/codegen/parameter.rs, src/codegen/return_value.rs, src/env.rs
Not sure that it good way, but it helps comment all functions with unsupported parameters.
Also I do not like class names, but nothing normal could not come up
=> Remake rust type

src/analysis/parents.rs, src/analysis/rust_type.rs, src/analysis/type_kind.rs, src/codegen/function.rs, src/codegen/function_body.rs, src/codegen/mod.rs, src/codegen/return_value.rs, src/codegen/translate_from_glib.rs, src/codegen/translate_to_glib.rs
Almost full functions generation.
Last "trait constraint" and "return out parameters", but before I prefer get compilable gtk code.
If you don't start #21 then say, I try do it.
=> Generate function body

src/analysis/functions.rs, src/analysis/rust_type.rs, src/codegen/parameter.rs, src/codegen/return_value.rs
Your advice https://github.com/gkoz/gir/issues/30#issuecomment-118555191 is really reduced code in this case. I'll try it for other Traits.
IMHO Tuple want be named (`LibrarysTypeId` ?) and moved to library.
=> Combine ToRustType's implementations

Gir.toml, src/analysis/rust_type.rs, src/config.rs, src/library.rs, src/main.rs, src/nameutil.rs
=> Different names for types from other libs

Gir.toml, src/analysis/functions.rs, src/analysis/implements.rs, src/analysis/mod.rs, src/analysis/object.rs, src/analysis/parents.rs, src/analysis/rust_type.rs, src/codegen/general.rs, src/codegen/widget.rs, src/library.rs
Current only common and parents
=> Generate uses

src/analysis/general.rs, src/analysis/object.rs, src/analysis/type_kind.rs, src/analysis/widget.rs, src/codegen/parameter.rs, src/codegen/return_value.rs, src/codegen/translate_from_glib.rs, src/codegen/translate_to_glib.rs, src/codegen/widgets.rs
Still not sure about good name for 'TypeKind::of()', prefer 'for' but it keyword :(
=> Remove typekind widget

src/analysis/functions.rs, src/analysis/mod.rs, src/analysis/needed_upcast.rs, src/analysis/upcasts.rs, src/codegen/function.rs, src/codegen/parameter.rs
=> Generate functions upcasts

src/analysis/functions.rs, src/analysis/implements.rs, src/analysis/parents.rs, src/analysis/rust_type.rs, src/codegen/function.rs, src/codegen/parameter.rs, src/codegen/return_value.rs, src/codegen/translate_from_glib.rs, src/env.rs
External types (`pango::Layout` in Scale) now count as ignored, if not set as "manual" in `Gir.toml`
=> Change external types rule

src/analysis/functions.rs, src/analysis/mod.rs, src/analysis/out_parameters.rs, src/codegen/function.rs, src/codegen/function_body.rs, src/codegen/parameter.rs, src/codegen/return_value.rs, src/library.rs
Not checked with pointer types and caller-allocates="1".
=> Out parameters as return

src/codegen/general.rs, src/codegen/sys/functions.rs, src/codegen/sys/lib_.rs, src/library.rs, src/parser.rs
WIP, don't merge.
Just to inform about.
=> Generate sys interface functions

Cargo.toml, Gir_GLib.toml, Gir_Gtk.toml, src/analysis/rust_type.rs, src/codegen/sys/ffi_type.rs, src/codegen/sys/lib_.rs, src/codegen/sys/statics.rs, src/config.rs, src/nameutil.rs
WIP.
Questionable:
1)  Change crate name from snake to lowercase (don't like change current names like `glib` to `g_lib`). Later, there will be problems with names like `gdkpixbuf`, but currently we have rename it anyway.
2) Change generate folder to `..\gtk`, as we needed 5 libraries, and i very don't like add it all to `gir/.gitignore` and have it in work tree.
=> Preparing for glib 1

src/codegen/sys/lib_.rs, src/library.rs
=> Don't skip FooClass, FooIface records, stub out the unions

src/codegen/sys/ffi_type.rs, tests/sys/gobject.toml
This fixes build. `ignore` shortcut in next PR
=> Ignore GObject.VaClosureMarshal in gobject-sys

src/codegen/sys/ffi_type.rs, src/config.rs, src/gobjects.rs, tests/sys/gobject.toml
Problems, that I don't solved fully:
1. iterate all GStatuses,
2. place `ignore` not in `options`
3. `parse_status_shorthand`: `for` in `map`
=> Shorthand for status="ignore" in toml

.gitignore, src/codegen/sys/ffi_type.rs, tests/sys/gio-sys/Cargo.toml, tests/sys/gio.toml, tests/sys/sys_build/Cargo.toml, tests/sys/sys_build/src/lib.rs, tests/sys/test.sh
=> Add gio to tests

src/codegen/sys/ffi_type.rs, src/codegen/sys/lib_.rs, src/codegen/sys/statics.rs, src/library.rs, src/parser.rs, tests/sys/pango-sys/Cargo.toml, tests/sys/pango.toml, tests/sys/test.sh
Add GArray, GByteArray and GPtrArray support.
Make enums and bitflags c_int and c_uint; convert negative bitflags members to positive repr.
Add pango to tests.
=> Arrays and bitflags improvements

tests/sys/atk-sys/Cargo.toml, tests/sys/gir-atk.toml, tests/sys/gir-gtk.toml, tests/sys/gtk-sys/Cargo.toml, tests/sys/sys_build/Cargo.toml
=> Add gtk-sys to tests

src/codegen/sys/functions.rs, src/codegen/sys/lib_.rs, src/codegen/sys/statics.rs, src/parser.rs, tests/sys/gir-gobject.toml
=> Generate other functions

src/codegen/sys/ffi_type.rs, src/codegen/sys/functions.rs, src/codegen/sys/lib_.rs, src/library.rs, src/parser.rs
=> Generate record functions

.travis.yml, src/codegen/sys/cargo_toml.rs, src/codegen/sys/mod.rs, src/parser.rs, tests/sys/atk-sys/Cargo.toml, tests/sys/gdk-pixbuf-sys/Cargo.toml, tests/sys/gdk-sys/Cargo.toml, tests/sys/gio-sys/Cargo.toml, tests/sys/gir-atk.toml, tests/sys/gir-gdk-pixbuf.toml, tests/sys/gir-gdk.toml, tests/sys/gir-gio.toml, tests/sys/gir-glib.toml, tests/sys/gir-gobject.toml, tests/sys/gir-gtk.toml, tests/sys/gir-pango.toml, tests/sys/glib-sys/Cargo.toml, tests/sys/gobject-sys/Cargo.toml, tests/sys/gtk-sys/Cargo.toml, tests/sys/pango-sys/Cargo.toml, tests/sys/secret-sys/Cargo.toml, tests/sys/sys_build/Cargo.toml, tests/sys/test.sh
Turns out the `toml-rs` library can't preserve the order of the items but at least it's deterministic.
=> Cargo.toml generation and manipulation

src/codegen/sys/build.rs, src/codegen/sys/cargo_toml.rs, src/codegen/sys/lib_.rs, src/codegen/widgets.rs, src/config.rs, src/file_saver.rs
Can make instead conditional compilation or config options
=> Don't make backups

tests/sys/test.sh
=> Fix equality comparison for sh

src/analysis/functions.rs, src/analysis/out_parameters.rs, src/codegen/function.rs, src/library.rs
=> Limit out_as_return to unconverted types

src/analysis/functions.rs, src/analysis/out_parameters.rs
=> Comment functions with unsupported outs

src/analysis/out_parameters.rs, src/codegen/function.rs, src/codegen/function_body.rs, src/codegen/return_value.rs, src/library.rs
=> Outs as optional return

src/codegen/sys/build.rs, src/codegen/sys/cargo_toml.rs, src/codegen/sys/lib_.rs, src/codegen/widgets.rs, src/config.rs, src/main.rs, src/parser.rs
=> Make full cover of errors in Config::new

src/config.rs
=> Relative paths in config

src/codegen/sys/ffi_type.rs
A case handled by this PR is
```xml
<type name="StatusIcon" c:type="gpointer"/>
```
=> Continuation of #116: use the proper type for objects when c:type is gpointer

src/analysis/return_value.rs, src/chunk/chunk.rs, src/chunk/mod.rs, src/chunk/parameter_ffi_call_in.rs, src/codegen/function.rs, src/codegen/function_body_chunk.rs, src/codegen/mod.rs, src/codegen/translate_to_glib.rs, src/writer/primitives.rs, src/writer/to_code.rs
=> Add chunks for functions body with direct call

src/analysis/object.rs, src/analysis/record.rs, src/codegen/general.rs, src/writer/to_code.rs
Uses now look like this
```
use PageOrientation;
use PaperSize;
use Unit;
use ffi;
use glib::translate::*;
use glib::types;
use object::*;
```
=> Rework uses

src/analysis/functions.rs, src/analysis/object.rs, src/chunk/chunk.rs, src/codegen/function.rs, src/codegen/function_body_chunk.rs, src/codegen/general.rs, src/codegen/object.rs, src/codegen/translate_to_glib.rs, src/writer/to_code.rs
Follows the changes in https://github.com/gtk-rs/glib/pull/77
=> Wrappers evolution

src/analysis/functions.rs, src/analysis/out_parameters.rs, src/codegen/general.rs, src/codegen/translate_to_glib.rs
The second commit relies on the recently pushed updates to `glib#object_reform`
=> Small fixes

Gir_Gtk.toml, src/analysis/functions.rs, src/analysis/mod.rs, src/analysis/safety_assertion_mode.rs, src/chunk/chunk.rs, src/codegen/function.rs, src/codegen/function_body_chunk.rs, src/config/config.rs, src/config/error.rs, src/writer/to_code.rs
=> Generate safety assertion in non-member functions

Gir_Gtk.toml, src/analysis/functions.rs, src/config/functions.rs
=> Add version override for functions

src/analysis/functions.rs, src/analysis/object.rs, src/analysis/record.rs, src/codegen/function.rs, src/codegen/general.rs, src/codegen/object.rs, src/codegen/record.rs, src/config/functions.rs, src/config/gobjects.rs
Final part of #180
Example for config:
```
[[object]]
name = "Gtk.PaperSize"
status = "generate"
cfg_condition = "tst"
[[object.function]]
name = "is_ipp"
version = "3.16"
cfg_condition = "unix"
```
=> Cfg condition

src/analysis/conversion_type.rs, src/analysis/ref_mode.rs, src/analysis/rust_type.rs, src/codegen/translate_from_glib.rs
[This glib commit](https://github.com/gkoz/gtk-rs-glib/commit/a40657e34185a8883e9b2ae1d4cc3324464ac747) makes the generator's job easier.
=> Improve containers support

src/analysis/functions.rs, src/analysis/upcasts.rs, src/codegen/function.rs
=> Provide type parameter defaults for optional parameters

Gir_Gtk.toml, src/analysis/out_parameters.rs, src/analysis/parameter.rs, src/analysis/rust_type.rs, src/chunk/chunk.rs, src/chunk/mod.rs, src/chunk/parameter_ffi_call_out.rs, src/codegen/function_body_chunk.rs, src/codegen/return_value.rs, src/library.rs, src/parser.rs, src/writer/to_code.rs
=> Throwable functions

src/codegen/function.rs, src/codegen/object.rs
=>  	Remove unneeded generated end extra line and add extra empty lines between trait function declarations

src/codegen/object.rs
=> Remove extra empty line in "impl<O: Upcast<"

src/codegen/function.rs
=> Remove empty line on hidden functions

src/codegen/translate_to_glib.rs
See https://github.com/gtk-rs/glib/pull/92
=> `to_glib_container` returns a `Stash`

Cargo.lock, Cargo.toml, src/codegen/doc/mod.rs, src/codegen/mod.rs, src/config/config.rs, src/config/work_mode.rs, src/library.rs, src/main.rs, src/parser.rs
=> Add doc generation

src/analysis/functions.rs, src/analysis/rust_type.rs, src/codegen/parameter.rs, src/codegen/return_value.rs, src/codegen/sys/ffi_type.rs, src/codegen/sys/functions.rs, src/codegen/sys/lib_.rs, src/codegen/translate_from_glib.rs, src/traits.rs
=> Make "ignored" classes, interfaces or records ignored rust types as well

src/config/functions.rs, src/config/gobjects.rs, src/config/identables.rs, src/config/members.rs, src/config/mod.rs, src/traits.rs
=> Extract equal functionality for config items to traits

src/analysis/object.rs, src/analysis/signals.rs, src/analysis/trampolines.rs, src/codegen/signal.rs
Change
```
GLArea:
//#[cfg(feature = "v3_16")]
//pub fn connect_create_context<Unsupported or ignored types>(&self, f: F) -> u64 {
//    TODO: connect to trampoline
//}
//#[cfg(feature = "v3_16")]
//pub fn connect_render<Unsupported or ignored types>(&self, f: F) -> u64 {
//    TODO: connect to trampoline
//}
Overlay:
//pub fn connect_get_child_position<Unsupported or ignored types>(&self, f: F) -> u64 {
//    TODO: connect to trampoline
//}
```
to
```
GLArea:
//#[cfg(feature = "v3_16")]
//pub fn connect_create_context<Unsupported or ignored types>(&self, f: F) -> u64 {
//    Ignored return value Gdk.GLContext
//}
//#[cfg(feature = "v3_16")]
//pub fn connect_render<Unsupported or ignored types>(&self, f: F) -> u64 {
//    Ignored context: Gdk.GLContext
//}
Overlay:
//pub fn …
```
=> Write error list for commented signals

src/analysis/c_type.rs, src/analysis/ffi_type.rs, src/analysis/mod.rs, src/analysis/namespaces.rs, src/analysis/signals.rs, src/analysis/trampolines.rs, src/codegen/sys/ffi_type.rs, src/codegen/trampoline.rs
=> Trampoline namespaces

src/analysis/conversion_type.rs, src/analysis/ref_mode.rs, src/analysis/return_value.rs, src/analysis/rust_type.rs, src/library_postprocessing.rs
Currently only enabled union in `Gtk` is `Event`
=> Allow union parameters

src/analysis/rust_type.rs, src/library_postprocessing.rs
For https://github.com/gtk-rs/gtk/pull/340
=> Detect union ctype

src/analysis/imports.rs, src/analysis/object.rs, src/analysis/record.rs, src/codegen/enums.rs, src/codegen/flags.rs
Fix use `glib::` errors in https://github.com/gtk-rs/glib/issues/135 and https://github.com/gtk-rs/glib/pull/136
=> Fix imports from glib when generate glib

src/analysis/signals.rs, src/config/signals.rs
Fix error found in https://github.com/gtk-rs/gtk/issues/381
=> Add signal version override

src/codegen/enums.rs
For https://github.com/gtk-rs/gtk/issues/381#issuecomment-247492968
=> Enums primary detects error domain by function "quark"

src/analysis/trampolines.rs, src/codegen/trait_impls.rs, src/config/signals.rs
Fix generating Display for records with throwable `to_string` for #281
=> Throwable to string

src/analysis/trampolines.rs, src/config/signals.rs
=> Add object.signal.return.nullable config

src/codegen/sys/lib_.rs, src/library.rs, src/parser.rs
This is a resubmit of #276 with the commits squashed and some reordering of functions in codegen/sys/lib_.rs for diff readability.
=> Parse fields in classes and generate correct class structs (resubmit)

Cargo.lock, Cargo.toml, appveyor.yml, tests/sys/sys_build/Cargo.toml
Attempt fixing build on appveyor with latest stable rust
Prerequisite for https://github.com/gtk-rs/gir/pull/300
=> Update rust version in appveyor.yml

src/analysis/rust_type.rs
Part of #283.
Improved version of #284 
I also add PR in gtk with changes (only one file `Settings.rs`)
=> Add long and short types

src/analysis/bounds.rs, src/analysis/child_properties.rs, src/analysis/imports.rs, src/analysis/mod.rs, src/analysis/object.rs, src/codegen/child_properties.rs, src/codegen/child_property_body.rs, src/codegen/mod.rs, src/codegen/object.rs, src/config/child_properties.rs, src/config/gobjects.rs, src/config/mod.rs, src/writer/primitives.rs
Part of https://github.com/gtk-rs/gtk/issues/392
WIP as support only `gboolean` and `gint`
=> Generate child properties

src/analysis/functions.rs, src/codegen/record.rs
Affected files in gtk:
a) Removed one line after Impl: 
src/auto/css_section.rs
src/auto/paper_size.rs
src/auto/selection_data.rs
src/auto/text_attributes.rs
src/auto/text_iter.rs
src/auto/tree_path.rs
b) Removed empty Impl at all in src/auto/tree_iter.rs
=> Remove records empty line

src/analysis/functions.rs, src/analysis/mod.rs, src/analysis/object.rs, src/analysis/record.rs, src/analysis/signatures.rs, src/analysis/supertypes.rs, src/codegen/doc/mod.rs, src/codegen/function.rs, src/codegen/general.rs, src/codegen/objects.rs, src/codegen/records.rs
=> Don't generate a method if a parent already has it

src/codegen/sys/lib_.rs
Part of https://github.com/gtk-rs/gtk/issues/434
@GuillaumeGomez take look please
=> Fix GValue generation in gobject-sys

src/analysis/bounds.rs, src/analysis/functions.rs, src/analysis/parameter.rs, src/analysis/trampolines.rs, src/writer/primitives.rs
@GuillaumeGomez I leave merge to you, don't merge if it conflict with your plans.
=> Moved bounds logic out parameter

src/analysis/properties.rs, src/codegen/enums.rs
Removes lines in `enums.rs` if no `impl ErrorDomain` generated.
In `pango` in allow remove dependency to `glib-sys` added in https://github.com/gtk-rs/pango/pull/54
```
use glib_ffi;
use glib::error::ErrorDomain;
```
=> Remove unused uses in generated enums.rs

src/analysis/object.rs
=> Add use Object for interfaces with properties

src/analysis/properties.rs, src/parser.rs
Affected modules gio, gdk, gtk
=> Fixed processing of properties "construct_only" flag

src/codegen/sys/lib_.rs
This allows for more struct fields to be correctly generated.
=> Handle pointers to unions and special-case GMutex and GWeakRef unions

src/codegen/sys/lib_.rs
> Depends on (and includes) https://github.com/gtk-rs/gir/pull/343
These look like
```C
struct {
[..]
union {
gpointer _gst_reserved[GST_PADDING];
struct {
gint some_new_field;
} abi;
} ABI;
}
```
And can be directly replaced with the _gst_reserved variant of the enum. The *reserved* variant is always the biggest one, otherwise the C library broke its ABI.
=> Add special handling for "padding unions" as used in GStreamer structs

README.md
@EPashkin: I didn't have much to do in here, just a bit rereading. Do you want to take the ownership of the commit? It's mostly your work after all (and thanks again for it, it's awesome!).
=> Add TOML files explanations

src/analysis/object.rs
Closes #309 
Affect `Gio.Action` and `Gio.AppInfo`
=> Generate interfaces functions

src/analysis/properties.rs
=> Add default values for fundamental types and Records

README.md, src/analysis/child_properties.rs, src/analysis/functions.rs, src/analysis/signals.rs, src/codegen/child_properties.rs, src/codegen/function.rs, src/codegen/general.rs, src/codegen/signal.rs, src/config/child_properties.rs, src/config/functions.rs, src/config/signals.rs
=> Added doc_hidden option for functions, properties and child_properties

src/codegen/function_body_chunk.rs
cc @EPashkin 
For https://github.com/gtk-rs/gtk/pull/499
=> Always make check_init_assert first in chunks

src/codegen/function_body_chunk.rs, src/codegen/translate_to_glib.rs
Fix of https://github.com/gtk-rs/gtk/issues/501
=> Fix into parameters lifetime

src/analysis/bounds.rs
Fix of https://github.com/gtk-rs/gtk/issues/505
=> Fix generating properties with Object descendants type

README.md
Forgotten `readme` update for #364
=> Update trait config description

README.md, src/codegen/sys/functions.rs, src/config/functions.rs
=> Add sys function config is_windows_utf8

src/codegen/flags.rs, src/codegen/sys/cargo_toml.rs, src/codegen/sys/lib_.rs
Minor API changes for the macro. After this, all the repos have to be regenerated and the Cargo.tomls updated to 0.9
=> Update to bitflags 0.9

src/analysis/out_parameters.rs, src/analysis/rust_type.rs, src/chunk/chunk.rs, src/codegen/function_body_chunk.rs, src/writer/to_code.rs
=> Add support for String/PathBuf out parameters

src/analysis/rust_type.rs
These are not implemented yet.
See https://github.com/gtk-rs/gir/pull/389#issuecomment-309989621
=> Don't support String InOut parameters and &mut String Out parameters

src/codegen/enums.rs
Part of #123
cc @GuillaumeGomez, @sdroege 
Make enums look as https://github.com/gtk-rs/gir/issues/123#issuecomment-309222862
=> Fix enums from_glib unsafety, store unknown value

src/codegen/sys/cargo_toml.rs, src/codegen/sys/lib_.rs, src/config/config.rs, src/config/external_libraries.rs, src/config/mod.rs
Added extra config for external libraries
```
[options]
external_libraries = [
"GLib",
"Gdk",
"GdkPixbuf",
]
[external_libraries]
crate-name="NameSpace"
```
Edit: switched parameters
=> Add customization of crate names for external libraries

src/codegen/alias.rs
(Another issue when generating pango haha)
cc @EPashkin
=> Import everything from auto in case a type is an alias of an auto type

src/library.rs, src/main.rs, src/update_version.rs
And as promised, here it is! However the code isn't really nice so if you have any ideas of improvement, I'll gladly update.
=> Allow to have a better version prediction for functions

src/codegen/sys/lib_.rs
=> Fix indent

src/analysis/record.rs, src/codegen/sys/functions.rs, src/codegen/sys/lib_.rs, src/codegen/translate_from_glib.rs, src/library.rs, src/parser.rs
See individual commits. Also cc @Luke-Nukem
=> Generate get_type() functions for unions and some cleanup

src/codegen/sys/lib_.rs, src/library.rs, src/parser.rs
See the individual commits, also cc @Luke-Nukem
=> Fix generation of anonymous unions and structs-in-unions

README.md, src/analysis/function_parameters.rs, src/analysis/functions.rs, src/config/functions.rs
Part of https://github.com/gtk-rs/gtk/issues/477 and https://github.com/gtk-rs/gir/issues/264.
=> Add detection of length input parameters

src/analysis/function_parameters.rs, src/analysis/functions.rs, src/analysis/out_parameters.rs, src/analysis/rust_type.rs
https://github.com/gtk-rs/gir/issues/388
=> Add support for arrays of fundamental types

src/config/child_properties.rs, src/config/error.rs, src/config/functions.rs, src/config/gobjects.rs, src/config/members.rs, src/config/properties.rs, src/config/signals.rs, src/parser.rs
=> Add checkup for toml keys

src/analysis/object.rs, src/analysis/properties.rs, src/analysis/ref_mode.rs, src/analysis/trampoline_parameters.rs, src/analysis/trampolines.rs, src/codegen/object.rs, src/codegen/trampoline.rs, src/nameutil.rs
https://github.com/gtk-rs/gir/issues/437
=> Add support for property notifications (notify signal)

src/analysis/functions.rs, src/analysis/object.rs, src/analysis/out_parameters.rs, src/chunk/mod.rs, src/codegen/doc/mod.rs, src/codegen/object.rs, src/codegen/property_body.rs, src/codegen/record.rs, src/config/error.rs, src/config/gobjects.rs, src/config/mod.rs, src/main.rs, src/nameutil.rs, src/parser.rs
cc @GuillaumeGomez 
@sdroege Please test this on gstreamer, it must don't produce any difference
=> Fix clippy warnings

src/analysis/info_base.rs, src/analysis/object.rs, src/analysis/record.rs
See https://github.com/gtk-rs/sourceview/pull/15
=> Fix wrong version detection for "GtkSourceStyle"

README.md
=> Improve FFI part a bit

Cargo.lock, Cargo.toml, src/main.rs
=> Remove crate time

src/analysis/properties.rs, src/analysis/signals.rs, src/codegen/signal.rs
https://github.com/gtk-rs/glib/issues/229
=> Use a newtype wrapper for the signal handler IDs

src/analysis/trampoline_parameters.rs
After https://github.com/gtk-rs/gir/pull/453 conversion_type already `ConversionType::Borrow`
=> Fix wrong warning

src/codegen/doc/mod.rs
I'll add for properties a bit later. I found a bug on rustdoc-stripper and I'm trying to fix it.
=> Add doc for signals

src/codegen/doc/mod.rs
Fixes #460.
And here is the second part!
cc @EPashkin 
(I'll regenerate docs for crates once merged.)
=> Add property doc generation

src/codegen/general.rs, src/codegen/sys/functions.rs, src/codegen/sys/lib_.rs
Since [rustc/43348](https://github.com/rust-lang/rust/pull/43348) has been merged, we can now do this!
=> Add dox feature in order to build all docs, whatever the platform

src/codegen/sys/cargo_toml.rs
Needed by https://github.com/rust-lang/rust/pull/44892
=> Generate dox feature as well

src/codegen/sys/lib_.rs
Part of https://github.com/gtk-rs/gir/pull/467
Fixed sys documentation generation.
Tested on https://github.com/gtk-rs/gdk-pixbuf/pull/50.
=> Remove wrong "dox" configs

src/analysis/functions.rs
Part of https://github.com/gtk-rs/gir/pull/490
=> Add `use gio_ffi` if needed

src/chunk/chunk.rs, src/codegen/function_body_chunk.rs, src/writer/to_code.rs
Second fix for https://github.com/gtk-rs/gir/pull/490
=> Add callback_guard to async trampolines

src/codegen/sys/lib_.rs
=> Fix invalid [c_void] debug implementation

src/analysis/properties.rs, src/codegen/property_body.rs
See https://github.com/gtk-rs/glib/pull/266
=> Use new Value::from_type() function for property getters

README.md, src/main.rs, src/update_version.rs
Part of https://github.com/gtk-rs/gtk/issues/600
=> Add version override for enums and flags

README.md, src/codegen/mod.rs, src/config/config.rs, src/config/work_mode.rs, src/library.rs, src/main.rs
=> Add new mode to see not bound type

src/analysis/rust_type.rs
Based on idea of https://github.com/gtk-rs/glib/pull/248
=> Add generation `Char` and `UChar` parameters

src/analysis/symbols.rs, src/codegen/doc/mod.rs
Part of https://github.com/gtk-rs/gir/issues/500
=> Fix renamed trait docs

src/analysis/bounds.rs, src/analysis/functions.rs, src/chunk/chunk.rs, src/codegen/function_body_chunk.rs, src/writer/to_code.rs
See individual commit messages and https://github.com/gtk-rs/gir/issues/508
=> Various async function improvements

src/codegen/sys/lib_.rs
Fix https://github.com/gtk-rs/gir/issues/512
=> Add detecting and including custom modules on sys mode

src/codegen/enums.rs, src/codegen/flags.rs, src/codegen/function.rs, src/codegen/general.rs, src/codegen/properties.rs, src/codegen/signal.rs, src/config/members.rs, src/env.rs
=> Generate deprecated attribute on deprecated functions

src/chunk/chunk.rs, src/chunk/parameter_ffi_call_out.rs, src/codegen/function_body_chunk.rs, src/config/gobjects.rs, src/writer/to_code.rs
Fix error, found in https://github.com/gtk-rs/sourceview/pull/35
cc @GuillaumeGomez, @sdroege 
PS. PR contains function extracting, so better check by commits
=> Fix async for boxed 

src/analysis/properties.rs, src/analysis/signatures.rs
Part of https://github.com/gtk-rs/gtk/issues/608, #511
=> Fix property parent check

README.md, src/analysis/record.rs, src/analysis/record_type.rs, src/analysis/ref_mode.rs, src/codegen/general.rs, src/codegen/record.rs, src/config/gobjects.rs
Alternative of https://github.com/gtk-rs/gir/pull/542
Add `record_boxed` config for records.
=> Allow generate record with g_boxed_copy and g_boxed_free

src/analysis/function_parameters.rs, src/analysis/types.rs, src/codegen/sys/lib_.rs, src/library.rs, src/parser.rs
Part of #529
Followup of https://github.com/gtk-rs/gir/pull/544
cc @GuillaumeGomez,  @sdroege, @tmiasko
=> Alternative of General support for disguised types

src/codegen/function_body_chunk.rs, src/codegen/trampoline.rs
Part of https://github.com/gtk-rs/glib/pull/250
=> Remove adding callback_guard

src/analysis/bounds.rs, src/analysis/functions.rs, src/main.rs
Fix [panic when generating gdk-pixbuf-sys](https://github.com/gtk-rs/gir/pull/548#issuecomment-366976512)
Also see #549
@tmiasko please, can you confirm that it works without adding "generate" to sys?
=> Fix panic on generating gdk-pixbuf-sys

README.md, src/analysis/constants.rs, src/analysis/mod.rs, src/codegen/constants.rs, src/codegen/mod.rs, src/config/constants.rs, src/config/gobjects.rs, src/config/mod.rs
Output based on the manual bindings in the GLib:
https://github.com/gtk-rs/glib/blob/master/src/lib.rs#L139-L168
The output for GIO can be seen @ <https://github.com/MathieuDuponchelle/gio/blob/master/src/auto/mod.rs> and <https://github.com/MathieuDuponchelle/gio/blob/master/src/auto/constants.rs>
=> Add support for string constants

src/codegen/sys/lib_.rs
Helper for https://github.com/gtk-rs/sys/issues/82
=> Use GObject status when generating types

README.md, src/analysis/override_string_type.rs, src/config/string_type.rs
.. and update readme
Closes #592
=> Rename "string" in string_type to "utf8" to match glib type

Cargo.lock, Cargo.toml, src/codegen/sys/statics.rs
=> Add ignore clipy warnings in sys

README.md, src/analysis/imports.rs, src/analysis/namespaces.rs, src/codegen/general.rs, src/codegen/mod.rs, src/codegen/object.rs, src/codegen/sys/lib_.rs, src/config/config.rs, src/nameutil.rs
Part of https://github.com/gtk-rs/glib/issues/337
Example generation https://github.com/EPashkin/glib/tree/tmp_gobject
=> Gobject generation

src/codegen/enums.rs, src/codegen/flags.rs
However before merging, I'd like to be able to confirm that it works (on GObject) but I wasn't able to generate the GObject files for some reason... Am I missing something?
=> Prevent some useless generations

src/codegen/flags.rs
=> fix invalid multiple flag import

src/codegen/enums.rs
Part of https://github.com/gtk-rs/glib/issues/363
=> Generate glib::Quark based ErrorDomain for enums

src/analysis/conversion_type.rs
Part of https://github.com/gtk-rs/gtk/pull/684
=> Make ConversionType for glib::Quark Scalar

src/library.rs
=> List not bound parents in not bound mode

src/library.rs
The current output is a bit too noisy (especially on gtk haha).
=> Remove parent duplicates for not bound mode

src/library.rs
=> Show not bound functions and methods

src/analysis/bounds.rs, src/codegen/function.rs
See https://github.com/gtk-rs/gio/pull/179#pullrequestreview-192970234
cc @sdroege, @GuillaumeGomez
=> Fix unused bounds in futures

src/analysis/return_value.rs
Part of https://github.com/gtk-rs/gir/issues/655 and https://github.com/gtk-rs/gio/pull/185
Without https://github.com/gtk-rs/gir-files/pull/32 only need regen in glib, gdk
=> Use nullable attribute on constructor return value

src/codegen/sys/mod.rs
=> Fix invalid crate name generation

src/codegen/doc/format.rs, src/codegen/function_body_chunk.rs, src/codegen/signal_body.rs, src/codegen/sys/ffi_type.rs, src/codegen/sys/lib_.rs, src/codegen/sys/tests.rs, src/config/child_properties.rs, src/config/constants.rs, src/config/derives.rs, src/config/external_libraries.rs, src/config/functions.rs, src/config/gobjects.rs, src/config/ident.rs, src/config/members.rs, src/config/parsable.rs, src/config/properties.rs, src/config/signals.rs, src/library.rs, src/parser.rs, src/version.rs
=> Fix some clippy warnings

src/codegen/doc/mod.rs
Fix error https://github.com/gtk-rs/lgpl-docs/pull/54#discussion_r268402749
=> Don't generate docs for totally deprecated items

src/analysis/class_builder.rs, src/codegen/object.rs, src/library.rs
=> Dont generate builders constraint and minor fixes

README.md
=> Add link to gir tutorial

src/analysis/properties.rs, src/analysis/signals.rs
Closes #772
@GuillaumeGomez, @sdroege  Seems this fix is enough,
or you prefer some general solution like special function for this?
cc @fkrull
=> Don't bring trait ObjectType into scope

src/analysis/bounds.rs
=> Don't panic on ignored parameter in callback

src/codegen/sys/build.rs
Part of https://github.com/gtk-rs/sys/pull/141
=> Add warning to gobject-sys's build script

src/codegen/sys/fields.rs
Part of https://github.com/gtk-rs/sys/pull/138
=> Don't derive Copy, Clone for truncated in sys mode

src/codegen/doc/mod.rs, src/library.rs, src/parser.rs
Fix #803 again, now with doc update
cc @GuillaumeGomez, @Boiethios
=> Parse "doc-deprecated" tag in class and interface

src/codegen/sys/build.rs, src/codegen/sys/cargo_toml.rs
Fixes #821.
cc @EPashkin @sdroege @Boiethios
=> Use dox instead of creating new feature

README.md, src/analysis/functions.rs, src/config/functions.rs
Part of https://github.com/gtk-rs/gir/issues/829
=> Add flag to disable future generation

README.md
=> Add link to gir reference

README.md
=> Add link to schema for .gir files

src/library.rs
=> Correctly detect not generated builders

src/analysis/class_builder.rs
Part of https://github.com/gtk-rs/gtk/issues/892
=> Class builder includes properties of  implemented interfaces

Cargo.lock, Cargo.toml, src/codegen/sys/tests.rs, src/config/external_libraries.rs, src/config/property_generate_flags.rs, src/library.rs
And also update dependencies to the latest versions.
=> Use Box<dyn Error> instead of Box<Error>

src/analysis/class_builder.rs
=> Fix merge conflict

src/codegen/return_value.rs
Fixes this issue: https://github.com/gtk-rs/gdk/pull/311/files#diff-b8ec742bb894a18319d0da63b74b5770R52
cc @EPashkin
=> Fix missing parenthesis on return types

src/codegen/function_body_chunk.rs
Fixes https://github.com/gtk-rs/gir/issues/819
=> Add missing from_glib conversion for Pid

src/codegen/function.rs, src/codegen/object.rs
=> Add deriving Default, Clone to builders

src/analysis/imports.rs
This is in order to reduce the noise before running `cargo fmt`.
=> generate imports in the same order as rustfmt

src/codegen/doc/mod.rs, src/parser.rs
=> Fix signal doc

src/library_postprocessing.rs
Fix #880 
cc @sdroege , @GuillaumeGomez
=> Fix fields with fixed size array type

src/library_postprocessing.rs
Finishing touch for https://github.com/gtk-rs/gir/pull/881
=> Remove unused variable

Cargo.lock, Cargo.toml, src/codegen/constants.rs, src/codegen/doc/format.rs, src/codegen/doc/mod.rs, src/codegen/sys/functions.rs, src/nameutil.rs
This works without requiring any macros.
----
@EPashkin @GuillaumeGomez any opinions?
=> Use once_cell::sync::Lazy instead of lazy_static

src/analysis/functions.rs, src/analysis/safety_assertion_mode.rs, src/chunk/chunk.rs, src/codegen/function.rs, src/codegen/function_body_chunk.rs, src/writer/mod.rs, src/writer/to_code.rs
=> Simplify chunk::Assert* and fix missing init check for async_future methods

.travis.yml
=> Add a check to avoid unforeseen failures

README.md, src/analysis/object.rs, src/codegen/object.rs, src/config/gobjects.rs
This work is to enable work to complete https://github.com/gtk-rs/gtk/issues/984 by allowing us to register something in `gtk::ApplicationBuilder::build()`
=> Builder postprocess

src/analysis/bounds.rs
See https://github.com/gtk-rs/gio/pull/292
----
CC @EPashkin @GuillaumeGomez
=> Consider nullability for async function return values

README.md, src/codegen/sys/build.rs, src/config/config.rs
Part of https://github.com/gtk-rs/sys/pull/167#issuecomment-623858337
cc @sdroege , @GuillaumeGomez , @kinnison
=> Add options.split_build_rs

src/codegen/sys/build.rs
=> Add static lifetime to generated build_version.rs

README.md, src/analysis/functions.rs, src/analysis/safety_assertion_mode.rs, src/analysis/special_functions.rs, src/config/functions.rs, src/config/string_type.rs, src/config/work_mode.rs, src/library.rs
Sometimes this is misdetected, see https://gitlab.freedesktop.org/gstreamer/gstreamer-rs/-/issues/211
CC @EPashkin @GuillaumeGomez
=> Allow overriding safety assertions for functions

README.md
Found in https://github.com/gtk-rs/gio/pull/303#discussion_r434857253
=> Fix wrongly written `object.function.return`

src/analysis/class_builder.rs, src/config/config.rs, src/config/gobjects.rs, src/library.rs, src/parser.rs
=> Allow to ignore builders

README.md
=> Update builder documentation

src/codegen/sys/build.rs, src/codegen/sys/cargo_toml.rs, src/nameutil.rs
Use system-deps instead of our custom deps handing code.
[Tested with gstreamer-sys](https://gitlab.freedesktop.org/gdesmott/gstreamer-rs-sys/pipelines/165046).
cc @sdroege
=> Use system-deps

src/codegen/sys/cargo_toml.rs
=> Remove deleting pkg_config

src/codegen/doc/mod.rs
CC @EPashkin @GuillaumeGomez 
Then it's only not supported by rustdoc-stripper... which also mishandles enums currently.
=> Generate docs for bitfields too

src/codegen/sys/cargo_toml.rs, src/codegen/sys/lib_.rs, src/nameutil.rs
import library needs to be explicitly linked
=> Specify link attribute for Windows to be happy

src/codegen/enums.rs, src/library.rs, src/library_postprocessing.rs, src/parser.rs
Fixes https://github.com/gtk-rs/gir/issues/969
=> Properly handle error-domain

src/codegen/general.rs, src/codegen/sys/functions.rs, src/codegen/sys/statics.rs
Fixes #987 
I'll send the matching PR for gtk-rs once this one is merged.
=> Generate doc cfg attributes for more beautiful docs

src/analysis/properties.rs, src/codegen/properties.rs
See https://github.com/gtk-rs/gtk-rs/pull/156
=> This is not needed any longer

src/config/members.rs
Missed this in https://github.com/gtk-rs/gir/pull/977
Not a big deal, but that will remove some error logs.
=> config/members: add manual to wanted check

.github/workflows/main.yaml, tests/sys/atk-sys/Cargo.toml, tests/sys/gdk-pixbuf-sys/Cargo.toml, tests/sys/gdk-sys/Cargo.toml, tests/sys/gio-sys/Cargo.toml, tests/sys/glib-sys/Cargo.toml, tests/sys/gobject-sys/Cargo.toml, tests/sys/gtk-sys/Cargo.toml, tests/sys/pango-sys/Cargo.toml, tests/sys/secret-sys/Cargo.toml, tests/sys/sys_build/Cargo.toml
I regenerated the tests cargo files. :)
=> Add 2018 edition to tests

src/library_postprocessing.rs
=> don't be verbose on missing c:type on internal fields

src/library_postprocessing.rs
These always show up in the .gir file but for final types there wouldn't
be any fields inside it. A proper instance struct needs to contain at
least the field for the parent type's instance struct.
Fixes https://github.com/gtk-rs/gir/issues/1013
=> Improve final type heuristic to also check for unknown instance structs

src/analysis/functions.rs, src/codegen/function.rs, src/codegen/general.rs, src/codegen/trait_impls.rs
(At least part of) https://github.com/gtk-rs/gir/issues/909.
Was handled while preparing https://github.com/gtk-rs/gir/issues/963.
=> Doc aliases for C & renamed functions

src/codegen/enums.rs, src/codegen/flags.rs
Part of https://github.com/gtk-rs/gtk-rs/issues/197
=> Make calls to from_glib unsafe

src/codegen/sys/cargo_toml.rs
For [1] we need to override the target library version because 1.20 does not exist yet. Gir keeps overwriting this value making it impossible to check such changes in.
As cleanup remove the unnecessary get_mut in set_string: insert already replaces an existing value if the given key exists.
[1]: https://gitlab.freedesktop.org/gstreamer/gstreamer-rs/-/merge_requests/649#note_723814
=> cargo_toml: Do not overwrite system-deps version if already set

src/codegen/object.rs
Goes along with https://github.com/gtk-rs/gtk-rs/pull/219.
=> Use new glib::Object::new() syntax

src/codegen/general.rs, src/codegen/translate_from_glib.rs
Goes along with https://github.com/gtk-rs/gtk-rs/pull/220.
=> Use `wrapper!` instead of `glib_wrapper!`

src/codegen/constants.rs, src/codegen/enums.rs
You can see the regen PR [here](https://github.com/gtk-rs/gtk-rs/pull/222).
=> Generate doc aliases for enums and constants too

src/analysis/return_value.rs
Fixes the issue encountered in https://github.com/gtk-rs/gtk-rs/pull/234
=> Fix import of BoolError in glib

src/codegen/doc/mod.rs
=> Add documentation in case this is an abstract class

Cargo.lock, src/codegen/sys/tests.rs
=> Fix new clippy warning in generated C tests

src/analysis/bounds.rs, src/analysis/out_parameters.rs
Both commits needed for https://github.com/gtk-rs/gtk-rs/pull/307
=> Consider nullability of out parameters in normal and async functions

README.md, src/analysis/safety_assertion_mode.rs, src/writer/mod.rs
see https://github.com/gtk-rs/gtk4-rs/pull/196
=> assertions: add a not initialized variant

src/analysis/enums.rs, src/analysis/flags.rs, src/analysis/properties.rs, src/codegen/enums.rs, src/codegen/flags.rs, src/codegen/property_body.rs, src/codegen/signal.rs
See https://github.com/gtk-rs/gtk-rs/pull/454
=> Value trait refactoring

src/codegen/enums.rs, src/codegen/flags.rs, src/codegen/special_functions.rs, src/codegen/trampoline_to_glib.rs, src/codegen/translate_to_glib.rs
Needed for https://github.com/gtk-rs/gtk-rs/issues/410
A PR will be opened against gtk-rs with the required glib changes
=> codegen: take Self for Copy types

src/analysis/out_parameters.rs
When generating a function with an output parameter which type is an alias, the actual type was not checked for additional imports.
Issue found auto-generating `gst-base::BaseSink::wait`.
=> out_param: follow aliases for imports

src/codegen/object.rs
fix a missing element from #1123
=> codegen: add missing } for build pattern

src/analysis/bounds.rs, src/analysis/child_properties.rs, src/analysis/functions.rs, src/analysis/out_parameters.rs, src/analysis/properties.rs, src/analysis/return_value.rs, src/analysis/rust_type.rs, src/analysis/trampolines.rs, src/codegen/child_properties.rs, src/codegen/object.rs, src/codegen/parameter.rs, src/codegen/properties.rs, src/codegen/return_value.rs, src/codegen/trampoline.rs, src/codegen/translate_from_glib.rs, src/config/error.rs, src/library_postprocessing.rs, src/parser.rs
See https://github.com/gtk-rs/gtk-rs-core/pull/3.
I also renamed the function specifiers for `RustTypeBuilder` that I introduced in https://github.com/gtk-rs/gir/pull/1092/commits/c43d9a5c8314631ccf7350e5750d7df96e49c625 because I thought they were uselessly verbose.
=> Use try_from_glib shortcut

src/codegen/object.rs
=> codegen/object: Add missing deprecation attribute to builders

src/codegen/doc/mod.rs, src/codegen/object.rs
=> docs: generate docs for builder properties

src/codegen/doc/mod.rs
=> docs: generate docs for global functions

src/codegen/object.rs
=> codgen: generate a builder method for objects with a Builder 

src/codegen/doc/mod.rs
Otherwise some enum members are not found
=> docs: properly look for renamed enum members

src/codegen/doc/mod.rs
=> docs: look for renamed properties getters/setters

src/codegen/object.rs
=> codgen: make the builder method doc slightly better formatted

src/codegen/general.rs
Example: https://github.com/gtk-rs/gtk3-rs/compare/master...GuillaumeGomez:regen?expand=1
=> Generate doc aliases on items in wrapper! macro

README.md, src/codegen/enums.rs, src/codegen/flags.rs, src/codegen/general.rs, src/codegen/object.rs, src/codegen/record.rs, src/codegen/trait_impls.rs, src/config/members.rs
Fixes #1081.
You can see the result there: https://github.com/gtk-rs/gtk4-rs/compare/master...GuillaumeGomez:regen?expand=1
=> Add support for cfg_condition on enum variants and bitfields and fix cfg_condition for enums and bitfields

src/codegen/signal.rs
You can see the results there: https://github.com/gtk-rs/gtk3-rs/compare/master...GuillaumeGomez:regen?expand=1
=> Don't generate duplicated doc aliases

src/analysis/functions.rs, src/analysis/out_parameters.rs, src/analysis/properties.rs, src/analysis/record.rs, src/analysis/rust_type.rs, src/codegen/enums.rs, src/codegen/flags.rs, src/codegen/function_body_chunk.rs, src/codegen/general.rs, src/codegen/property_body.rs, src/codegen/record.rs, src/codegen/return_value.rs, src/codegen/sys/tests.rs, src/codegen/trait_impls.rs, src/config/functions.rs, src/config/members.rs, src/nameutil.rs
I took the commit from https://github.com/gtk-rs/gir/pull/1191 so it's merged faster.
=> Fix clippy lints

src/codegen/doc/format.rs
=> Generate warnings for code examples

src/codegen/doc/mod.rs
Some properties have already a getter/setter already and there's no need to try to document them
based on the property documentation. This removes the extra information dumped in the docs.md file in order to make finding missing/undocumented types easier
=> docs: don't generate for properties with getter/setter

src/codegen/sys/cargo_toml.rs
=> Update system-deps version in generated crates

book/src/config_api.md, src/analysis/bounds.rs, src/analysis/functions.rs, src/analysis/rust_type.rs, src/analysis/trampoline_parameters.rs, src/config/functions.rs
Fixes #1209.
GTK3 PR there: https://github.com/gtk-rs/gtk3-rs/compare/master...GuillaumeGomez:nullable-callback-param?expand=1
=> Config for nullable callback param

src/analysis/functions.rs, src/analysis/trampoline_parameters.rs, src/analysis/trampolines.rs
Fixes feature added in https://github.com/gtk-rs/gir/pull/1217.
=> Fix parameter setting by applying it to the rust_parameters field as well

src/codegen/sys/cargo_toml.rs, tests/sys/atk-sys/Cargo.toml, tests/sys/gdk-pixbuf-sys/Cargo.toml, tests/sys/gdk-sys/Cargo.toml, tests/sys/gio-sys/Cargo.toml, tests/sys/glib-sys/Cargo.toml, tests/sys/gobject-sys/Cargo.toml, tests/sys/gtk-sys/Cargo.toml, tests/sys/pango-sys/Cargo.toml, tests/sys/secret-sys/Cargo.toml
I'll send PRs for everything once this is merged.
=> Update to system-deps 5

src/analysis/bounds.rs, src/analysis/child_properties.rs, src/analysis/class_builder.rs, src/analysis/function_parameters.rs, src/analysis/functions.rs, src/codegen/bound.rs, src/codegen/translate_to_glib.rs
See https://github.com/gtk-rs/gtk-rs-core/issues/187
This is not complete yet.
=> Fix support for nullable paths / OsStrings

src/codegen/object.rs
So that we can use `Pad::NONE` instead of crate global `NONE_PAD`.
Fixes https://github.com/gtk-rs/gir/issues/1252
=> codegen: generate NONE constants as associated constants

Cargo.toml, src/analysis/class_builder.rs, src/analysis/constants.rs, src/analysis/functions.rs, src/analysis/object.rs, src/analysis/properties.rs, src/analysis/signals.rs, src/codegen/constants.rs, src/codegen/doc/mod.rs, src/codegen/enums.rs, src/codegen/flags.rs, src/codegen/function.rs, src/codegen/general.rs, src/codegen/object.rs, src/codegen/properties.rs, src/codegen/record.rs, src/codegen/signal.rs, src/codegen/special_functions.rs, src/codegen/sys/build.rs, src/codegen/sys/functions.rs, src/codegen/sys/lib_.rs, src/codegen/trait_impls.rs, src/config/config.rs, src/config/external_libraries.rs, src/env.rs, src/version.rs
Fixes https://github.com/gtk-rs/gir/issues/1231
Fixes https://github.com/gtk-rs/gir/issues/1099
=> per crate min version

Cargo.toml
=> revert edition change

src/codegen/sys/lib_.rs
Based on <https://doc.rust-lang.org/nomicon/ffi.html#representing-opaque-structs>.
You can see the result [here](https://github.com/gtk-rs/gtk3-rs/pull/670).
=> Correctly generate opaque types

src/analysis/object.rs, src/codegen/object.rs
Fixes #976
gtk4-rs PR: https://github.com/gtk-rs/gtk4-rs/pull/722
=> codgen: don't generate empty impl blocks

generator.py
=> Remove "auto" folder when regenarating non-sys crate

src/codegen/sys/cargo_toml.rs, tests/sys/atk-sys/Cargo.toml, tests/sys/gdk-pixbuf-sys/Cargo.toml, tests/sys/gdk-sys/Cargo.toml, tests/sys/gio-sys/Cargo.toml, tests/sys/glib-sys/Cargo.toml, tests/sys/gobject-sys/Cargo.toml, tests/sys/gtk-sys/Cargo.toml, tests/sys/pango-sys/Cargo.toml
Part of https://github.com/gtk-rs/gtk-rs-core/issues/375.
=> Update to system-deps 6

generator.py, src/config/config.rs
Follow-up of #1270.
cc @MarijnS95
=> Move auto folder removal into gir directly

src/codegen/signal.rs
See https://github.com/gtk-rs/gtk-rs-core/pull/366
=> gir: fix per emit_by_name change

src/codegen/sys/statics.rs
Nothing seems to be using it
Fixes #1276
=> sys: stop importing time_t,

src/analysis/functions.rs
=> codgen: trim extra _async in future variants

src/analysis/rust_type.rs
=> analysis: fix logic code in slice of copy types

src/codegen/enums.rs, src/codegen/flags.rs, src/codegen/function.rs, src/codegen/functions.rs, src/codegen/object.rs, src/codegen/record.rs, src/codegen/return_value.rs
You can see the result [here](https://github.com/gtk-rs/gtk-rs-core/compare/master...GuillaumeGomez:regen-must-use?expand=1).
It is the second step of https://github.com/gtk-rs/gtk-rs-core/pull/445.
=> Generate #[must_use] where needed

src/codegen/property_body.rs
Second part of https://github.com/gtk-rs/gtk3-rs/pull/699
=> codgen: go through the safe bindings for child properties

src/codegen/signal.rs, src/codegen/sys/tests.rs
they need more work to work on other platforms for now
=> sys: run ABI tests only under linux

book/src/config_api.md
@bilelmoussaoui what do you think?
=> Mention Default impls for objects with Builders

src/analysis/enums.rs, src/analysis/flags.rs, src/analysis/functions.rs, src/analysis/mod.rs, src/analysis/object.rs, src/analysis/record.rs, src/codegen/doc/gi_docgen.rs
Otherwise causes issue when looking for GtkApplication and you end up with a GApplication link
=> docs: Handle gi-docgen namespaces when looking for types to link

book/book.toml
This adds a GitHub link and "edit" button at the top right.
=> add GitHub urls to book

book/src/config_api.md, src/codegen/enums.rs, src/codegen/flags.rs, src/codegen/mod.rs, src/codegen/object.rs, src/config/gobjects.rs
Fixes #1324.
For now this is a draft because:
* Is the parameter name ok? If not what should we use?
* I chose to let the user put whatever they wanted as default value. Did you have something else in mind?
* I need to add documentation.
=> Add "default_value" parameter

src/codegen/function_body_chunk.rs
fixes https://github.com/gtk-rs/gir/issues/1356
=> Fix UB and clippy::let-and-return in function out variables handling

src/analysis/bounds.rs, src/analysis/constants.rs, src/analysis/conversion_type.rs, src/analysis/ffi_type.rs, src/analysis/function_parameters.rs, src/analysis/functions.rs, src/analysis/object.rs, src/analysis/out_parameters.rs, src/analysis/override_string_type.rs, src/analysis/ref_mode.rs, src/analysis/return_value.rs, src/analysis/rust_type.rs, src/analysis/trampoline_parameters.rs, src/analysis/types.rs, src/codegen/constants.rs, src/codegen/doc/mod.rs, src/codegen/function.rs, src/codegen/function_body_chunk.rs, src/codegen/sys/ffi_type.rs, src/codegen/sys/functions.rs, src/codegen/trampoline_from_glib.rs, src/codegen/translate_from_glib.rs, src/custom_type_glib_priority.rs, src/library.rs, src/library_postprocessing.rs
as those don't have Ext traits, see https://gtk-rs.org/gtk4-rs/git/docs/gdk4/struct.DNDEvent.html#implements
Before
After
=> docs: don't generate implements links for fundamental types

book/src/config_ffi.md, src/codegen/sys/functions.rs, src/config/functions.rs
=> Remove is_windows_utf8 function

src/analysis/child_properties.rs, src/analysis/object.rs, src/analysis/properties.rs, src/analysis/ref_mode.rs, src/codegen/doc/format.rs, src/codegen/doc/mod.rs, src/codegen/sys/cargo_toml.rs, src/codegen/trampoline.rs, src/library.rs, src/writer/to_code.rs, src/writer/untabber.rs
Fixes #1369
See my comment on https://github.com/gtk-rs/gir/issues/1369#issuecomment-1186217934 as the main reason why this issue was opened cannot be fixed from the bindings generator side.
=> analysis: Don't generate duplicate getter/notify/setter from parent type 

book/src/config_api.md, src/analysis/function_parameters.rs, src/analysis/functions.rs, src/codegen/parameter.rs, src/codegen/translate_to_glib.rs, src/config/functions.rs
To make use of the new IntoGlibPtr trait
Fixes the remaining of https://github.com/gtk-rs/gtk-rs-core/issues/50
=> config: Add a move configuration for functions parameters

src/codegen/general.rs, src/codegen/object.rs
See https://github.com/gtk-rs/gtk-rs-core/issues/766
=> Update for `Object::new()` panicking instead of returning a `Result`

book/src/config_ffi.md, src/codegen/sys/cargo_toml.rs, src/config/config.rs, src/config/external_libraries.rs, tests/sys/gdk-sys/Cargo.toml, tests/sys/gtk-sys/Cargo.toml
This also drops an unused option that doesn't seem to be that useful
=> codgen/sys: Properly generate dox features for external libraries

src/codegen/function.rs
Needed for https://github.com/gtk-rs/gtk-rs-core/pull/816
=> Add `#[allow(clippy::should_implement_trait)]` if method is named `default`

src/analysis/function_parameters.rs, src/codegen/translate_to_glib.rs, src/config/functions.rs
Needed for https://github.com/gtk-rs/gtk-rs-core/issues/50
=> analysis: Use the new move trait for in transfer-full params

src/analysis/bounds.rs, src/analysis/child_properties.rs, src/analysis/class_builder.rs, src/analysis/functions.rs, src/analysis/object.rs, src/analysis/properties.rs, src/analysis/signals.rs
Reduce the amount of generated code and drops a bit of unneeded complexity
Fixes #1401
=> analysis: Prefer using glib::prelude::*

src/codegen/enums.rs, src/codegen/flags.rs, src/writer/to_code.rs
=> Inline various enum/flags functions

src/codegen/doc/format.rs, src/codegen/doc/mod.rs
Fixes #1076
Current status:
Signals
Properties
=> docs: Generate properties/signals docs

src/analysis/bounds.rs, src/analysis/function_parameters.rs, src/analysis/functions.rs, src/library.rs, src/parser.rs
Fixes #1428.
@sdroege Can you confirm it fixes the issue please? Don't know when I'll have the time otherwise.
=> Handle user_data renaming

src/codegen/general.rs, src/codegen/object.rs
Depends on https://github.com/gtk-rs/gtk-rs-core/pull/910 . And once this is in, I'll deprecate the other object constructors.
=> Optimize builders

src/codegen/object.rs
This removes quite a bit of unnecessary code and reduces stack memory usage when using builders.
=> Implement object builders around `glib::object::ObjectBuilder`

src/codegen/function.rs, src/codegen/object.rs, src/codegen/properties.rs
Needed for https://github.com/gtk-rs/gtk3-rs/pull/799.
=> Fix missing check in case a type cannot be generated in builders

src/codegen/enums.rs, src/codegen/flags.rs
Needed for the properties macro https://github.com/gtk-rs/gtk-rs-core/pull/494
=> codegen: Generate HasParamSpec for enums/flags

src/analysis/function_parameters.rs
"backport" #1427 to 0.17 branch
=> Backport overflow fix

src/codegen/object.rs
https://github.com/gtk-rs/gtk-rs-core/issues/1093
=> codegen: seal Ext traits

src/codegen/trampoline.rs
See https://github.com/gtk-rs/gtk-rs-core/pull/1144 & https://github.com/gtk-rs/gtk4-rs/issues/1435 for details.
=> codegen: Replace ControlFlow with Propagation

src/config/mod.rs, src/library.rs, src/writer/mod.rs
Still needs to be hooked up in codegen
=> parser: Don't error out for forever scope

book/src/config/api.md, src/codegen/doc/mod.rs, src/codegen/enums.rs, src/codegen/sys/lib_.rs, src/config/members.rs
=> members: drop useless alias config

src/codegen/sys/lib_.rs, src/codegen/sys/tests.rs, src/config/gobjects.rs
See commits, needed for vte4 tests to pass
=> Various sys codegen fixes

src/codegen/function_body_chunk.rs
Another try. This time the generated code is correct
=> Don't cast callbacks as `&Box<T>` but use `&T` instead to make clippy happy

book/src/tutorial/preparation.md
A command in the gir book doesn't work when following the tutorial.
=> book: Fix erroneous command
