src/codegen/sys/ffi_type.rs
src/env.rs

For fully compilable we need fix really unimplemented types in Gir.toml.
I started adding, but have no time until the evening. 48 errors to go.
Also I noticed an unpleasant thing: when changing Gir.toml, `cargo run` recompile the project, and not just launches.
```
[[object]]
name = "Gdk.ModifierType"
status = "ignore"
[[object]]
name = "Gdk.Gravity"
status = "ignore"
[[object]]
name = "Gio.File"
status = "ignore"
[[object]]
name = "Gio.Icon"
status = "ignore"
[[object]]
name = "Pango.FontFace"
status = "ignore"
```

Change ignoring rule for sys crate

---

src/codegen/sys/lib_.rs
src/library.rs
src/parser.rs

...and make the attribute mandatory. Unlike glib:type-name it's always present.

library: change glib_type_name to c_type for Enumeration and Bitfield

---

src/codegen/sys/functions.rs
src/codegen/sys/lib_.rs

An fn type is not nullable so the more faithful representation of the C type is wrapping in an Option.

Wrap extern fns in Option

---

src/analysis/implements.rs
src/analysis/object.rs
src/analysis/parents.rs
src/analysis/rust_type.rs
src/codegen/sys/ffi_type.rs
src/codegen/sys/lib_.rs
src/codegen/sys/statics.rs
src/codegen/widgets.rs
src/gobjects.rs
src/library.rs
src/parser.rs

`c:type` parsed but unused, `name` used only for check for ignoring.
On build some warning about overflowing `pub const G_MININT8:i8 = 128;` etc.
Not sure about names checker functions for `GStatus`.
May be better remove `only_for_gtk` as it contains only `GTK_ENTRY_BUFFER_MAX_SIZE`

Generate consts

---

src/codegen/sys/ffi_type.rs
src/codegen/sys/lib_.rs
src/codegen/sys/statics.rs
src/parser.rs

It seems redundant to use the `_ffi` suffix in the sys crates when referring to sibling crates. All of this is FFI already.

Some comsetic changes

---

src/analysis/functions.rs
src/analysis/return_value.rs
src/analysis/rust_type.rs
src/analysis/type_kind.rs
src/codegen/parameter.rs
src/codegen/return_value.rs
src/codegen/sys/lib_.rs
src/codegen/translate_from_glib.rs
src/codegen/translate_to_glib.rs
src/library.rs
src/parser.rs

`GList` return value is translated to `Vec` correctly now.
Somewhat generalized passing input parameters by reference.
```patch
-    //fn get_children(&self) -> /*Unknown kind*/Unknown rust type: "List TypeId { ns_id: 1, id: 3 }";
-    //fn get_focus_chain(&self, focusable_widgets: /*Unknown kind*/Unknown rust type: "List TypeId { ns_id: 1, id: 3 }") -> bool;
+    fn get_children(&self) -> Vec<Widget>;
+    //fn get_focus_chain(&self, focusable_widgets: /*Unimplemented*/Vec<Widget>) -> bool;
-    //fn set_focus_chain(&self, focusable_widgets: /*Unknown kind*/Unknown rust type: "List TypeId { ns_id: 1, id: 3 }");
+    //fn set_focus_chain(&self, focusable_widgets: /*Unimplemented*/&[Widget]);
-    //fn set_icon(&self, icon: Option<gdk_pixbuf::Pixbuf>);
-    //fn set_icon_from_file(&self, …
```

Partially implement container handling

---

src/codegen/sys/ffi_type.rs

```patch
-    pub fn gtk_menu_item_set_submenu(menu_item: *mut GtkMenuItem, submenu: *mut GtkWidget);
+    pub fn gtk_menu_item_set_submenu(menu_item: *mut GtkMenuItem, submenu: *mut GtkMenu);
```
This will avoid silly upcast workarounds for cases like
```rust
pub fn set_submenu<T: Upcast<Menu>>(&self, submenu: Option<&T>) {
```
not knowing how to upcast to `Widget`.

sys: fix up c_type when the actual type is more specific

---

Gir_Gtk.toml
src/analysis/functions.rs
src/analysis/general.rs
src/analysis/object.rs
src/analysis/parents.rs
src/analysis/return_value.rs
src/analysis/rust_type.rs
src/analysis/type_kind.rs
src/codegen/function.rs
src/codegen/general.rs
src/codegen/translate_from_glib.rs
src/codegen/translate_to_glib.rs
src/codegen/widget.rs
src/codegen/widgets.rs
src/gobjects.rs
src/nameutil.rs

* Move the generated files files to `mod auto` and generate `auto/mod.rs`
* Mangle module, function, parameter names if they conflict with Rust keywords
* Generate non-widget objects
* Add `Bitfield` and `Filename` support
* Minor internal and non-functional output tweaks

Working toward object_reform

---

src/analysis/safety_assertion_mode.rs
src/chunk/chunk.rs
src/codegen/function_body_chunk.rs
src/writer/to_code.rs

Closes #174
Cover both `Option<Widget>` and `&[]` (GLib.List) exclusions cases.

Add skip assertion if use objects or interfaces

---

src/codegen/sys/functions.rs
src/codegen/sys/lib_.rs

Composing `GdkEvent*` wrappers is difficult without any `gdk_event_*` functions, which are associated with the `GdkEvent` union

Generate functions associated with bitfields, enums and unions

---

src/codegen/doc/format.rs
src/codegen/doc/mod.rs

I'll need to improve the regex part because for now, only "#Gtk" objects are replaced in their rust equivalent (the problem is with code blocks, I don't want them to change the C-name to rust-name).
#203

Add doc formatting

---

.travis.yml
src/codegen/function.rs
src/codegen/general.rs
src/codegen/object.rs
src/codegen/record.rs
src/codegen/sys/build.rs
src/codegen/sys/cargo_toml.rs
src/codegen/sys/functions.rs
src/codegen/sys/lib_.rs
src/config/functions.rs
src/config/gobjects.rs
src/config/ident.rs
src/config/members.rs
src/config/mod.rs
src/version.rs
tests/sys/gir-gdk.toml
tests/sys/sys_build/Cargo.toml
tests/sys/test.sh

This should ensure better API stability control as described in https://github.com/gtk-rs/gtk/issues/243 (new upstream library versions support should not introduce breaking changes in code that sticks to earlier versions).

Drop version detection in favor of features, add version support for enum variants

---

appveyor.yml
src/codegen/sys/build.rs
src/codegen/sys/cargo_toml.rs
tests/sys/atk-sys/Cargo.toml
tests/sys/gdk-pixbuf-sys/Cargo.toml
tests/sys/gdk-sys/Cargo.toml
tests/sys/gio-sys/Cargo.toml
tests/sys/glib-sys/Cargo.toml
tests/sys/gobject-sys/Cargo.toml
tests/sys/gtk-sys/Cargo.toml
tests/sys/pango-sys/Cargo.toml
tests/sys/secret-sys/Cargo.toml

- Update pkg-config to 0.3.7.
- Let pkg-config compare version numbers.
- If pkg-config can't be run emit hardcoded library names.
- On Windows always emit hardcoded library names to avoid the `-lmm32` issue.

Build script update

---

src/analysis/mod.rs
src/analysis/namespaces.rs
src/analysis/object.rs
src/analysis/symbols.rs
src/codegen/doc/format.rs
src/codegen/doc/mod.rs
src/env.rs
src/main.rs

Implement more of #203
- Small fixes (#213)
- Add symbol dictionary to translate C names to Rust correctly
- Avoid mangling inline code in backquotes
- Mangle parameter names and change instance parameter to `self`
- Shield XML tags

More intelligent symbol name handling and other docs generator improvements

---

src/codegen/sys/build.rs

The `!hardcode_shared_libs` branch should not print anything because `pkg_config` does that.

sys build script: avoid duplicate metadata when it's not suppressed

---

src/analysis/trampolines.rs

Only affect generation `FileChooser::confirm-override`, all other returning types was lucky and used somewhere else in this module.

Add used types from signal return

---

src/codegen/trampoline.rs

Not final fix of #241.
Changes `Option<&ListBoxRow>` to `&Option<ListBoxRow>` in signal closure

Fix signal parameters with Options

---

Cargo.lock

It no longer rejects comments after table headers
```toml
[table] # comment
```

Update toml again

---

src/codegen/enums.rs

Fix the ffi namespace use in glib. See PR gtk-rs/glib#136 for some of the details.

Proper ffi namespace use in glib

---

src/analysis/mod.rs
src/analysis/object.rs
src/analysis/record.rs
src/codegen/doc/mod.rs
src/codegen/function_body_chunk.rs
src/codegen/objects.rs
src/codegen/records.rs
src/env.rs
src/main.rs

Objects (classes and interfaces) and records ('generated' and 'manual' ones from all namespaces) get analyzed prior to generation. The `Info`s are collected into vectors with no indexing by name yet.
This partially implements #136. Fixes #252.

Add a separate analysis pass

---

src/analysis/ffi_type.rs

Closes #272 
It get no changes to current gtk, but not sure that it good.
Maybe better add comparsion to list ["i8", "u8", ..."] from `ffi_inner`,
or change same string from `ffi_inner` to something with ':'

Don't return from used_ffi_type basic types

---

src/analysis/return_value.rs

Fix #289 
Also helps https://github.com/gtk-rs/gtk/issues/387

Add nullable override for constructors

---

src/analysis/parameter.rs
src/analysis/signals.rs
src/analysis/trampolines.rs
src/config/functions.rs
src/config/gobjects.rs
src/config/matchable.rs
src/config/members.rs
src/config/mod.rs
src/config/parameter_matchable.rs
src/config/parsable.rs
src/config/signals.rs
src/traits.rs

Fixes #291
cc @gkoz @GuillaumeGomez 
Contains config refactoring (splitting `Identables`)

Nullable signal parameters

---

src/parser.rs

Fixes error on loading latest ubuntu gir's
```
thread 'main' panicked at 'src\parser.rs:740 Unexpected element <doc-version> in D:\eap\rust\0\gtk\gir-files\Gdk-3.0.gir:22214:9', src\parser.rs:53
```
On this method:
```xml
<method name="fullscreen_on_monitor"
c:identifier="gdk_window_fullscreen_on_monitor">
<doc xml:space="preserve">Moves the window into fullscreen mode on the given monitor. This means
the window covers the entire screen and is above any panels or task bars.
If the window was already fullscreen, then this function does nothing.</doc>
<doc-version xml:space="preserve">UNRELEASED</doc-version>
<return-value transfer-ownership="none">
<type name="none" c:type="void"/>
</return-value>
<parameters>
<instance-parameter name="window" transfer-ownership="none">
<doc …
```

Fix load latest girs

---

Cargo.lock
Cargo.toml
appveyor.yml
src/config/config.rs
src/config/error.rs
src/main.rs
src/version.rs
tests/sys/sys_build/Cargo.toml

Use [error-chain](https://crates.io/crates/error-chain) crate to handle errors
Before
```
Failed to read config "D:\eap\rust\0\gtk\Gir.toml1": File not found. (os error 2)
```
now
```
Failed to read config "D:\eap\rust\0\gtk\Gir.toml1"
caused by: File not found. (os error 2)
```
Config file name moved to special parent error and children not needed it anymore and just changed to strings.
Before
```
"D:\eap\rust\0\gtk\Gir.toml": No options.girs_dir in config
```
now
```
Error in config "D:\eap\rust\0\gtk\Gir.toml"
caused by: No options.girs_dir
```
cc @GuillaumeGomez, @gkoz 
PS. `error-chain` can collect backtrace of errors, but currently I disabled this.
Enabling feature "backtrace" add 5 more crates

Use error_chain crate to process errors

---

src/analysis/conversion_type.rs
src/analysis/mod.rs
src/analysis/out_parameters.rs
src/analysis/parameter.rs
src/analysis/trampoline_parameters.rs
src/analysis/trampolines.rs
src/codegen/trampoline.rs
src/codegen/trampoline_from_glib.rs
src/codegen/trampoline_to_glib.rs
src/codegen/translate_from_glib.rs
src/codegen/translate_to_glib.rs
src/config/signals.rs

Rework of trampoline parameters by idea in #264.
Added 2 transformation:
- "borrow" for replace `from_glib_none` to `from_glib_borrow`
- "treepath" for adding string to `TreePath` conversion
Currently not adding return values to parameters.
Warning: based on #292 so better merge it first.

Trampolines parameters transformations

---

src/analysis/functions.rs
src/analysis/out_parameters.rs

Closes #306
@antoyo, check this version please.

Apply configured return.nullable to out parameters

---

src/analysis/special_functions.rs

Fixes StyleContext for Gtk 3.20 (https://github.com/gtk-rs/gtk/pull/443#issuecomment-278370871)

Don't implement Display trait for non-standard to_string

---

src/analysis/bounds.rs
src/analysis/functions.rs
src/analysis/parameter.rs
src/analysis/rust_type.rs
src/analysis/trampolines.rs
src/chunk/parameter_ffi_call_in.rs
src/codegen/function.rs
src/codegen/parameter.rs
src/codegen/trampoline.rs
src/codegen/translate_to_glib.rs
src/library.rs

Remains to call `.into()` on the arguments (didn't look yet where I can do it in the code).
cc @EPashkin

Add Into<&str> for optional parameters

---

src/analysis/parameter.rs

Fix for `pango_layout_get_size` and `pango_layout_set_markup_with_accel` that have `caller-allocates="1"` for `int` out parameter

Fix generation out parameter with simply types

---

Cargo.lock
Cargo.toml
src/codegen/doc/format.rs
src/codegen/doc/mod.rs
src/codegen/sys/build.rs
src/codegen/sys/cargo_toml.rs
src/config/child_properties.rs
src/config/config.rs
src/config/error.rs
src/config/functions.rs
src/config/gobjects.rs
src/config/ident.rs
src/config/members.rs
src/config/parsable.rs
src/config/properties.rs
src/config/signals.rs
src/main.rs
src/parser.rs

Updating to new last toml as `rustc-serialize` planed for deprecation https://internals.rust-lang.org/t/rust-release-milestone-predictions/4591
Only last is `docopt` that also planing use serde https://github.com/docopt/docopt.rs/issues/128
PS. There was problem with sys crates https://github.com/alexcrichton/toml-rs/pull/151
PPS. When upgrading found that `regex 0.2.0` don't implement `Eq` so this code fails and upgrade will need other PR later (if any).
```
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum Ident {
Name(String),
Pattern(Regex),
}
```

Update toml, regex and xml-rs version

---

src/analysis/object.rs
src/analysis/properties.rs
src/analysis/signatures.rs

Removes properties when parent or interface has same functions.
Ex. `ColorButton::set_property_rgba` duplicate for `ColorChooser::set_rgba`

Use dependencies when checking for property duplicates

---

src/codegen/enums.rs

Fixed generation unversioned members of `Gdk.EventType` that versioned in https://github.com/gtk-rs/sys/blob/master/gdk-sys/src/lib.rs#L371-L374

Fix generation of versioned enum member

---

src/analysis/signatures.rs
src/parser.rs

Changed parsers functions attribute parameters from `&Vec<>` to `&[]` and renamed getter to remove conflict with `std::slice::SliceIndex`
```
error[E0277]: the trait bound `&str: std::slice::SliceIndex<xml::attribute::OwnedAttribute>` is not satisfied
--> src\parser.rs:131:59
|
131 |                             trace!("class {}", attributes.get("name").unwrap());
|                                                           ^^^ the trait `std::slice::SliceIndex<xml::attribute::OwnedAttribute>` is not implemented for `&str`
|
= note: slice indices are of type `usize` or ranges of `usize`
```

Fix parser atribute parameter and possible conflict with `std::slice::SliceIndex`

---

src/parser.rs

See commit message. While this does not add proper support for unions yet, it at least allows the parser to not fail on Gst-1.0.gir.
Proper union support is blocked by https://github.com/rust-lang/rust/issues/32836

Add support for parsing unions in classes

---

src/analysis/bounds.rs
src/analysis/properties.rs
src/codegen/function.rs
src/codegen/properties.rs

Closes #332 
Example change:
```diff
--- a/src/auto/container.rs
+++ b/src/auto/container.rs
@@ -90,7 +90,7 @@ pub trait ContainerExt {
fn unset_focus_chain(&self);
-    fn set_property_child(&self, child: Option<&Widget>);
+    fn set_property_child<T: IsA<Widget> + IsA<Object>>(&self, child: Option<&T>);
fn connect_add<F: Fn(&Self, &Widget) + 'static>(&self, f: F) -> u64;
```

Generate property setters with IsA

---

src/codegen/sys/lib_.rs

Otherwise we will make them to possibly incorrect Rust types, which do
not exist, and by this we map them to the same types as used inside
structs, function parameters, etc.
Case in question was GStreamer's GST_CLOCK_TIME_NONE which is of type
GstClockTime in C. By using the Rust type this would map to "ClockTime",
which does not exist in the FFI bindings.

Use FFI instead of Rust types for constants too

---

src/codegen/sys/lib_.rs

> This depends (and includes https://github.com/gtk-rs/gir/pull/335 )
In the GIR they are given with an integer value but we have to convert
them to the corresponding bitflags type.

Add support for correctly generating bitflag constants

---

src/codegen/sys/lib_.rs

> This depends on (and includes) https://github.com/gtk-rs/gir/pull/335
This reverts part of 9defa38e7dd18c0818e2560b7534ebb9ea87e068
Reason for this change is that it allows to use the constants directly
for calling C functions without dynamic memory allocations, and still
allows to convert them to a &str without any copying by using CStr.

Create C string constants as *const c_char with trailing \0 instead of &'static str

---

src/codegen/sys/lib_.rs

This is needed for various structs in GStreamer because either
1) it's a private padding field, but the struct has to be declared
as a constant to be useful (GstPluginDesc)
2) it's a semi-private field that in C would be accessed via a macro
This also makes the GValue type field public, and solves the following
FIXME comment: https://github.com/gtk-rs/glib/blob/master/src/value.rs#L144

Mark private struct fields in -sys bindings as public

---

src/analysis/bounds.rs
src/analysis/parameter.rs
src/analysis/return_value.rs
src/analysis/trampolines.rs
src/chunk/parameter_ffi_call_in.rs
src/codegen/function.rs
src/codegen/function_body_chunk.rs
src/codegen/parameter.rs
src/codegen/property_body.rs
src/codegen/signal.rs
src/codegen/trampoline.rs
src/codegen/translate_to_glib.rs
src/consts.rs
src/main.rs

However, I can't make it work because (small subset of errors):
```
error[E0191]: the value of the associated type `Storage` (from the trait `glib::translate::ToGlibPtr`) must be specified
--> src/auto/window.rs:993:49
|
993 |     fn set_transient_for<'a, T: Into<Option<&'a IsA<Window>>>>(&self, parent: T) {
|                                                 ^^^^^^^^^^^ missing associated type `Storage` value
error[E0191]: the value of the associated type `GlibType` (from the trait `glib::wrapper::Wrapper`) must be specified
--> src/auto/window.rs:993:49
|
993 |     fn set_transient_for<'a, T: Into<Option<&'a IsA<Window>>>>(&self, parent: T) {
|                                                 ^^^^^^^^^^^ missing associated type `GlibType` value
```
Apparently, it cannot determine the type …

Add into conversion for every nullable type

---

src/analysis/object.rs
src/analysis/properties.rs
src/analysis/signals.rs
src/codegen/object.rs
src/codegen/properties.rs

In crates like gtk or gstreamer, which have their own GtkObject and
GstObject, this otherwise will result in wrong bounds. Specifically the
one for GObject is missing, which is required for things like properties
and signals.

Fully qualify the glib::object::Object for the IsA<_> constraints

---

src/codegen/alias.rs
src/codegen/mod.rs

These come without any conversion traits implemented as they should be
directly compatible with the versions in the -sys crates.

Add support for generating alias types

---

src/analysis/object.rs
src/codegen/doc/mod.rs
src/codegen/object.rs
src/codegen/record.rs
src/codegen/trait_impls.rs
src/config/gobjects.rs

WIP: The configuration should probably be renamed to allow_no_trait or
similar instead.
Reason for this is that the general case is that subclasses of any
GObject are allowed, and in your own crate you don't generally know if
other crates or any other code is going to create subclasses. Only in
few cases a class is "final" and does not allow subclasses.
@EPashkin Any opinions on this one?

Generate *Ext traits by default and allow disabling them instead

---

README.md
src/analysis/functions.rs
src/analysis/imports.rs
src/analysis/mod.rs
src/analysis/out_parameters.rs
src/analysis/rust_type.rs
src/codegen/alias.rs
src/codegen/functions.rs
src/codegen/mod.rs
src/config/gobjects.rs

https://github.com/gtk-rs/gir/issues/295
All functions are now unconditionally generated unless "ignore=true" for them. None are re-exported automatically and would have to be added to e.g. src/lib.rs for re-exporting from auto::functions::$function_name.
Not sure if this is ideal. Reason for not re-exporting them automatically is that you usually want to group them into useful modules, e.g. in the case of GStreamer all "gst_parse_*" functions would be placed into a gst::parse module.
Any opinions?
Last commit is just some random cleanup that I happened to notice while reading the code again.

Generate functions

---

src/analysis/out_parameters.rs
src/analysis/parameter.rs
src/chunk/chunk.rs
src/chunk/parameter_ffi_call_in.rs
src/chunk/parameter_ffi_call_out.rs
src/codegen/function.rs
src/codegen/function_body_chunk.rs
src/codegen/property_body.rs
src/codegen/return_value.rs
src/codegen/translate_from_glib.rs
src/library.rs
src/parser.rs
src/writer/to_code.rs

https://github.com/gtk-rs/gir/issues/376
Only pointer arrays are currently supported, the translation trait is even called FromGlibPtrContainer. This should be changed really to also be able to handle all kinds of integer (incl. byte) arrays.

Add support for array-length for parameters and return values

---

README.md
src/analysis/info_base.rs
src/analysis/object.rs
src/analysis/record.rs
src/codegen/object.rs
src/codegen/record.rs
src/codegen/signal.rs
src/codegen/trampoline.rs
src/config/config.rs
src/config/gobjects.rs
src/library.rs

This allows configuring crate-wide and per object/record if an object is
supposed to be Send, Sync or Send + Sync. The marker traits will
automatically be implemented and signals callbacks on those objects will
get the appropriate trait bounds.
Note that it is still required to manually ensure that any signal of
parent or child types has at least the same trait bounds.
https://github.com/gtk-rs/gir/issues/379

Implement Send/Sync configuration for objects/records

---

Cargo.toml
README.md
src/analysis/ffi_type.rs
src/codegen/sys/functions.rs
src/codegen/sys/lib_.rs
src/codegen/sys/statics.rs
src/library.rs
src/parser.rs

Unions are fully enabled behind a feature-gate. Both non-nightly and nightly Rust appear to be working well.

Full enablement of Unions using nightly Rust

---

src/codegen/trampoline.rs

https://github.com/rust-lang-nursery/rust-clippy/wiki#borrowed_box

Fix borrowed_box clippy warning in generated trampoline code

---

src/analysis/signals.rs
src/analysis/trampolines.rs
src/codegen/object.rs
src/codegen/signal.rs
src/codegen/trampoline.rs
src/config/gobjects.rs
src/config/signals.rs

When the object is Send+Sync it might still make sense to use Send only
for the signal. This is the case if the signal can be called only from a
single thread at a time.
I need this for GStreamer to make usage together with GTK a bit simpler.

Add configuration for concurrency per signal

---

src/codegen/general.rs
src/codegen/object.rs
src/codegen/record.rs

Fix `Default` implementation for `PlacesSidebar` that have 
```
#[cfg(feature = "v3_10")]
pub fn new() -> PlacesSidebar {
```
cc @sdroege

Generate version conditions for Default implementation

---

src/analysis/object.rs
src/analysis/symbols.rs
src/codegen/doc/mod.rs
src/codegen/object.rs
src/codegen/record.rs
src/codegen/trait_impls.rs
src/config/gobjects.rs
src/config/signals.rs

This is needed in cases where there are multiple types with the same
name in the type hierarchy, e.g. GObject and GstObject or GApplication
and GtkApplication.
See https://github.com/gtk-rs/glib/issues/211

Add configuration for explicitly setting the trait name

---

src/codegen/doc/format.rs
src/codegen/doc/mod.rs

Fix #435 
Also changed generated name to comply with https://github.com/gtk-rs/lgpl-docs names.

Fix generating docs for traits with custom name

---

src/analysis/info_base.rs
src/analysis/object.rs
src/analysis/record.rs

Change bad #444, just make gir use config version if it present
```
[[object]]
name = "GtkSource.Style"
status = "generate"
version = "2.0"
[[object.function]]
name = "copy"
ignore = true
```

Make object version from config a higher priority

---

src/analysis/trampoline_parameters.rs
src/analysis/trampolines.rs

They are valid for the whole scope of the trampoline, obviously, and by
using from_glib_none() and passing them by reference we would in the
best case only do atomic reference counting but in the worst case
actually copy the data just to pass on a reference.

Borrow Boxed/Shared/Object/Interface arguments in signal trampolines

---

src/codegen/sys/build.rs

First commit makes it panic when `shared-library` has a wrong form.
(Thought it'd be helpful to do so instead of generating uncompilable code.)
Second commit combines `Path` with `Regex` to extract the library name, which will support extraction from absolute paths and macOS `.dylib`s as well.
Sorry if I'm misunderstanding the intention of the present code...

Use Path for shared library name extraction

---

src/codegen/flags.rs
src/codegen/sys/cargo_toml.rs
src/codegen/sys/lib_.rs
src/nameutil.rs

This introduces various API changes, most importantly the flags types
work like enums now, e.g. you use SomeFlags::THE_VALUE instead of
THE_VALUE as a constant. For the -sys bindings, SOME_FLAGS_THE_VALUE
will still be exported as an alias (for closer C compatiblity), but the
non-sys bindings use the flags like enums now.
Fixes https://github.com/gtk-rs/gir/issues/468

Update to bitflags 1.0

---

README.md
src/codegen/enums.rs
src/codegen/flags.rs
src/config/gobjects.rs

Useful for error/status types that the user must handle to not ignore
errors.

Allow marking enums and bitflags as #[must_use]

---

src/codegen/enums.rs
src/codegen/sys/lib_.rs

The C code might be extended by additional values without the bindings
being updated, which then is considered undefined behaviour on the Rust
side. As such we must use plain integers here.
The enums stay as enums in the non-sys crates and the conversion traits
ensure that the conversion from the integers to the actual enum values
is done correctly, while storing unknown values in a hidden enum
variant.
Fixes https://github.com/gtk-rs/gir/issues/480

Generate enums in -sys crates as integer constants

---

src/codegen/sys/lib_.rs
src/codegen/sys/statics.rs

Generate Debug for sys types

---

src/analysis/functions.rs
src/nameutil.rs

Had the issue while adding new types to `gio`.
cc @EPashkin

Avoid to generate variable names which are keywords

---

src/chunk/chunk.rs
src/codegen/function_body_chunk.rs
src/writer/to_code.rs

cc @GuillaumeGomez, @sdroege 
Removes warning "unnecessary parentheses around function argument"
which appeared in nightly for gtk and gio.
```diff
--- a/src/auto/icon_info.rs
+++ b/src/auto/icon_info.rs
@@ -214,7 +214,7 @@ impl<O: IsA<IconInfo>> IconInfoExt for O {
let mut error = ptr::null_mut();
let mut was_symbolic = mem::uninitialized();
let _ = ffi::gtk_icon_info_load_symbolic_finish(_source_object as *mut _, res, &mut was_symbolic, &mut error);
-            let result = if error.is_null() { Ok((from_glib(was_symbolic))) } else { Err(from_glib_full(error)) };
+            let result = if error.is_null() { Ok(from_glib(was_symbolic)) } else { Err(from_glib_full(error)) };
let callback: Box<Box<T>> = Box::from_raw(user_data as *mut _);
callback(result);
}
```

Remove unnecessary parentheses in async trampoline result

---

src/codegen/sys/lib_.rs
src/library_postprocessing.rs

Reduce field related logic in code generation phase by moving it to library
postprocessing phase. ~~This PR also includes sockaddr which allows to
successfully generate bindings for Soup (which didn't work correctly
previously).~~
Tested with bindings hosted under gtk-rs in FFI and API mode.

 Fill missing c:type in fields in postprocessing phase.

---

Cargo.toml
README.md
src/codegen/sys/lib_.rs
src/codegen/sys/statics.rs
src/library.rs
src/parser.rs
tests/sys/atk-sys/Cargo.toml
tests/sys/gdk-pixbuf-sys/Cargo.toml
tests/sys/gdk-sys/Cargo.toml
tests/sys/gio-sys/Cargo.toml
tests/sys/glib-sys/Cargo.toml
tests/sys/gobject-sys/Cargo.toml
tests/sys/gtk-sys/Cargo.toml
tests/sys/pango-sys/Cargo.toml
tests/sys/secret-sys/Cargo.toml

Removes all feature-gating of `union`, and now requires rust 1.19
Updates readme to reflect this.

Unions: Remove feature-gate for stable rustc

---

src/codegen/sys/statics.rs

Useful especially in the case of WebKit crates.

Allow non_snake_case to silence warnings in generated code.

---

src/config/error.rs
src/main.rs
src/parser.rs
src/xmlparser.rs

Element
=======
The most basic building block of new API is new Element type,
which wraps StartElement event, and provides following methods:
```rust
pub fn name(&self) -> &str;
pub fn attr(&self, name: &str) -> Option<&str>;
pub fn attr_required(&self, name: &str) -> Result<&str> {
pub fn attr_bool(&self, name: &str, default: bool) -> bool;
pub fn position(&self) -> TextPosition;
...
```
The `elem.name()` is equivalent to old `name.local_name.as_ref()`.
Previously to retrieve an attribute you would write `attr.by_name("name")`.
Now it is `elem.attr("name")`. When attribute is required you can use
`elem.attr_required("name")`. When attribute is absent, appropriate
error message will be generated that includes file name, line number,
column number, element name and attribute name.
Document …

Higher level API for XML parsing.

---

src/codegen/enums.rs
src/codegen/flags.rs

Fix for https://github.com/gtk-rs/glib/pull/290.
It seems we are missing some layer of abstraction, or general consistency in
generated code. I thinking about all checks of the form:  `* == namespaces::MAIN`.
It shouldn't really be necessary.

Fix use declarations when generating code for glib.

---

src/analysis/imports.rs
src/analysis/mod.rs
src/analysis/object.rs
src/analysis/record.rs
src/codegen/enums.rs
src/codegen/flags.rs

* Make Imports aware of current crate and names defined in module.
This move responsibility for special handling of names defined within
the same crate or module inside the Imports struct. Users of Imports
merely declare what they use.
* Use Imports to generate use declarations in enum / flags codegen.

Refactor imports.

---

src/codegen/doc/mod.rs
src/config/config.rs

This reduce the amount of manual tweaking required when
regenerating the doc of the gstreamer bindings, as it is
output in a different path with a different filename.
When the option is not specified, the current behaviour
is preserved.

doc: allow specifying a separate target path

---

src/analysis/bounds.rs
src/analysis/functions.rs
src/analysis/out_parameters.rs
src/codegen/function_body_chunk.rs

return type of the finish() function
Fixes #535 
I've got a WIP patch for Gio here: https://github.com/MathieuDuponchelle/gio/commit/babfd3a287f4050227b681aa45946c4fc95482ac
I also fixed a bug in the same commit, where we would look up the wrong finish function in gio, because we looked it up by rust name, and there were multiple unrelated functions with that name (connect_finish, maybe others). It was a bit awkward to split up, just let me know if you'd rather I split it up!

Add support for async functions that have a non-trivial ..

---

src/analysis/record_type.rs
src/analysis/ref_mode.rs

as only this record type is referenced without `mut`

Prioritize RecordType::Refcounted over other record types

---

src/codegen/sys/build.rs

By default, pkg-config-rs sets the PKG_CONFIG_ALLOW_SYSTEM_LIBS
environment variable
(alexcrichton/pkg-config-rs#35), which leads
to eg /usr/lib being present in the middle of the final command,
in turn leading to issues when working in an uninstalled environment,
where libraries that are also present system-wide do not get linked
against.

codegen/build.rs: disable print_system_libs in calls to pkg-config

---

src/codegen/function_body_chunk.rs
src/codegen/trampoline.rs

This reverts commit a61ccc16be2e0add02ec7b7953f55ee04317cbf5.
Part of https://github.com/gtk-rs/glib/pull/250

Revert "Remove adding callback_guard"

---

src/codegen/doc/mod.rs
src/codegen/sys/build.rs
src/codegen/sys/cargo_toml.rs
src/codegen/sys/lib_.rs

The default log level is warn, thus this change also intentionally hides
those messages by default, avoiding excessive output when generating
code for multiple crates in succession.

Use info instead of println in codegen.

---

src/codegen/sys/cargo_toml.rs
src/codegen/sys/mod.rs
src/codegen/sys/tests.rs

The mechanism of crate renaming that is available for external libraries
unfortunately does not cover the crate currently being generated.
Generated integration tests need to know the crate name to generate
proper extern crate declaration.
Obtain crate name from Cargo.toml file or auto-generate as before when
generating code for the very first time.
Also, support printing const char* in constants ABI test.

 Support libraries with customized crate name when generating tests.

---

src/codegen/sys/tests.rs

Also use constant arrays instead of BTreeMap, now that they are already
ordered. Constant functions are unstable feature, replace calls to
Layout::from_type, with manual construction of Layout struct.

Sort types and constants used in ABI tests by name at generation time.

---

src/codegen/sys/tests.rs

Without this it fails in gstreamer-sys as some of the macros (which are actually mis-detected as constants...) are calling into GLib

Include pkg-config --libs and LDFLAGS in the compiler command-line

---

src/codegen/sys/tests.rs

When feature test macro is explicitly defined, the implicit defaults are no
longer provided. While we don't need any more features than requested, this is
not necessarily true of other libraries which may in fact assume that defaults
will be always available.
Instead of defining _POSIX_C_SOURCE to get appropriate functionality from
printf on MinGW, just define __USE_MINGW_ANSI_STDIO directly.
Also include manual header first so that it can be free to customize macro
definitions, before other headers are processed.

Remove _POSIX_C_SOURCE feature test macro.

---

src/codegen/flags.rs
src/codegen/sys/cargo_toml.rs
src/codegen/sys/lib_.rs
src/codegen/sys/statics.rs
src/update_version.rs

Part of https://github.com/gtk-rs/gir/issues/575
@sdroege Please, check changes in gstreamer, especially in GST_BUFFER_COPY_ALL and other constants based on flags
cc @GuillaumeGomez,, @tmiasko

Uint flags in sys

---

src/analysis/bounds.rs
src/analysis/functions.rs

* Drop requirement that asynchronous functions have to end in `_async`.
D-Bus related functions tend to have `_sync` version instead.
* Include global functions in search for finish function.
* Import modules used by trampolines, glib_ffi for gpointer and
gobject_ffi for GObject.

Generate bindings for global asynchronous functions.

---

src/analysis/bounds.rs
src/analysis/child_properties.rs
src/analysis/functions.rs
src/analysis/imports.rs
src/analysis/object.rs
src/codegen/function.rs
src/codegen/general.rs
src/codegen/object.rs

@EPashkin If you have any suggestions how to make this less ugly, please tell me :)
This depends on https://github.com/gtk-rs/glib/pull/314

Generate futures variants of GIO async functions

---

src/codegen/function.rs

Replace cloned() with to_owned() to handle situations where borrowed
type is different from the owned one. The cloned() method supports only
the case of &T -> T.
Borrow trait is used to perform analogous work in other direction.

Use ToOwned and Borrow traits when generating futures.

---

src/analysis/bounds.rs
src/analysis/conversion_type.rs
src/analysis/function_parameters.rs
src/analysis/functions.rs
src/analysis/mod.rs
src/analysis/out_parameters.rs
src/analysis/override_string_type.rs
src/analysis/ref_mode.rs
src/analysis/return_value.rs
src/analysis/rust_type.rs
src/codegen/function_body_chunk.rs
src/codegen/sys/ffi_type.rs
src/codegen/sys/tests.rs
src/codegen/trampoline_from_glib.rs
src/config/functions.rs
src/config/mod.rs
src/config/string_type.rs
src/library.rs
tests/sys/gir-secret.toml

Part of https://github.com/gtk-rs/gir/issues/592
All works fine, but need last attempt to remove ugly code in src/analysis/out_parameters.rs

WIP: Support string type override

---

src/analysis/bounds.rs
src/analysis/functions.rs
src/lib.rs

also ignoring [last 10 clippy warnings](https://rust-lang-nursery.github.io/rust-clippy/v0.0.200/index.html#write_literal), since after removing "{}", you will need to quote all curly brackets and make code less readable.
cc @GuillaumeGomez, @sdroege, @antoyo 
```
warning: writing a literal with an empty format string
--> src\codegen\enums.rs:216:9
|
216 | /         "        }
217 | |     }
218 | | }
219 | | "
| |_^
|
= help: for further information visit https://rust-lang-nursery.github.io/rust-clippy/v0.0.200/index.html#write_literal
```

Async exctraction

---

src/analysis/functions.rs

Fix error found in https://github.com/gtk-rs/gio/pull/124

Add `use glib;` if class has async method

---

README.md
src/codegen/enums.rs
src/codegen/flags.rs
src/codegen/general.rs
src/config/derives.rs
src/config/gobjects.rs
src/config/mod.rs
src/config/parsable.rs

Allow using API mode TOML config such as:
``` toml
[[object]]
name = "Gst.BufferFlags"
status = "generate"
[[object.derive]]
name = "Serialize, Deserialize"
cfg_condition = "feature = \"ser_de\""
[[object]]
name = "Gst.Format"
status = "generate"
[[object.derive]]
name = "Serialize, Deserialize"
cfg_condition = "feature = \"ser_de\""
```
to generate:
``` rust
bitflags! {
#[cfg_attr(feature = "ser_de", derive(Serialize, Deserialize))]
pub struct BufferFlags: u32 {
const LIVE = 16;
[...]
}
}
```
and
``` rust
#[derive(Clone, Copy, Debug, Eq, PartialEq, Hash)]
#[cfg_attr(feature = "ser_de", derive(Serialize, Deserialize))]
pub enum Format {
Undefined,
[...]
}
```

Enum / Flags: generate user defined `derive`

---

src/analysis/functions.rs
src/analysis/ref_mode.rs
src/config/gobjects.rs
src/library.rs
src/version.rs

See https://rust-lang-nursery.github.io/rust-clippy/v0.0.209/index.html#trivially_copy_pass_by_ref

Fix clippy warnings about passing short and Copy arguments by reference

---

src/codegen/function_body_chunk.rs
src/codegen/trampoline.rs

Stable rust v1.27.0 landed, so I start removing callback guard
Part of https://github.com/gtk-rs/glib/pull/250 and https://github.com/gtk-rs/glib/issues/304
Previous attempt:  https://github.com/gtk-rs/gir/pull/547

Remove adding callback_guard

---

src/codegen/sys/ffi_type.rs

Part of https://github.com/gtk-rs/gio/pull/131
cc @sdroege

Fix generating array with c:type="gpointer*" and other actual type

---

src/codegen/signal.rs

Fix panic on GObject generation (see https://github.com/gtk-rs/gir/pull/620#issue-199102491).
cc @sdroege

Fix panic in generating `emit` for incomplete signal

---

src/analysis/function_parameters.rs
src/analysis/functions.rs
src/analysis/object.rs
src/analysis/record.rs
src/analysis/special_functions.rs
src/codegen/enums.rs
src/codegen/flags.rs
src/codegen/general.rs
src/codegen/record.rs
src/codegen/trait_impls.rs
src/codegen/translate_to_glib.rs
src/config/derives.rs
src/config/gobjects.rs

See https://github.com/gtk-rs/glib/pull/367 for context
This is WIP

Improve deriving of trait impls

---

src/library.rs

That should be the last commit for this serie. Just realised that the first letter of the namespace wasn't capitalised for parents.

Get real parent name

---

src/library.rs

I completely failed my previous PR (only tested it on sourceview, shame on me...). However I still have an issue: some types have a `ns_id` equal to 0. Therefore, the filtering is failing because the full name doesn't match (`*` instead of `Gtk` for example). For example we have this issue for:
```
Gtk.TextIter::get_marks because of *.TextMark
```
Any idea @EPashkin?

Fix not bound functions and methods filtering

---

Cargo.lock
Cargo.toml
README.md
src/analysis/properties.rs
src/config/mod.rs
src/config/properties.rs
src/config/property_generate_flags.rs
src/lib.rs

Part of #639 and #510
cc @GuillaumeGomez, @sdroege 
IMHO needed other name instead "object.property.generate", maybe for `PropertyGenerateFlags` too.
WIP as I don't like current parser implementation and try to rework it.

Partial properties generation

---

src/analysis/properties.rs

Part of #510 
cc @GuillaumeGomez , @sdroege 
Affected crates glib, gtk, gio, gdk, gdk-pixbuf, sourceview

Don't generare notify for ConstructOnly properties

---

src/codegen/enums.rs
src/codegen/flags.rs
src/codegen/sys/lib_.rs
src/nameutil.rs

Fix #600
@ceyusa can you test it?
cc @GuillaumeGomez, @sdroege, @russel

Add underscore to enum and bitflags member starting with digits

---

src/analysis/bounds.rs
src/codegen/properties.rs

This code is currently a huge mess and generate stuff like:
```
fn set_property_cell_background<'a, P: Into<Option<&'a Option<&str>>>>(&self, cell_background: P) {
```
Which is pretty funny but not what I want. So my main question is:
Why does it generate two `Option` wrapping instead of one? (I assume the `Into` wrapping generates one over a type which already has one)
A bit of help would be very appreciated here (I think I did it completely wrong). :)
Once this part done, I'll just have to generate the `.into` call and we'll be good to go I think.

Into wrapping

---

README.md
src/codegen/sys/cargo_toml.rs
src/codegen/sys/fields.rs
src/codegen/sys/functions.rs
src/codegen/sys/lib_.rs

Generate cfg_condition on sys mode

---

src/codegen/sys/fields.rs

Since GObject class structures are records from GIR perspective.
I just forgot to add this too :disappointed:

sys: generate cfg_condition for records

---

src/analysis/conversion_type.rs
src/analysis/ffi_type.rs
src/analysis/types.rs
src/codegen/sys/ffi_type.rs
src/library.rs
src/parser.rs

Part of #648, #652
Only change sys generation
@alatiera please check this version on gstreamer-sys

Use inner c:type for arrays with fixed size in sys mode

---

src/codegen/sys/tests.rs

Otherwise tests will fail if the constants start/end with whitespace.
Fixes https://github.com/gtk-rs/gir/issues/644

Don't trim constants themselves when testing for their value

---

src/analysis/object.rs
src/codegen/general.rs
src/codegen/object.rs
src/config/gobjects.rs

This passes the Rust class struct to glib_wrapper! if configured to do
so but still requires it to be manually implemented for the time being.
See https://github.com/gtk-rs/glib/pull/392

Implement basics for subclassing

---

src/analysis/functions.rs
src/analysis/object.rs
src/analysis/out_parameters.rs
src/analysis/record.rs

See https://github.com/gtk-rs/glib/pull/398
This is not complete. There's still the `std::ptr` added from `src/analysis/out_parameters.rs:analyze_imports()`. It seems like the condition there is wrong but I don't know what it should be. It seems to be related to `src/codegen/function_body_chunk.rs:c_type_mem_mode_lib()`.
@EPashkin any ideas?

Remove now unneeded use statements for the glib_wrapper! macro

---

src/analysis/functions.rs
src/analysis/object.rs
src/analysis/properties.rs
src/analysis/signals.rs
src/codegen/function.rs
src/codegen/object.rs
src/codegen/property_body.rs
src/codegen/signal.rs
src/writer/to_code.rs

Closes https://github.com/gtk-rs/gir/issues/670

WIP: Don't generate any but the main IsA<_> bound for extension traits

---

src/analysis/properties.rs
src/analysis/signals.rs
src/codegen/child_properties.rs
src/codegen/object.rs
src/codegen/properties.rs
src/codegen/property_body.rs
src/config/config.rs
src/config/gobjects.rs
src/writer/to_code.rs

commit bcfdfe6584cb9d934eb22ac150889a7d8b1c9924 (HEAD -> raw-strings)
Author: Sebastian Dröge <sebastian@centricular.com>
Date:   Sat Dec 8 10:58:23 2018 +0200
Also generate display trait for shorthand types only if the global default says so
commit 6178a527b14e9f226db2b7f7758e23bf3cdc3488
Author: Sebastian Dröge <sebastian@centricular.com>
Date:   Sat Dec 8 10:48:03 2018 +0200
Only insert casts in property getters/setters if we're generating them for a trait
Otherwise compilation fails because type annotations would be needed.
commit 83a8280c1b9cbdedee5cc57323ca1f424f94383f
Author: Sebastian Dröge <sebastian@centricular.com>
Date:   Sat Dec 8 10:33:38 2018 +0200
Use raw 0-terminated strings for connecting to signals and accessing properties
Going through `s.to_glib_none().0` involves …

Various minor fixes

---

src/analysis/properties.rs
src/codegen/properties.rs

And remove unneeded IsA<Object> bound from them
----
See https://github.com/gtk-rs/gir/pull/673#issuecomment-445453829
I'll get rid of the other unneeded bounds at a later time

Add missing "glib" use statement for property setters

---

src/analysis/child_properties.rs
src/analysis/functions.rs
src/analysis/properties.rs
src/analysis/return_value.rs
src/analysis/rust_type.rs
src/analysis/supertypes.rs
src/analysis/trampoline_parameters.rs
src/analysis/trampolines.rs
src/codegen/function.rs
src/codegen/property_body.rs
src/codegen/return_value.rs
src/codegen/trampoline.rs

Generated code relying on CStringHolder should be more efficient because it
reduces the amount of string copies.

Generate code using CStringHolder instead of String

---

src/analysis/types.rs
src/codegen/sys/fields.rs

When bit field is not preceded by another bit field, generate the field
as if didn't specify bit width.
From Sys V ABI perspective two most important things about bit fields
are that they occupy storage unit appropriate for their declared type,
and that they might share it with other struct / union members.
When there are no other bit fields they could share storage with
they are laid out like fields without bit width specification.
Use this observation to generate definitions for additional types.

They weren't meant to be bit fields

---

src/codegen/sys/lib_.rs

The special case generates unqualified name in Rust, which crates
mismatch with version in C, since it is not present there.
Differences in sys codegen:
```diff
diff --git a/gdk-pixbuf-sys/src/lib.rs b/gdk-pixbuf-sys/src/lib.rs
index 1f814d8..45fc764 100644
--- a/gdk-pixbuf-sys/src/lib.rs
+++ b/gdk-pixbuf-sys/src/lib.rs
@@ -19,9 +19,8 @@ use libc::{c_int, c_char, c_uchar, c_float, c_uint, c_double,
use glib::{gboolean, gconstpointer, gpointer, GType};
// Enums
-pub type Colorspace = c_int;
-pub const GDK_COLORSPACE_RGB: Colorspace = 0;
-pub type GdkColorspace = Colorspace;
+pub type GdkColorspace = c_int;
+pub const GDK_COLORSPACE_RGB: GdkColorspace = 0;
pub type GdkInterpType = c_int;
pub const GDK_INTERP_NEAREST: GdkInterpType = 0;
diff --git a/gio-sys/src/lib.rs b/gio-sys/src/lib.rs …
```

Remove special generation for enums with a single member

---

.travis.yml
src/analysis/bounds.rs
src/analysis/function_parameters.rs
src/analysis/functions.rs
src/analysis/record.rs
src/analysis/signatures.rs
src/analysis/types.rs
src/chunk/mod.rs
src/codegen/doc/mod.rs
src/codegen/function_body_chunk.rs
src/codegen/property_body.rs
src/codegen/signal.rs
src/codegen/sys/fields.rs
src/codegen/sys/functions.rs
src/codegen/sys/lib_.rs
src/codegen/sys/statics.rs
src/config/mod.rs
src/lib.rs
src/library.rs
src/main.rs

also add clippy check in travis

Fix some clippy warnings

---

src/codegen/translate_from_glib.rs

See https://github.com/gtk-rs/glib/pull/419

Codegen: use new glib macro for BoolError

---

src/analysis/ffi_type.rs

When generating glib, I had a "little" issue because of this one.
cc @EPashkin

Fix invalid gboolean generation

---

src/library_postprocessing.rs

If there's a subtype we don't consider it a final type too. The class
struct might be private but inside the library there might be subtypes.
Subtypes in other libraries are nonetheless not possible if the class
struct is private.
----
I forgot to add that back yesterday. I don't think this changes any generated code except for `gstreamer-pbutils`

Check for known subtypes when deciding if a type is a final type

---

src/codegen/function_body_chunk.rs

Gir sometimes swap boxes for gio's `g_vfs_unregister_uri_scheme`
```diff
--- a/src/auto/vfs.rs
+++ b/src/auto/vfs.rs
@@ -121,8 +121,8 @@ impl<O: IsA<Vfs>> VfsExt for O {
let _callback: Box_<Option<P>> = Box_::from_raw(data as *mut _);
}
let destroy_call7 = Some(parse_name_destroy_func::<P, R> as _);
+        let super_callback1: Box_<Option<R>> = parse_name_func_data;
let super_callback0: Box_<Option<P>> = uri_func_data;
-        let super_callback1: Box_<Option<R>> = parse_name_func_data;
unsafe {
```

Fix unstable super_calback's list for g_vfs_register_uri_scheme

---

src/analysis/rust_type.rs
src/codegen/function_body_chunk.rs
src/library.rs

handle aliases better

---

src/library.rs
src/library_postprocessing.rs

Remove references from TypeId usage

---

src/analysis/functions.rs
src/analysis/out_parameters.rs

Fix #693 
@vhdirk Please check results, no `use std::mem` deletion for now
@GuillaumeGomez There no changes in gtk-rs

Add imports for async out parameters

---

README.md
src/codegen/doc/mod.rs
src/config/gobjects.rs

Part of https://github.com/gtk-rs/gir/issues/683
currently only support traits from current crate
and don't use parents manual traits at all (so it need be added manually)

Add manual traits

---

src/analysis/functions.rs
src/analysis/rust_type.rs
src/analysis/trampolines.rs
src/codegen/function_body_chunk.rs

Fixes #704.
This currently fixes two things:
* Remove the invalid indirection (`Box::<Option<X>>.as_ptr()` -> `&Box<Option<X>>` is not longer a thing)
* Added the missing `Option` <s>(yep, everything is an `Option` by default)</s> (it's now correctly handled everywhere)
* No more `GString` parameters: they're replaced with `&str` now
* Fix invalid Send/Sync bounds (by default, I was giving both of them :p)
* Fix invalid nullable "status" from destroy callbacks.
I intend to fix the other issues on this PR as well so please don't merge! :)

Few improvements on user callback generation

---

src/chunk/chunk.rs
src/codegen/function_body_chunk.rs
src/codegen/signal.rs
src/codegen/signal_body.rs
src/codegen/trampoline.rs
src/writer/to_code.rs

See the individual commits for explanations.
Needs some manual code updated too, which I'll do after the regens are all through.

Create fewer boxes for closures

---

src/analysis/trampoline_parameters.rs
src/codegen/function_body_chunk.rs

Want some more user-callbacks?

---

src/analysis/bounds.rs
src/analysis/child_properties.rs
src/analysis/function_parameters.rs
src/analysis/functions.rs
src/analysis/out_parameters.rs
src/analysis/return_value.rs
src/analysis/rust_type.rs
src/analysis/trampolines.rs
src/codegen/child_properties.rs
src/codegen/function.rs
src/codegen/function_body_chunk.rs
src/codegen/parameter.rs
src/codegen/properties.rs
src/codegen/return_value.rs
src/codegen/trampoline.rs

Remove into bound for user callbacks

---

src/codegen/trampoline.rs

Don't use transmute() for signal trampoline closures

---

src/analysis/bounds.rs
src/analysis/child_properties.rs
src/analysis/function_parameters.rs
src/analysis/properties.rs
src/codegen/child_properties.rs
src/codegen/function.rs
src/codegen/function_body_chunk.rs
src/codegen/parameter.rs
src/codegen/properties.rs
src/codegen/property_body.rs
src/codegen/trampoline.rs
src/codegen/translate_to_glib.rs

Fixes #722 
It doesn't fix the whole `None::<Whatever>` issue but I guess it's a first step? The goal here being to go back to more explicit code.

Remove Into trait generation

---

README.md
src/analysis/return_value.rs
src/config/functions.rs
src/config/signals.rs

Allow to overwrite returned type

---

.travis.yml
src/analysis/ffi_type.rs
src/codegen/doc/mod.rs
src/codegen/function_body_chunk.rs
src/codegen/sys/cargo_toml.rs
src/codegen/sys/mod.rs
src/nameutil.rs

Fix #731
No changes in current gtk-rs

Recheck crate names usage

---

src/codegen/sys/lib_.rs
src/config/gobjects.rs

[ffi] Support alignment on objects

---

src/analysis/ffi_type.rs
src/analysis/functions.rs
src/analysis/mod.rs
src/analysis/namespaces.rs
src/analysis/object.rs
src/analysis/properties.rs
src/analysis/record.rs
src/analysis/ref_mode.rs
src/analysis/signals.rs
src/chunk/mod.rs
src/codegen/constants.rs
src/codegen/enums.rs
src/codegen/flags.rs
src/codegen/function.rs
src/codegen/function_body_chunk.rs
src/codegen/general.rs
src/codegen/property_body.rs
src/codegen/record.rs
src/codegen/signal.rs
src/codegen/trampoline.rs
src/config/functions.rs
src/config/work_mode.rs
src/env.rs
src/nameutil.rs
src/writer/to_code.rs

Part of https://github.com/gtk-rs/gir/issues/685

Don't use "ffi" suffix for sys crates

---

src/analysis/rust_type.rs
src/codegen/function_body_chunk.rs

Fixes #741.
You can see the result here: https://github.com/gtk-rs/gtk/pull/798

Handle nullable parameters for callbacks as well

---

README.md
src/config/config.rs
src/nameutil.rs

web_kit2_sys and web_kit2_web_extension_sys looks ugly

Add crate name fix for webkit2xx

---

src/codegen/function_body_chunk.rs

Part of https://github.com/gtk-rs/gdk/issues/287
changes only in gdk:
```diff
--- a/src/auto/seat.rs
+++ b/src/auto/seat.rs
@@ -91,7 +91,7 @@ impl Seat {
panic!("cannot get closure...")
};
}
-        let prepare_func = Some(prepare_func_func::<P> as _);
+        let prepare_func = if prepare_func_data.is_some() { Some(prepare_func_func::<P> as _) } else { None };
let super_callback0: &Option<&mut dyn (FnMut(&Seat, &Window))> = &prepare_func_data;
unsafe {
from_glib(gdk_sys::gdk_seat_grab(self.to_glib_none().0, window.as_ref().to_glib_none().0, capabilities.to_glib(), owner_events.to_glib(), cursor.to_glib_none().0, event.to_glib_none().0, prepare_func, super_callback0 as *const _ as usize as *mut _))
```
```diff
--- a/src/auto/window.rs
+++ b/src/auto/window.rs
@@ -908,7 +908,7 @@ impl<O: …
```

Allow nullable trampolines with scope="call"

---

src/parser.rs

G-i now generates a source-position element, but for our
purposes we don't need it yet.
This allows us to generate bindings for libraries that
include it, closing https://github.com/gtk-rs/gir/issues/748

parser: ignore source-position

---

src/codegen/sys/cargo_toml.rs
src/nameutil.rs

Force replacing '-' in crate name for `use`

---

src/library_postprocessing.rs

As of https://gitlab.gnome.org/GNOME/gobject-introspection/commit/1f0965e379035be51ae96d5761358ec088fb3421,
fixed-size arrays are no longer generated with c:type, thus
we should not expect it of them.
Fixes https://github.com/gtk-rs/gir/issues/749

library_postprocessing: Don't expect c:type for FixedArray

---

src/analysis/functions.rs
src/codegen/function.rs

While this requires nightly, the API is now stabilized and will become part of Rust 1.36. IMHO we should merge this now so that it can all get wider testing.

Port to futures 0.3

---

Cargo.lock
Cargo.toml
src/codegen/sys/cargo_toml.rs

Generated `Cargo.toml` now looks like this (for sourceview-sys):
```toml
[package]
name = "gtk-source-sys"
version = "0.0.1"
links = "gtk_source"
build = "build.rs"
[lib]
name = "gtk_source_sys"
[dependencies]
libc = "0.2"
[dependencies.cairo-sys]
git = "https://github.com/gtk-rs/sys"
[dependencies.gdk-sys]
git = "https://github.com/gtk-rs/sys"
[dependencies.gdk_pixbuf-sys]
git = "https://github.com/gtk-rs/sys"
[dependencies.gio-sys]
git = "https://github.com/gtk-rs/sys"
[dependencies.glib-sys]
git = "https://github.com/gtk-rs/sys"
[dependencies.gobject-sys]
git = "https://github.com/gtk-rs/sys"
[dependencies.gtk-sys]
git = "https://github.com/gtk-rs/sys"
[build-dependencies]
pkg-config = "0.3.7"
[dev-dependencies]
shell-words = "0.1.0"
tempdir = "0.3"
[features]
v2_0 = []
v2_2 = ["v2_0"] …
```

Update sys cargo

---

.gitignore
src/analysis/rust_type.rs
src/codegen/function_body_chunk.rs

Fixes #758.
cc @EPashkin @sdroege @elmarco

Fix callbacks

---

README.md
src/analysis/object.rs
src/analysis/properties.rs
src/codegen/object.rs
src/codegen/properties.rs
src/config/gobjects.rs

The usage of the generated code looks like:
```rust
let button = LockButtonBuilder::new()
.text_lock("Verrouiller")
.text_unlock("Déverrouiller")
.build();
```
This creates a `gtk::LockButton` and set the properties `text_lock` and `text_unlock` at the widget construction.
The generated code looks like:
```rust
#[cfg(any(feature = "builders", feature = "dox"))]
pub struct LockButtonBuilder {
#[cfg(any(feature = "v3_14", feature = "dox"))]
text_lock: Option<String>,
#[cfg(any(feature = "v3_14", feature = "dox"))]
text_unlock: Option<String>,
// ...
}
#[cfg(any(feature = "builders", feature = "dox"))]
impl LockButtonBuilder {
pub fn new() -> Self {
Self {
#[cfg(any(feature = "v3_14", feature = "dox"))]
text_lock: None,
#[cfg(any(feature = "v3_14", feature = "dox"))]
text_unlock: None, …
```

Generate builder for widgets

---

src/codegen/sys/tests.rs
src/library_postprocessing.rs
src/parser.rs

Part of https://github.com/gtk-rs/gir/issues/760
Removes traits from more types
Instead `klass.c_class_type` is `klass.type_struct` now used because it allow to get type from library.

Use disguised in final types check

---

src/analysis/class_builder.rs
src/analysis/mod.rs
src/analysis/object.rs
src/analysis/properties.rs
src/case.rs
src/codegen/object.rs
src/config/gobjects.rs

Part of #763
Makes minor fixes after #757
cc @antoyo

Fix builders

---

src/parser.rs

It is added by newer versions of gobject-introspection in various
places.

Ignore the <attribute> element in any other XML element

---

src/codegen/function_body_chunk.rs

`gpointer` mismatches with callback return type generated [here](https://github.com/gtk-rs/gir/blob/4618ddbc20ce0dd7799832faa9d5a961b1be4075/src/codegen/sys/functions.rs#L265).
Example: [GtkMapListModelMapFunc](https://developer.gnome.org/gtk4/unstable/gtk4-GtkMapListModel.html#GtkMapListModelMapFunc) in gtk4.
cc @GuillaumeGomez @sdroege

Use complete pointer type for trampoline return

---

README.md
src/analysis/class_builder.rs
src/case.rs
src/codegen/object.rs
src/config/config.rs
src/config/gobjects.rs

Close #763
Makes minor fixes after #757, #764
```diff
+++ b/src/auto/about_dialog.rs
@@ -505,8 +505,8 @@ impl AboutDialogBuilder {
self
}
-    pub fn logo(mut self, logo: gdk_pixbuf::Pixbuf) -> Self {
-        self.logo = Some(logo);
+    pub fn logo(mut self, logo: &gdk_pixbuf::Pixbuf) -> Self {
+        self.logo = Some(logo.clone());
self
}
```
Only changes classes parameters, vector functions remain unchanged
```rust
pub fn artists(mut self, artists: Vec<String>) -> Self {
self.artists = Some(artists);
self
}
```
cc @GuillaumeGomez , @sdroege , @antoyo

Builder setters accept references

---

src/analysis/imports.rs

Fix imports handling

---

src/analysis/rust_type.rs
src/codegen/function_body_chunk.rs
src/codegen/trampoline.rs
src/codegen/trampoline_from_glib.rs

See https://github.com/gtk-rs/gir/issues/777
Next step is to do the same for callbacks passed to functions. That apparently does not even use the same machinery to find the correct type mappings between Rust and FFI types.
@GuillaumeGomez Any hint where to look and why you didn't use the `trampoline_from_glib` function?

Use Option<&T> instead of &Option<T> for signal callback parameters

---

src/codegen/function.rs

Fixes #789.
As far as I can tell, only gtk is impacted (in `src/auto/icon_info.rs`).

Fix trait object warning for futures

---

src/analysis/bounds.rs

Fixes #783.
Now the new "issue" is:
```
libgir::analysis::functions] measure_disk_usage_async: Cannot handle callbacks and async parameters at the same time for the moment
```
🤣 

Fix missing callback parameter handling

---

src/analysis/functions.rs
src/analysis/object.rs
src/analysis/properties.rs
src/analysis/signals.rs
src/analysis/trampolines.rs
src/codegen/object.rs
src/codegen/signal.rs
src/codegen/trampoline.rs

Fixes #664.
You can check the generated code [here](https://github.com/gtk-rs/gtk/pull/824).

Generate trampolines directly inside functions

---

README.md
src/analysis/record.rs
src/codegen/general.rs
src/codegen/record.rs
src/config/gobjects.rs

Fixes https://github.com/gtk-rs/glib/issues/469

Add configuration for init/clear function expressions of boxed types

---

README.md
src/codegen/doc/mod.rs
src/config/functions.rs
src/config/properties.rs
src/config/signals.rs

Fix https://github.com/gtk-rs/gir/issues/797
@GuillaumeGomez, not sure that it right way, but it works
test for gio:
```diff
+++ b/Gir.toml
@@ -664,11 +664,13 @@ manual_traits = ["SocketListenerExtManual"]
name = "accept_socket_async"
ignore = true
+    doc_trait_name = "SocketListenerExtManual"
[[object.function]]
name = "accept_async"
ignore = true
+    doc_trait_name = "SocketListenerExtManual"
[[object]]
name = "Gio.Subprocess"
```

Add overriding for function trait for manual implemented functions

---

src/library.rs
src/parser.rs

Fix #803 
@GuillaumeGomez seems that in doc mode aliases are not processed at all

Parse "doc-deprecated" tag in alias

---

src/chunk/chunk.rs
src/chunk/conversion_from_glib.rs
src/chunk/parameter_ffi_call_out.rs
src/codegen/function_body_chunk.rs
src/codegen/translate_from_glib.rs
src/writer/to_code.rs

Use new mem::uninitialized API

---

src/codegen/function_body_chunk.rs

Fixes #813.
Can you check it @Boiethios please?

Prevent invalid function parameter order on async callback by not enforcing it

---

src/analysis/function_parameters.rs
src/codegen/function_body_chunk.rs

Handle glib::Pid conversions specifically

---

src/codegen/sys/build.rs
src/codegen/sys/cargo_toml.rs
src/config/config.rs

Fixes https://github.com/gtk-rs/gir/issues/818.
I'm pretty sure I'm forgetting something here though... Well it's late, I'll see that tomorrow...

Handle doc generation for docs.rs

---

src/codegen/property_body.rs
src/codegen/signal.rs

... in consequence of https://github.com/gtk-rs/glib/pull/513

Migrate property getters to new signature for `Value::get`

---

Cargo.lock
Cargo.toml
src/analysis/bounds.rs
src/analysis/child_properties.rs
src/analysis/class_builder.rs
src/analysis/functions.rs
src/analysis/imports.rs
src/analysis/mod.rs
src/analysis/object.rs
src/analysis/out_parameters.rs
src/analysis/properties.rs
src/analysis/record.rs
src/analysis/return_value.rs
src/analysis/rust_type.rs
src/analysis/signals.rs
src/analysis/special_functions.rs
src/analysis/supertypes.rs
src/analysis/trampolines.rs
src/codegen/constants.rs
src/codegen/enums.rs
src/codegen/flags.rs
src/codegen/function.rs
src/codegen/function_body_chunk.rs
src/codegen/general.rs
src/codegen/signal.rs
src/codegen/sys/cargo_toml.rs
src/codegen/trampoline_from_glib.rs
src/codegen/translate_to_glib.rs
src/lib.rs
src/main.rs

Part of https://github.com/gtk-rs/gir/issues/807

Refactor Imports

---

src/parser.rs

Fix #835
@mmstick Does this fix issue?
cc  @GuillaumeGomez , @sdroege

Fall back for "type-name" for objects

---

src/analysis/bounds.rs
src/analysis/class_builder.rs
src/analysis/properties.rs
src/codegen/general.rs
src/codegen/properties.rs
src/library.rs
src/nameutil.rs

Part of https://github.com/gtk-rs/gir/issues/827

Use IsA for property setters for non-final objects

---

src/analysis/bounds.rs
src/analysis/class_builder.rs
src/analysis/rust_type.rs

Hi guys, I just started learning the code and I found some duplicate clone calls.
Maybe this pr can help

Remove some duplicate clone calls

---

src/analysis/bounds.rs
src/analysis/class_builder.rs
src/analysis/properties.rs
src/codegen/object.rs
src/codegen/sys/build.rs

[Example of new code generation.](https://github.com/gtk-rs/gtk/pull/902/files#diff-b636ac4109f36a9dcd7198cf7ed90654L548)

Add generic parameters to builder methods

---

src/analysis/bounds.rs
src/analysis/functions.rs
src/codegen/function_body_chunk.rs

An example of generation: https://github.com/gtk-rs/gio/pull/230
Note that the gio PR needs https://github.com/gtk-rs/gir/issues/815

Allow nullable callbacks

---

src/analysis/functions.rs

Fixes https://github.com/gtk-rs/gtk/issues/872
Fixes https://github.com/gtk-rs/gir/issues/735

Fix invalid import add

---

.travis.yml
Cargo.lock
Cargo.toml
build.rs
src/config/config.rs
src/git.rs
src/main.rs

I'll update this text with the compilation time for every change.
It turns out `git2-sys` is very slow to compile (+1 minute).
Maybe we can re-enable the features of `env_logger` since it does not help much.
Clean build: 4m 15s
Rebuild:     1m 30s
Clean build: 2m 26s
Rebuild:     1m 20s
Clean build: 2m 23s
Rebuild:     1m 18s
Clean build: 2m 11s
Rebuild:     1m 17s
Clean build: 1m 28s
Rebuild:     55.24s

Remove dependencies

---

src/analysis/ffi_type.rs
src/analysis/functions.rs
src/analysis/mod.rs
src/analysis/trampoline_parameters.rs

Fixes #856.
Waiting for @Ekleog to confirm it works in his case.

Extend gpointer to void*

---

src/analysis/bounds.rs
src/analysis/imports.rs
src/analysis/rust_type.rs
src/codegen/return_value.rs

Fixes #862.
cc @EPashkin @sdroege @Ekleog

Correctly generate glib::Error import

---

Cargo.lock
src/analysis/trampolines.rs
src/codegen/trampoline.rs

Otherwise glib::signal::Inhibit needs to be re-exported from the crate root.
CC @EPashkin

Provide the full path to the Inhibit type for signals

---

src/parser.rs

Ignore function-macro tag to prevent warnings

---

src/analysis/functions.rs
src/codegen/function.rs

@GuillaumeGomez This depends on https://github.com/gtk-rs/glib/pull/531
When regenerating, all other crates need their `futures` feature removed and the dependency on the `futures` crate

Generate pinned box futures and use the stabilized futures

---

src/codegen/sys/cargo_toml.rs
src/codegen/sys/tests.rs

The `tempdir` crate was deprecated by its authors, and `tempfile` is
recommended as a replacement.
I assume this is the first time that a dependency needs to be removed
from `Cargo.toml` files, because I found no functionality to remove the
entry. I created an `unset` function analogous to the `set_string`
function found in the `cargo_toml.rs` file.
Rationale: I do packaging work for rust crates in Debian, and due to
it's deprecation, we decided to not package the `tempdir` crate at all,
but to submit patches to the projects that still use it instead.

Migrate to `tempfile` from deprecated `temdir`

---

src/xmlparser.rs

[TextPosition](https://docs.rs/xml-rs/0.8.0/xml/common/struct.TextPosition.html) starts [counting line numbers at 0](https://docs.rs/xml-rs/0.8.0/xml/common/struct.TextPosition.html#structfield.row). There is a ready made [implementation](https://docs.rs/xml-rs/0.8.0/src/xml/common.rs.html#51-53) of `fmt::Display` that accounts for this when showing a TextPosition to a human.
Using this implementation instead of manually showing the zero-indexed line number fixes an off by one error, that the line numbers displayed by the ErrorEmitter are currently having.

Fix off-by-one line numbers in xmlparser::ErrorEmitter

---

README.md
src/analysis/functions.rs
src/analysis/return_value.rs
src/analysis/trampolines.rs
src/chunk/chunk.rs
src/codegen/property_body.rs
src/codegen/return_value.rs
src/codegen/translate_from_glib.rs
src/config/functions.rs

This allows converting an Option<T> into an Result<T, glib::BoolError>,
which in case of Option signalling error allows for more ergonomic error
handling code.
----
CC @EPashkin @GuillaumeGomez

Add new nullable_return_is_error configuration for return types

---

src/analysis/bounds.rs
src/analysis/functions.rs
src/codegen/function_body_chunk.rs

Fix #872 
```rust
fn get_data<P: IsA<gio::Cancellable>, Q: FnOnce(Result<Vec<u8>, glib::Error>) + Send + 'static>(&self, cancellable: Option<&P>, callback: Q) {
let user_data: Box_<Q> = Box_::new(callback);
unsafe extern "C" fn get_data_trampoline<Q: FnOnce(Result<Vec<u8>, glib::Error>) + Send + 'static>(_source_object: *mut gobject_sys::GObject, res: *mut gio_sys::GAsyncResult, user_data: glib_sys::gpointer) {
let mut error = ptr::null_mut();
let mut length = mem::MaybeUninit::uninit();
let ret = webkit2_sys::webkit_web_resource_get_data_finish(_source_object as *mut _, res, length.as_mut_ptr(), &mut error);
let result = if error.is_null() { Ok(FromGlibContainer::from_glib_full_num(ret, length.assume_init() as usize)) } else { Err(from_glib_full(error)) };
let callback: Box_<Q> = …
```

Fix returning array from async trampolines

---

src/analysis/conversion_type.rs
src/analysis/ref_mode.rs
src/analysis/rust_type.rs
src/codegen/translate_from_glib.rs

This is the consecutive PR after including the PtrArray support in glib. Tested with latest NetworkManager introspection definitions.
Related to https://github.com/gtk-rs/glib/pull/559

Add support for PtrArray

---

README.md
src/analysis/bounds.rs
src/analysis/functions.rs
src/analysis/out_parameters.rs
src/config/functions.rs

This PR allows the configuration file to override `use-return-for-result` per function. There are many functions in practice that return a `boolean` or `guint` where the return value is a real value and doesn't just indicate if an error occurred.
You could argue that libraries shouldn't do that, or that the GIR format should allow a tag to distinguish this. However, I think we also have to be able to deal with the current situation, and I figured this is the most logical work-around.
Feedback welcome :)

Allow to override use-return-for-result in function configuration.

---

src/main.rs
src/parser.rs

The first commit is in order to provide a way to check gir files for GNOME so they don't have to wait for us to report bugs. Once this PR is merged, I'll create a Dockerfile and send it to https://gitlab.gnome.org/GNOME/gtk/tree/master/.gitlab-ci/
The second commit is "funnier": when testing the option, I decided to use the dl.sh script to get the latest (and buggy) gir files for gtk4. And when I ran it (expecting a failure), I got:
```
Can't open file "../gir-files/Gsk-4.0.gir": Too many open files (os error 24)
```
After a little search, and a nice run using strace:
```bash
strace -e trace=open,close,read,write,connect,accept ./target/release/gir --check-gir-file ../gir-files/Gtk-4.0.gir
```
I discovered that gir was opening thousands of file. At this point, it seemed pretty obvious …

Check gir file

---

src/git.rs

Command::output() succeeds as long as the command was actually called.
It's up to the user to check if the command was properly executed or
not.
Fix returning Some("") instead of None when calling repo_hash() with an
invalid git repo path.

git: check return value from 'git' command

---

src/codegen/function_body_chunk.rs
src/codegen/trampoline_from_glib.rs

See https://github.com/gtk-rs/glib/pull/605
----
This works fine for glib, gio, gdk, gdk-pixbuf, pango, pangocairo and gtk (I have local branches for all of them that I will submit once this is merged). Please review but don't merge until I've also checked GStreamer :)

Generate code for new from_glib_borrow signature

---

src/analysis/properties.rs
src/analysis/signals.rs
src/writer/to_code.rs

Regen sample: https://github.com/gtk-rs/gtk/pull/983

Remove all transmute calls in generated code

---

src/codegen/enums.rs

use #[non_exhaustive] for generated enums

---

src/analysis/properties.rs
src/analysis/signals.rs
src/writer/to_code.rs

Part of https://github.com/gtk-rs/gir/issues/901
This reverts commit 5ca26d9e8400e8fa904f23c9dc8597241a7ba1d0.

Revert "Remove all transmute calls in generated code"

---

src/library.rs

This is a bit tricky since we currently filter out based on names. However, enums can have names ending with "Type" for example, filtering them out. I wonder if classes or other types may be filtered out for the same reason? I couldn't find one but I think it's a possibility.

Show more not generated types

---

src/codegen/sys/lib_.rs

We generate them only as constants so overlaps are not really a problem
and like this we a) represent the C header more accurately and b) don't
randomly skip values based on their order. Duplicated values could be
aliases or old names for the same thing.

Generate duplicated enum values in the -sys crate

---

tests/sys/gir-gdk.toml

The reason #917 was needed (that #915 passed CI) was that the new feature @EPashkin added wasn't actually tested by any of the tests.  This patch causes `gdk-sys` in the tests to require the split build option.  This way bugs in this code in the future should be caught.

tests: use split_build_rs in gdk gir test

---

.github/workflows/main.yaml
README.md
src/codegen/sys/build.rs
src/codegen/sys/cargo_toml.rs
src/codegen/sys/mod.rs
src/config/config.rs

Fix #916 
@sdroege Please test this.
I also found that previous version lost "v1_36_7" in pango and "v2_44" in glib in build.rs, and only added it to Cargo.toml

Add options.extra_versions and lib_version_overrides configurations

---

src/codegen/function_body_chunk.rs
src/codegen/signal.rs
src/codegen/trampoline_from_glib.rs

```
commit 6d9a4cc73a956e6ca97adcbcd3ef2826356c2bce (HEAD -> as_deref)
Author: Sebastian Dröge <sebastian@centricular.com>
Date:   Wed Jun 3 17:31:37 2020 +0300
Fix generation of signal emit functions outside traits
512 |             glib::Object::from_glib_borrow(self.to_glib_none().0 as *mut gobject_sys::GObject)
|                                            -----^^^^^^^^^^^^--
|                                            |    |
|                                            |    cannot infer type for type parameter `P` declared on the trait `ToGlibPtr`
|                                            this method call resolves to `glib::translate::Stash<'a, P, Self>`
commit 8d7902afa507498e8342b3ad23d6672aa04b379c
Author: Sebastian Dröge <sebastian@centricular.com>
Date:   Wed Jun 3 17:30:38 …
```

Fix some code generation issues

---

src/codegen/enums.rs
src/codegen/flags.rs
src/codegen/sys/build.rs
src/codegen/sys/lib_.rs
src/codegen/sys/tests.rs
src/parser.rs

New clippy is much stricter.
I decided to ignore `write_literal` because we printing many brackets.

Fix and ignore clippy warnings

---

src/analysis/class_builder.rs
src/analysis/functions.rs
src/analysis/imports.rs
src/analysis/properties.rs
src/analysis/signals.rs

https://github.com/gtk-rs/gdkx11/issues/1
Builder add its types with version from last property, we missed this because modules have same version.
cc @GuillaumeGomez , @sdroege 
Affected crates gio, sourceview.
```diff
+++ b/src/auto/list_store.rs
@@ -5,14 +5,10 @@
use gio_sys;
#[cfg(any(feature = "v2_44", feature = "dox"))]
use glib;
-#[cfg(any(feature = "v2_44", feature = "dox"))]
use glib::object::Cast;
-#[cfg(any(feature = "v2_44", feature = "dox"))]
use glib::object::IsA;
use glib::translate::*;
-#[cfg(any(feature = "v2_44", feature = "dox"))]
use glib::StaticType;
-#[cfg(any(feature = "v2_44", feature = "dox"))]
use glib::ToValue;
use std::fmt;
use ListModel;
```

Add ImportsWithDefaults

---

src/analysis/functions.rs

The idiomatic way for Rust constructors is to be named from_XXX()
instead of new_from_XXX() and with_XXX() instead of new_with_XXX().
Fix #905

functions: rename constructors

---

src/analysis/record.rs
src/codegen/enums.rs
src/codegen/flags.rs
src/codegen/general.rs
src/codegen/record.rs

And only make use of the functions conditionally if they're newer than
the type itself.
This only applies to records (boxed/shared), enums and flags. GObject
types always need a get_type function and won't work without, so there
will never be the case that the function is added later.
Fixes https://github.com/gtk-rs/gir/issues/839
----
This should be all for being able to update pango now. Generates for example the following:
```rust
#[cfg(any(feature = "v1_44", feature = "dox"))]
glib_wrapper! {
#[derive(Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct AttrIterator(Boxed<pango_sys::PangoAttrIterator>);
match fn {
copy => |ptr| pango_sys::pango_attr_iterator_copy(mut_override(ptr)),
free => |ptr| pango_sys::pango_attr_iterator_destroy(ptr),
get_type => || …
```

Handle version configuration on get_type functions in non-sys mode

---

src/codegen/sys/cargo_toml.rs

collect_versions() returns all the versions while
env.namespaces.main().versions() is a filtered subset.

cargo_toml: set feature-versions for all versions

---

src/codegen/sys/build.rs

Use `eprintln` for writing to stderr

---

src/codegen/doc/mod.rs

I realized afterwards that bitfields fields and enum variants were both `Member`, so it's not good for the second one. Maybe I should use the same code for bitfields as well? What do you think @EPashkin ?

Fix variant doc generation

---

src/codegen/sys/build.rs
src/codegen/sys/cargo_toml.rs

shell-words 1.0 is compatible with 0.1: https://github.com/tmiasko/shell-words/commit/ae583f7a19ca886e40d829cf93dcc95365580e78

sys crates: update shell-words dependency and remove unused imports in build.rs

---

README.md
src/analysis/functions.rs
src/analysis/return_value.rs
src/config/config.rs
src/config/gobjects.rs

This has to be used carefully as many libraries forgot to put
`nullability` annotations on return values, which then causes a panic if
an unexpected `NULL` is returned.
----
CC @GuillaumeGomez @EPashkin @sophie-h
With this you can check what kind of changes are generated when trusting the gir files, and then report any missing nullable annotations to the C libraries.

Add per-crate and per-object configuration to trust return value nullability

---

src/codegen/function_body_chunk.rs
src/library_postprocessing.rs

That is, don't remove them from the list of functions to generate. We
only do that for the non-sys bindings as there these shouldn't become
separate functions but part of the glib::ErrorDomain trait impl.
----
After this we should regenerate things.

Generate error quark functions in -sys mode if they exist

---

src/codegen/sys/cargo_toml.rs
tests/sys/secret-sys/Cargo.toml

This will allow us to override the library name depending on the
version, see https://github.com/gdesmott/system-deps/issues/11

toml: use new system-deps versions syntax

---

src/analysis/functions.rs

This was accidentally changed in 3303549443533079b3d9e49b61c6336f5ccdeacb.

Make sure that closures in global functions require Send+Sync

---

README.md
src/analysis/class_builder.rs
src/analysis/constants.rs
src/analysis/functions.rs
src/analysis/info_base.rs
src/analysis/object.rs
src/analysis/properties.rs
src/analysis/signals.rs
src/codegen/enums.rs
src/codegen/flags.rs
src/codegen/function.rs
src/codegen/function_body_chunk.rs
src/codegen/general.rs
src/codegen/record.rs
src/codegen/sys/functions.rs
src/codegen/trait_impls.rs
src/codegen/translate_from_glib.rs
src/config/constants.rs
src/config/functions.rs
src/config/gobjects.rs
src/config/members.rs
src/config/properties.rs
src/config/signals.rs

This holds if we assume the C side Unicode validity can be trusted.
Consequence of the removal of `FromGlib<u32>` for `char` and `Option<char>` in https://github.com/gtk-rs/glib/pull/718.
The following projects were updated:
- https://github.com/fengalin/atk/tree/translate-option-result
- https://github.com/fengalin/pango/tree/translate-option-result
- https://github.com/fengalin/gtk/tree/translate-option-result
With these updates, `gtk-rs/examples` builds successfully. `gstreamer-rs` doesn't seem affected.
I'll send pull requests for `atk`, `pango` and `gtk` when this is merged.

Use char::TryFrom::<u32> to convert from UniChar

---

src/analysis/object.rs
src/codegen/general.rs
src/codegen/object.rs

This is possible due to https://github.com/gtk-rs/gtk-rs/pull/10.
Regenerating the gtk-rs bindings and compiling it seems to work with the current changes there in https://github.com/gtk-rs/gtk-rs/pull/11.

Do not pass $rust_class_name to glib_wrapper!

---

.github/workflows/main.yaml

Try to fix Windows CI

---

Cargo.lock
src/analysis/object.rs
src/analysis/record.rs
src/codegen/enums.rs
src/codegen/sys/tests.rs
src/codegen/trait_impls.rs
src/config/config.rs
src/config/error.rs
src/config/property_generate_flags.rs
src/main.rs
src/xmlparser.rs

Extracted from #991
While addressing minor code inconsistency I stumbled upon a commit from Heftig using `rerast` for structural refactoring, and it turns out Rust-analyzer supports SSR as well. This made it possible to easily do a bulk of conversions to use `?` instead of manual `match` blocks. See the relevant commits for the rules used.
One minor deficiency is the inability to repeat labels: it is impossible to specify `Some($a) => $a`, meaning that a manual check is necessary to see if the right hand side wasn't doing any extra conversion. These had to be addressed by hand, but weren't many.

Simplify `match` blocks into `?` operator using SSR

---

src/codegen/enums.rs
src/codegen/general.rs
src/codegen/object.rs
src/version.rs

Simplify some duplicate code around cfg and version handling, and fix the following warnings when compiling with the `dox` feature:
warning: unused doc comment
--> gstreamer/src/auto/enums.rs:761:41
|
761 |             #[cfg_attr(feature = "dox", doc(cfg(feature = "v1_18")))]
|                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
762 |             66817 => EventType::InstantRateSyncTime,
|             --------------------------------------- rustdoc does not generate documentation for match arms
Fixes: c63d1fa ("Generate doc cfg attributes for more beautiful docs")

codegen/enum: Do not generate doc(cfg) on match arms

---

src/codegen/general.rs
src/codegen/sys/build.rs
src/codegen/sys/cargo_toml.rs
src/codegen/sys/functions.rs
src/codegen/sys/statics.rs

When rustdoc is running, it provides alongside `cfg(doc)`, which is all we need, making the `dox` feature unnecessary.
I need to check on gtk-rs first if I didn't forget it there so please wait before merging!

Switch to doc cfg instead of feature dox

---

src/codegen/object.rs
src/codegen/record.rs
src/codegen/trait_impls.rs

For the time being this only adds missing `#[cfg]` blocks on four trait `impl`s in `gtk-rs`. It'll become more interesting when `gstreamer` pulls in v1.20 gir files and associated enum function generation (#991) comes online.
CC @sdroege

codegen: Add version condition on special function traits

---

src/codegen/object.rs
src/codegen/trait_impls.rs
src/config/ident.rs
src/library.rs

`write_fmt` (what `write!` expands to) needs to be set up with an `std::fmt::Arguments` object that is consequently iterated.  All segments of the format string get `Display::fmt` called on them and those implementations usually result in calling some form of `write_str` (at least for `&str`).
This is a minor change that only saves few unnecessary cyles and is mostly done for cosmetic reasons.  It finishes the work started in 3eaed54.
---
This follows a discussion in https://github.com/gtk-rs/gtk-rs/pull/155. The change results in hundreds of file changes in gtk-rs which is a lot of noise to bear. The new format of `f.write_str("Some string literal")` is nicer to read though, and we're already making massive changes with the docs anyhow.

Use write_str instead of write_fmt when no formatting is needed

---

src/analysis/child_properties.rs
src/analysis/properties.rs
src/codegen/enums.rs
src/codegen/flags.rs
src/codegen/property_body.rs

Fixes an issue where glib::Value could conflict with other
things named "Value"

codegen: Explicitly use glib::Value instead of importing

---

src/codegen/general.rs
src/codegen/sys/build.rs
src/codegen/sys/cargo_toml.rs
src/codegen/sys/functions.rs
src/codegen/sys/statics.rs

Reverts gtk-rs/gir#1005 as explained in https://github.com/gtk-rs/gir/issues/1009

Revert "Switch to doc cfg instead of feature dox"

---

src/codegen/sys/cargo_toml.rs

See: https://gitlab.freedesktop.org/gstreamer/gstreamer-rs/-/merge_requests/565#note_709394
In the case of GL EGL/Wayland/X11 we use gstreamer-gl-1.0 for every version except from 1.18 onwards, where these are renamed to `gstreamer-gl-{egl,wayland,x11}-1.0`.
This requires us to manually change the name of the "unversioned" system dep in Cargo.toml, without the generator overwriting it afterwards.
---
Let me know if this should be a separate helper function next to `set_string` instead.

cargo_toml: Do not overwrite library name for unversioned system-deps

---

src/codegen/sys/build.rs

The latter just disappears instead of being printed.
Fixes https://github.com/gtk-rs/gir/issues/1016

Use `cargo:warning` instead of `eprintln!` for printing warnings

---

Cargo.lock
src/analysis/enums.rs
src/analysis/flags.rs
src/analysis/function_parameters.rs
src/analysis/functions.rs
src/analysis/imports.rs
src/analysis/mod.rs
src/analysis/object.rs
src/analysis/record.rs
src/analysis/signals.rs
src/analysis/special_functions.rs
src/codegen/constants.rs
src/codegen/enums.rs
src/codegen/flags.rs
src/codegen/function.rs
src/codegen/functions.rs
src/codegen/mod.rs
src/codegen/object.rs
src/codegen/parameter.rs
src/codegen/record.rs
src/codegen/special_functions.rs
src/codegen/trait_impls.rs
src/env.rs

Leverage existing function generation for class/record to generate associated functions on enumerations as well, instead of having to write these by hand :tada:. The MR for `gstreamer-rs` can be found [here](https://gitlab.freedesktop.org/gstreamer/gstreamer-rs/-/merge_requests/630). These changes came up during https://gitlab.freedesktop.org/gstreamer/gstreamer-rs/-/merge_requests/581.
This relies on functions being associated with the `<enumeration>` in `.gir` files as opposed to being free (same story with class/record), see https://gitlab.freedesktop.org/gstreamer/gst-plugins-base/-/merge_requests/805 for an example where this was not the case.
Note that we have [decided](https://gitlab.freedesktop.org/gstreamer/gst-plugins-base/-/merge_requests/805#note_616786) against turning the …

Generate `impl` blocks for associated enum functions

---

src/codegen/sys/cargo_toml.rs

#1020 
Changed the way `package.metadata.system-deps` `name` is checked and inserted.

Fixed issue generating the -sys/Cargo.toml

---

src/config/functions.rs
src/config/ident.rs
src/config/properties.rs

It's a common issue when edition the gir files so instead of silently fail, it now displays an error.
cc @sdroege

Add an error in case a name field has content of the pattern field

---

.github/workflows/main.yaml
Cargo.lock
src/config/ident.rs

The index contained in GH Actions' virtual environments always lag behind a bit and might point to superseded packages (as is the case with CI failures observed in #1032 and #1033).
Also run `cargo update` and fix a linter warning for `Regex` being too large.
These changes are already included in #1032 and #1033.

CI: Run apt update before apt install

---

.github/workflows/main.yaml
Cargo.lock
README.md
src/analysis/record.rs
src/codegen/record.rs
src/config/gobjects.rs
src/config/ident.rs

This override only works when `get_type` is available and is intended when copy and free are not available, to call the generic `g_boxed_copy/free` functions (which under the hood resolve the right `copy/free` function from its `GType`, as retrieved with get_type).
However, this behaviour is already implied if `copy/free` nor `(un)ref` are found. Hence it is only useful to forcibly use generic `g_boxed_copy/free` even if type-specific functions are directly available in G-IR and Rust. That can almost never be the right thing.
The functionality isn't used for nearly 3 years, and wasn't even used for all that long in gstreamer-rs; it was introduced [here][1] and removed a mere [15 days after][2].
[1]: https://gitlab.freedesktop.org/gstreamer/gstreamer-rs/-/commit/3a0c9723044fb3c9063fcef60e02 …

Remove use_boxed_functions override

---

.github/workflows/main.yaml
Cargo.lock
README.md
src/analysis/functions.rs
src/codegen/function.rs
src/codegen/function_body_chunk.rs
src/config/functions.rs
src/config/ident.rs

While implementing `GLFilter` bindings review suggested to mark a few new functions as `unsafe`.  It saddened me to have to copy these functions to "manual" files and repeatedly update/maintain them as the main repo and `GLFilter` MR progressed: notable are the addition of `doc(alias)` and mutability changes.  Not to mention changes to versioning `cfg()` blocks that those functions were luckily not affected by.

function: Teach gir how to generate whole functions as unsafe

---

README.md
src/codegen/sys/cargo_toml.rs
src/config/config.rs

In `gdkx11`, the `cairo` dependency is optional but is still being used with `dox`. We need to be able to generate extra `dox` features and this feature does it.

Add extra_dox_features config setting

---

Cargo.lock
src/analysis/special_functions.rs
src/codegen/general.rs
src/codegen/record.rs

While not harmful at all (clippy doesn't even flinch when writing `as *mut _` where a `*const` is required; not to mention opaque `mut_override` function calls) it is misleading to see `mut_override` in calls like `copy` where this is not required at all.
---
This is a rather quick and gross bit of duct-tape for something that's not really harming anything but readability and manual analysis of autogenerated files; feedback and suggestions welcome!

codegen: Omit mut_override from boxed copy if parameter is *const

---

src/analysis/enums.rs
src/analysis/flags.rs
src/analysis/functions.rs
src/analysis/mod.rs
src/analysis/object.rs
src/analysis/properties.rs
src/analysis/signals.rs
src/analysis/special_functions.rs

While adding some new classes to gstreamer-rs gir keeps emitting `use glib::translate::*;` for classes that do not have any members that could possibly use translation functionality, resulting in obvious "unused import" linter warnings. ~Simply adding this import only if there are members (functions, signals or properties) solves that problem for now.~ All these cases have been addressed by adding `with_defaults` import wrappers, and importing "global" imports under these so that they have the appropriate version constraints. In cases where no members exist (or they are commented out) this code does not even run at all, and the import is completely omitted (the original issue this PR was about).

analysis: Move global imports to object-specific analysis and under versioning constraints

---

src/codegen/sys/tests.rs

This is a first step in the plan outlined in https://github.com/gtk-rs/gir/issues/1047
Instead of compiling a C program for each layout and one for each
constant to check, generate a single layout.c and a single
constant.c which output all the values, one per line.
On the rust side, it is easier to compile and run the C program
just once and then parse its output one line at a time to compare
with the corresponding rust record.
Note also that C programs are now taken by the system's header
files (eg atk.h) rather than from `-DATK_FOO=1` passed by the
test itself. I think this is actually the right thing to check
since that is the real value we want to compare with.
However this also means that the test will fail when run on
a system older than the one used to generate the gir files, since …

codegen: rework ABI tests to use a single C program for each test

---

src/codegen/sys/cargo_toml.rs

The return type of the probe() method changed, so this will affect user
code doing manual work in their build.rs, the one we generate does not.
I tried regenerating `gtk-rs` and it build fine.

sys: use system-deps 3.0

---

src/codegen/enums.rs

Avoids `#[doc(alias = "...")]` is the same as the item's name errors

doc_alias: don't generate if the enum c_name = rust_name

---

src/codegen/signal.rs

ObjectExt::emit should take a SignalId instead of the signal name
see https://developer.gnome.org/gobject/stable/gobject-Signals.html#g-signal-emit-by-name
Needed for https://github.com/gtk-rs/gtk-rs/pull/302

signals: rename emit to emit_by_name

---

src/codegen/sys/tests.rs

When there are no C types, we don't need the crate imports.

codegen: Avoid a dead code warning in ABI tests

---

README.md

It's `assertion`, not `assertions`

README: fix object.function "assertion" key name

---

src/analysis/properties.rs
src/analysis/signals.rs
src/chunk/chunk.rs
src/codegen/signal.rs
src/codegen/signal_body.rs
src/library.rs
src/parser.rs
src/writer/to_code.rs

Some GObject signals use a non-default [_detail_ argument](https://developer.gnome.org/gobject/stable/signal.html#signal-detail). This allows one to specify that a closure should only be invoked on a subset of that signal's emissions.
There is an attribute in the GIR annotations that specifies when a signal uses non-default values of _detail_. As of time of writing, the code generated by the `gir` tool does not allow one to specify the value of _detail_ in the relevant connect methods&mdash;the closure passed to `connect_<signal name>` will get invoked on all emissions of that signal, regardless of the value of _detail_. This PR contains an attempt at adding such support in. For signals that use _detail_, the relevant method's signature is changed from, e.g.,
```rust
fn …
```

Add support for connecting to signals with details

---

src/codegen/general.rs
src/config/config.rs

So for example, if we set "a/../b", it'll write up "b" (because "a" is "eaten" since there is a ".."). If there is no parent folder before a "..", it does nothing.

"canonicalize" paths

---

README.md
src/analysis/class_builder.rs
src/config/config.rs
src/config/gobjects.rs
src/library.rs

In some crates like gtk3/gtk4, creating a builder pattern is often set to true. It makes the configuration file super huge. This is an effort to try to reduce that by adding an option to always enable the builder pattern generation. 
Note that you can still disable builder pattern generation individually using `ignore_builder = true`
See the following commit for a real use case: https://github.com/gtk-rs/gtk4-rs/pull/219/commits/e3eac0f3adc5852b68cffc814445fd7627b31614

add an option to always generate builder patterns

---

src/codegen/sys/statics.rs

Required to fix gdk since the latest update of clippy
```
error: name `GdkGLError` contains a capitalized acronym
--> gdk4/sys/src/lib.rs:111:10
|
111 | pub type GdkGLError = c_int;
|          ^^^^^^^^^^ help: consider making the acronym lowercase, except the initial letter: `GdkGlError`
|
= note: `-D clippy::upper-case-acronyms` implied by `-D warnings`
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#upper_case_acronyms
error: name `_GdkGLTextureClass` contains a capitalized acronym
--> gdk4/sys/src/lib.rs:2699:12
|
2699 | pub struct _GdkGLTextureClass(c_void);
|            ^^^^^^^^^^^^^^^^^^ help: consider making the acronym lowercase, except the initial letter: `_GdkGlTextureClass`
|
= help: for further information visit …
```

sys mode: allow clippy warning upper_case_acronyms

---

Cargo.lock
src/codegen/general.rs
src/config/config.rs

@GuillaumeGomez This is the implementation I intended to make, back when originally noticing and reporting this issue. Unfortunately you merged the PR just before I was able to send it as a review suggestion, so here it is as a PR instead.
- Accepts an `impl AsRef<Path>`;
- Returns a `PathBuf` since it's still a path, so no changes are needed in the other files. Those have been reverted;
- No unnecessary clones, `as_os_str` / `to_str` / `to_owned` confusing code: just playing around with path components and copying them to a new buffer (owned `PathBuf`) at once in the end;
- Fails on paths that go out of their "root/current" directory, ie. `../`;
- Tests, but we'll have to see what to do with silently removing `CurrentDir` and `RootDir`!

config: "Canonicalize" ../ away from relative git paths

---

src/config/config.rs
src/git.rs

Depends on #1041
With the new separate gir directories it is useful to know what repo (url) a git hash came from, without hardcoding it here. Consensus shows that these repos are either directly cloned through submodules with a default remote named `origin` or a manual rename to `upstream` with the personal remote (from which PRs are commonly created) named `origin`. In that case the url of `upstream` is preferred.
CC @GuillaumeGomez @sdroege

git: Read remote url from upstream or origin

---

src/analysis/symbols.rs
src/codegen/doc/format.rs
src/codegen/doc/mod.rs

Or self-dubbed intra-docs lite (wrt gir). This PR is the safest of the bunch: `@` is only used in limited quantities and pretty much every C symbol (in GStreamer) links to a valid item. There's even extra validation to ensure that the type/parent name of the symbol matches that of the type the docs are generated for!
We still have the debate about seeing or hiding `crate::` and `Self::` in the generated HTML docs going on: https://github.com/gtk-rs/gir/pull/1085#issuecomment-810171414. @GuillaumeGomez doesn't mind and prefers shorter gir and markdown code, what do the other maintainers think? See the screenshots how having `crate::` and `Self::` in the HTML looks.

[1/3] Emit intra-doc links for self (`@`) references

---

src/config/config.rs

`normalize_path` was introduced in [1] for pretty-printing relative paths with `../` ParentDir components.  It was not intended for use outside of displaying scenarios but thanks to tests we can safely use it to solve a mismatch [2] when searching for submodule paths in `.gitmodules`.
This functionality introduced with [3] finds the submodule associated with a path based on string matching in order to pull out the URL, but was only tested with GStreamer-rs where "clean" paths are passed in through gir's `-d` option.  Gtk-rs and gtk4-rs use `girs_directories =` in `Gir.toml` with relative paths like `gtk4/../gir-files`: these cannot be found in `.gitmodules` with simple string matching and need the path simplified first.
[1]: https://github.com/gtk-rs/gir/pull/1075
[2]: …

config: Normalize submodule path before looking it up in .gitmodules

---

src/analysis/functions.rs
src/codegen/doc/mod.rs

This is a workaround for renamed functions not being matched during doc generation. A better solution would require a rework of `gir` so that codegen processes "analysis augmented" items everywhere.
It's not enough to check the `configured_functions` for a `rename`d value since, among others, final renaming uses heuristics and performs name conflict resolution against existing methods and properties. The renaming logic is implemented in `analysis::functions`. The workaround consists in retrieving the `analysis::functions::Info` to get the `new_name`, if any.
This allows generating new `*.md` files with the expected names. Currently, these files are stored in https://github.com/gtk-rs/lgpl-docs. However, they are only updated when a new version is released. Discussions are in progress so …

Fix renamed functions not being documented

---

src/analysis/record.rs
src/codegen/record.rs

This constraint is already enforced with a `panic!` during codegen,
effectively disallowing Gir.toml from specifying objects that cannot be
generated.  It is now more obvious instead of being just an error line
in the (already pretty spammy) logs.
Furthermore analysis is also used to generate documentation, including
those for manual types.  Bailing here means no analysis for the type
is available leading to missing documentation.  After this change we get
a bunch of missing text to show up in `docs.md` in GStreamer for the
manual types that lack memory functions.
See also #1094
---
I have been thinking about wrapping `return None;` in `needs_generate()` but that seems such an unnecessary and arbitrary constraint, let's catch it in codegen instead.

analysis/record: Do not bail on missing memory functions

---

src/codegen/doc/mod.rs

Using intra-doc-links saves quite a bit of code in gir, looks cleaner in the markdown files and resulting docs (`[src]` button mostly), and has the advantage of being checked by `rustdoc` for validity.
That last point is not totally fair as most of these trait "implements" / "implementors" segments are generated inside macros, for which`rustdoc` does not seem to emit any warnings or errors currently.
---
This has only been tested on GStreamer-rs, and only sampled at random because of aforementioned "no-warnings-in-macros" issue :disappointed:

doc: Use intra-doc-links instead of relative paths to html pages

---

build.rs
src/codegen/general.rs
src/config/config.rs
src/git.rs

Intially plaguing GStreamer-rs this code grabs the git hash from the root repository if the specified gir directory is not a submodule.  GStreamer-rs since moved all gir files to subdirectories (because it is possible to have multiple now) but various external projects have a single gir file checked in to the root repo and do not want to see all generated files change the hash after every regeneration while the root repository is checked out on a different commit.
This change uses `git rev-parse --show-toplevel` to resolve where the repository (folder containing `.git`) for a given directory lives and ignores the hash and URL if that is equivalent to the canonical path of the root.
CC @sophie-h for requesting this :)

config,git: Omit gir directory hash and URL if not a submodule

---

Cargo.toml
README.md
generator.py

This is a direct import of all the commits from `gtk-rs` (the original source, and it's the most complete) with https://gitlab.freedesktop.org/gstreamer/gstreamer-rs/-/merge_requests/739 for `docs/` generation and https://gitlab.freedesktop.org/gstreamer/gstreamer-rs/-/merge_requests/740 to run all `gir` processes in parallel since they have no inter-dependencies and give a **massive** speed boost the more cores one has.
We'd like to place this script with `gir` so that it can be shared between `gtk-rs`, `gtk4-rs` and `gstreamer-rs` (and perhaps other projects that wish to invoke `gir` for every `Gir.toml` found in their workspace) without having to copypaste the file/changes (yuck) or transplant commits with `git format-patch`/`git am` (less disgusting, but still annoying) whenever we …

Import generator.py from gtk-rs

---

.github/workflows/main.yaml

`generator.py` moved into this repository, and gtk-rs (and friends) now symlink to `gir/generator.py`.  We could simply call `../generator.py` instead, but this make sure the symlink is actually valid.

ci: Symlink gir directory to ourselves to find generator.py

---

src/analysis/symbols.rs
src/codegen/doc/mod.rs

Some types have their trait name overridden for clarity, but this is not always conveyed in the docs.  This bit of code partially solves a case in GStreamer-rs where links show up to `gst::ObjectExt` that should have been `gst::GstObjectExt` instead, as per `trait_name = "GstObjectExt"`.
---
CC @slomo: This doesn't fix our `GstObjectExt` mismatch in GStreamer-rs _yet_! For that we'll have to replicate the override in every `Gir.toml` that uses the type:
```toml
[[object]]
name = "Gst.Object"
status = "manual"
trait_name = "GstObjectExt"
```
Do we have a smarter way of doing so, as well as for the other `trait_name =` overrides?

doc: Always consider `trait_name` from `Gir.toml` in implementation docs

---

src/codegen/object.rs

Following a discussion in [1] we have decided to remove all trait exports - both manual and automatic - from the crate root in favour of having them available to crate users in `prelude` only, as per the intended design.  It was inconsistent to have ExtManual traits available in `prelude` only (and some randomly in the crate root in GStreamer-rs) whereas all automatic traits were re-exported through the crate root as well.
[1]: https://github.com/gtk-rs/gir/pull/1111
CC @bilelmoussaoui

codegen/object: Only re-export traits from `traits`/`prelude` module

---

src/codegen/doc/mod.rs

docs: manual traits are in prelude only

---

src/codegen/general.rs
src/codegen/object.rs

This started as an effort to get rid of the `[Deprecated since XXX]` and `# Deprecated` in the documentation in favour of cleaner and more obvious:
Unfortunately that doesn't show unless the docs are compiled with at least that version - which only seems to be happening in GStreamer thus far.
---
Also emit the missing `#[deprecated]` notice for objects, right into the `mod.rs` file. Is it missing anywhere else?
**TODO**: Probably need the same deduplication for these attributes as we had for the features in #1080. Right now it shows multiple times, even though deprecation of a type should also hold for all members and functions. Unlike `doc(cfg())` features (see #1080 for example) `rustdoc` does not seem to coalesce these:

codegen/general: Emit "Since vXXX" in #[deprecated] attributes

---

src/codegen/doc/mod.rs

Nowadays we have the `doc_cfg` feature rendering clean, consistent and obvious markers for feature requirements through `doc(cfg())` attributes in the code (perhaps automatically derived from `cfg()` attributes in the not so distant future). With this it is not necessary to repeat the requirement in the documentation text once again, which wasn't really obvious nor good-looking to begin with.
Besides, this "Feature:" text is currently erroneously generated on the last member of an enum, instead of on the enum itself (parts omitted for brevity):
```rust
#[cfg(any(feature = "v1_14_1", feature = "dox"))]
#[cfg_attr(feature = "dox", doc(cfg(feature = "v1_14_1")))]
pub enum WebRTCFECType {
/// none
None,
/// ulpfec + red
///
/// Feature: `v1_14_1`
///
UlpRed,
}
```
Note that other …

codegen/doc: Omit "Feature: `vXXX`" text in favour of doc_cfg

---

src/codegen/doc/format.rs

The docs look like a wasteland with all these symbols (containing `::`) in monospace without being clickable. Thanks to intra-doc-links we can simply wrap them in `[]` and color up the whole page!
Things that are still broken:
- Links to manually overridden types: `GstBinExt::iterate_elements()` should use `GstBinExtManual`;
- Signals. `` [`Bin::element-added`](crate::Bin::element-added) `` doesn't exist. Messing with the regex and `` [`Bin`](crate::Bin)::element-added `` might be better for the time being (if monospace is added back);
- The C docs use a format like `#GstElementClass.set_context()` which are not yet parsed correctly;
- (For GStreamer) various documentation fixes that are merged in `master` only and will probably only come around with the v1.20 release.
- `@` references …

[3/3] Emit intra-doc-links for symbol references

---

src/codegen/doc/format.rs

The same as #1088 but for functions. This one is more tricky since not all functions (ie. memory management functions like `free` and `unref`) are generated, hence result in invalid links.  Certain functions are implemented manually and do not exist under `<type>Ext` but `<type>ExtManual` - this might be a shortcoming of the existing C symbol mapping that should simply not map those functions to an `Ext` type. Other than that the gains in GStreamer are massive over the few tens of broken links.

[2/3] Emit intra-doc links for function references

---

src/analysis/properties.rs

Following [1] an unnecessary `glib::ToValue` import showed up in auto
code, which does not appear to be used in gtk-rs nor gstreamer-rs.
After all, getters convert from Values, not to Values.
Fixes: c6cacb0 ("Implement handling of new Value traits")
[1]: https://gitlab.freedesktop.org/gstreamer/gstreamer-rs/-/merge_requests/746#note_893561
---
Cc @sdroege, this seems correct. Unfortunately `gtk-rs` was already riddled with `#[allow(unused_imports)]`.

analysis/properties: Remove unused ToValue import for property getters

---

build.rs
src/git.rs

`gir`'s hash in version files gets out of sync quite frequently with the hash of the submodule.  This happens when generating from a change locally, creating a PR and later regenerating on the merge commit.  When no file changes have been made `gir` doesn't get recompiled with the newer hash, but the submodule hash is still changed resulting in a mismatch.  It is usually caught later on another machine/checkout.
This change ensures `gir`'s hash is always updated when the checkout changes, even if no code changes have been made that would normally cause `cargo` to recompile it.

build: Rerun if git hash changed

---

src/codegen/enums.rs
src/codegen/flags.rs
src/codegen/sys/tests.rs

Some low-hanging fruit to shorten generated code and making it more readable at the same time.
This is only scratching the surface. If we really want to combat `use_self` we'd have to replace function arguments and return types, which is not worth it IMO. This was simple enough (simplifying the generator, too) that it should be okay to do.

Fix some clippy::use_self warnings in generated code

---

src/codegen/object.rs

this allows us to enable clippy::let_and_return lint

codegen: only use ret if a builder_postprocess is set

---

src/codegen/enums.rs

Commit 3f36d06 ("Fix some clippy::use_self warnings in generated code") did away with repeating the surrounding type name in places where the `Self` keyword is preferred (`clippy::use_self`), but accidentally also replaced the type in a string literal used for formatting (first noticed in [1]).  When these enums are printed the logs will be filled with helpless `Self::<variant>` instead of `<type>::<variant>` which wasn't intended.
[1]: https://github.com/gtk-rs/gtk4-rs/pull/349/files#r625049878
---
Can anyone double-check aforementioned commit for more such mistakes.  I don't see any but I don't trust my eyes anymore :flushed:

codegen/enums: Keep emitting name of `Self` in string literals

---

src/analysis/functions.rs
src/analysis/properties.rs
src/codegen/child_properties.rs
src/codegen/function.rs
src/codegen/properties.rs
src/codegen/signal.rs

This is an attempt at fixing gtk-rs/gir#1105. See also [the result for `gtk-rs`](https://github.com/gtk-rs/gtk-rs/pull/490).
It also addresses concerns described by @sdroege regarding some doc aliases which didn't match the name in upstream doc due to name mangling or property naming conventions. It also adds doc aliases for child properties which were not generated before.
Note that aliases from properties are no longer generated when they match the final name, hence the reduction in the "prop name alias" step below.

Add rename doc aliases

---

README.md
src/analysis/functions.rs
src/config/functions.rs

Some `constructor`s are not annotated as such in `gir` files. This PR allows configuring a function as `constructor` so that it can be renamed according to the naming conventions for constructors.
Required for: https://github.com/gtk-rs/gtk-rs/pull/505

config/function: allow forcing 'constructor' annotation

---

generator.py
src/analysis/symbols.rs
src/codegen/doc/mod.rs

We recently removed all `Ext` and `ExtManual` traits from crate roots in favour of consistently exporting them from the prelude only, and at about the same time merged intradoc links for function symbols.  Both work as intended in isolation, but result in lots of broken links when put together because the documentation generator doesn't know about the existence of a `prelude` module.  This patch corrects the module path by leveraging existing `make_trait_method` machinery.
---
Old part of the comment, this is all fixed now:
~This breaks function references to "normal" `impl StructName` blocks. Could be a simple check for `Ext`/`ExtManual` suffix, but that's horrible.~
~All in all I'm really lost as to what the best way is to represent where a function lives, this should afaik be available …

doc: Link trait functions in `prelude`

---

generator.py
src/analysis/symbols.rs
src/codegen/doc/format.rs
src/codegen/doc/mod.rs

Depends on #1119.
Rust prelude symbols - `true`, `false` and `None` - are explicitly added to the list of symbols.  These are the only global constants/symbols that shouldn't receive a `crate::` prefix.  Everything else coming from the current or another crate must be imported from the root as it may reside in another file/module.

codegen: Emit `crate::` for all global `%` constants except from prelude

---

src/codegen/doc/format.rs
src/codegen/doc/mod.rs

A lot of effort was put in to hide these from the final documentation, by using `[]()` kind of links.  Unfortunately, for symbols that don't exist (broken references in g-ir documentation, types that haven't been implemented yet, functions related to lifetime management and cleanup that are implicit in Rust) these generate clickable links pointing to a Rust item path (`crate::Foo::bar`) which is inconvenient.  On the other hand, without `[]()` indirection but simple `[]` intradoc links rustdoc doesn't emit a link for unknown items at all, leaving a simple monospace Rust path surrounded by brackets.
---
CC @GuillaumeGomez: we discussed this on IRC and it should be a nice simplifications. Seeing `Self::` or `crate::` in docs shouldn't be too bad, on the contrary readers immediately know …

[RFC] codegen/doc: Simplify links by allowing `Self::` and `crate::` prefix

---

src/analysis/functions.rs
src/codegen/function.rs

... otherwise we can't take advantage of config and auto-renaming
on non-future function.

funct async: use codegen name for _future funct

---

src/codegen/sys/lib_.rs

Prints the same, but without a cast.

codegen/sys: Use pointer formatting literal to print address of self

---

src/main.rs

This app was probably written before Rust 1.26 introduced main which could return `Result`
https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-1260-2018-05-10
As far as I understand this, the behaviour should be exactly the same

Rename `do_main` to `main`

---

src/codegen/doc/mod.rs

All deprecated objects, traits and records already receive a `#[deprecated = "Since XXX"]` annotation in Rust which neatly shows up in the docs. The extra `[Deprecated]` label in the documentation is not necessary anymore.
`# Deprecated` headers remain for the documentation part clarifying why an item has been deprecated, and what its alternative is.
---
I planned to do this a while ago given https://github.com/gtk-rs/gir/pull/1087 but funnily enough gtk3-rs recently bumped a bunch of minimum versions and now no deprecated objects/traits/records exist anymore :stuck_out_tongue:

codegen/doc: Drop `[Deprecated]` text in favour of Rust annotations

---

src/codegen/enums.rs

See https://github.com/gtk-rs/gtk4-rs/pull/397 for the resulted changes
cc @GuillaumeGomez, i suppose that's why we had such code in gtk's ResponseType, basically based on what gir generates :)

codegen: use C value instead of hardcoding it

---

README.md
src/analysis/functions.rs
src/codegen/doc/mod.rs
src/config/functions.rs

Fixes #1115 
A one last type of parameters that's not really useful, is the `n_X` followed after parameter `X` that's an array used to specify the length of the array. Not sure how to check for that one properly. I suppose looking for `n_X` param, if X is found and is of type of Array & `n_X` is of type `gsize` we can omit that one as well?

docs: ignore not useful function parameters

---

src/codegen/object.rs

Fixes https://github.com/gtk-rs/gtk4-rs/issues/405
If a struct contains no method, or all of it's methods are manual for whatever reason this allows generation the builder method automatically

codgen: generate impl T if there are builder properties as well

---

src/analysis/bounds.rs
src/analysis/rust_type.rs
src/codegen/bound.rs
src/codegen/function.rs
src/codegen/mod.rs
src/codegen/object.rs
src/codegen/parameter.rs
src/codegen/ref_mode.rs
src/codegen/signal.rs
src/codegen/trampoline.rs

All the cleanups from #1153 separated in nicely documented, individually reviewable commits.
This includes a simplification of `where T: IsA<Foo>` into specifying the trait bound directly when the type parameter is defined: `func<T: IsA<Foo>>`.
As requested by @GuillaumeGomez the "fix" for `clippy::use_self` is in here too, but in hindsight I'm not too sure how useful it is. This is what it does:
```diff
diff --git a/gdk/src/auto/device.rs b/gdk/src/auto/device.rs
index f53e2a154f..9994f88311 100644
--- a/gdk/src/auto/device.rs
+++ b/gdk/src/auto/device.rs
@@ -450,7 +450,7 @@ impl Device {
}
#[doc(alias = "changed")]
-    pub fn connect_changed<F: Fn(&Device) + 'static>(&self, f: F) -> SignalHandlerId {
+    pub fn connect_changed<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId { …
```

[refactor] Simplify handling of trait bounds and aliases

---

src/codegen/doc/mod.rs

Because such traits don't exists for those types
Can be noticed in https://gtk-rs.org/gtk4-rs/git/docs/gsk4/struct.BlurNode.html where RenderNode is final (actually, it's fundamental, but marked as final on the gir config to avoid the usage of the `Ext` trait)
After the change, the generated doc is like this
```rust
glib::wrapper! {
/// A render node applying a blur effect to its single child.
#[derive(Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct BlurNode(Shared<ffi::GskBlurNode>);
match fn {
ref => |ptr| ffi::gsk_render_node_ref(ptr as *mut ffi::GskRenderNode),
unref => |ptr| ffi::gsk_render_node_unref(ptr as *mut ffi::GskRenderNode),
}
}
``` 
So no more invalid `Ext` traits :)

docs: filter out final types from implements trait list

---

src/codegen/doc/mod.rs

The name is already there, but it isn't an intradoc-link yet.

codegen/doc: Make extension trait docs link back to the type

---

src/analysis/enums.rs
src/analysis/flags.rs
src/analysis/functions.rs
src/analysis/mod.rs
src/codegen/enums.rs
src/codegen/flags.rs
src/config/gobjects.rs

Docs generation is going to look at analysis data to know what variants and functions are available on enums/flags.  External types (in the `manual = []` list) were previously omitted because of their status.  This changes enums and flags to behave like objects and records which only bail if the type is entirely ignored, and perform a `need_generate()` check at `codegen` instead.
Fixes: 50cee9e ("enums: Move rejection and glib imports from codegen to analysis")
Fixes: e549975 ("Copypaste enum analysis and function generation to bitfield")
---
CC @bilelmoussaoui, we're going to need this for #1161.

enums,flags: Always analyze manual types

---

src/analysis/enums.rs
src/analysis/flags.rs

Otherwise unused imports show up in the enums/flags files.
Fixes: 68591f1 ("enums,flags: Always analyze manual types")

enums,flags: Do not analyze imports if the type is not generated

---

src/analysis/functions.rs
src/analysis/mod.rs
src/analysis/object.rs
src/analysis/symbols.rs
src/codegen/doc/format.rs
src/codegen/doc/gi_docgen.rs
src/codegen/doc/mod.rs
src/codegen/enums.rs
src/codegen/flags.rs
src/library.rs
src/library_postprocessing.rs
src/parser.rs

What does this PR do:
- Adds support of the news docs linking format used in GTK4 newer Pango/GdkPixbuf and other GTK specific libraries.
See https://gnome.pages.gitlab.gnome.org/gi-docgen/linking.html for the linking spec.
-  Switch to using analysis data instead of the symbols list for figuring out whether a function, object, enum member/bitfield variant should have a doc link which solves the broken doc links
- Handles Markdown codeblocks correctly as we now try to find items in a \`item\` situation and falls back to text language in case no language is defined so that doc tests can still pass.
The advantages of doing so are:
- Support of renamed functions
- Properly ignored enum members/flag variants are handled correctly
- No more #1140 
- Properly working links or nothing.
The …

Docs: refactored + GI Docgen support

---

src/analysis/functions.rs

`gir` already knows which functions it is not able to generate given the available dependencies and other constraints, and marks unavailable functions as "commented" (so that a `TODO: call xxx()` shows up as reminder).  Leverage this information to not generate intradoc links to those items, as they don't exist.

analysis/function: Don't link docs that are commented or invisible

---

src/analysis/functions.rs
src/analysis/mod.rs
src/codegen/doc/format.rs
src/codegen/doc/gi_docgen.rs

Depends on #1178.
Add the missing links (only one in GStreamer) to associated functions and methods on enumerations and flags.

codegen/doc: Generate links for enum/flag functions/methods

---

src/codegen/sys/tests.rs

[libgraphene has float constants](https://github.com/ebassi/graphene/blob/master/include/graphene-macros.h#L112-L113)

Add float format to PRINT_CONSTANT

---

src/codegen/enums.rs
src/codegen/flags.rs
src/codegen/sys/lib_.rs
src/library.rs
src/parser.rs

`gir` XML contains `version=` attributes which are currently redefined manually in `Gir.toml`.  Propagate this info through to codegen to save all this redundant manual extra configuration.

enum,flags: Take `version=` attribute in XML for members into account

---

src/codegen/doc/mod.rs

currently if a type has a unique method marked as a manual, has_trait would be set to false
which means the current type to be documented is assumed to be impl Type instead of trait TypeExtManual if the type is not final
This adds a check based on whether the type is final or not which fixes an issue with https://gtk-rs.org/gtk4-rs/git/docs/gdk4_wayland/prelude/trait.WaylandSurfaceExtManual.html
cc @MarijnS95

docs: properly handle trait name for manual methods

---

src/analysis/bounds.rs
src/analysis/function_parameters.rs
src/analysis/override_string_type.rs
src/analysis/ref_mode.rs
src/analysis/rust_type.rs
src/analysis/types.rs
src/codegen/function.rs
src/codegen/function_body_chunk.rs
src/codegen/trampoline_from_glib.rs
src/config/config.rs
src/config/functions.rs
src/config/members.rs
src/xmlparser.rs

https://blog.rust-lang.org/2021/06/17/Rust-1.53.0.html :shark: 
Previously `|` was only allowed in the top-level of patterns, requiring the circumfering enum variant (usually something wrapped in `Some`, and in `gir` `Type::Fundamental` is common) to be repeated for every inner variant that's matched against.  Not anymore, since 1.53 it is now possible to write `|` within a single variant instead of repeating it many times.

Rust 1.53: Use the new nested or_patterns

---

src/codegen/sys/cargo_toml.rs
src/nameutil.rs
tests/sys/atk-sys/Cargo.toml
tests/sys/gdk-pixbuf-sys/Cargo.toml
tests/sys/gdk-sys/Cargo.toml
tests/sys/gio-sys/Cargo.toml
tests/sys/glib-sys/Cargo.toml
tests/sys/gobject-sys/Cargo.toml
tests/sys/gtk-sys/Cargo.toml
tests/sys/pango-sys/Cargo.toml
tests/sys/secret-sys/Cargo.toml

The `links` annotation in `Cargo.toml` is intended to ensure that in the
crate graph there's at most one crate that's an implementation of
some sort concept.
This can make sense in some scenarios, most prominent of which is when
the crate defines `#[no_mangle]` symbols (e.g. by compiling a vendored C
library.) In that situation linking a binary that depends on two
versions of the library cannot work because of colliding symbol names.
There does not appear to be a similar reason to impose such a
restriction on the users of gir-generated bindings, however. All of
the generated crates link to a system library, they do not define any
`#[no_mangle]` symbols nor they vendor/build C libraries as part of
their build process.  Most likely all the different versions of the
bindings will link to the …

Remove the `links` annotations

---

src/codegen/constants.rs
src/codegen/enums.rs
src/codegen/flags.rs
src/codegen/function.rs
src/codegen/general.rs
src/codegen/object.rs
src/codegen/record.rs
src/codegen/sys/functions.rs
src/codegen/sys/lib_.rs
src/codegen/sys/tests.rs
src/codegen/trait_impls.rs

Attributes on macro-calls don't have any meaning, as indicated by this warning and the feature requirement not showing up in docs:
warning: unused attribute `doc`
--> gstreamer/src/auto/flags.rs:663:29
|
663 | #[cfg_attr(feature = "dox", doc(cfg(feature = "v1_20")))]
|                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
note: the built-in attribute `doc` will be ignored, since it's applied to the macro invocation `bitflags`
--> gstreamer/src/auto/flags.rs:664:1
|
664 | bitflags! {
| ^^^^^^^^
Separate the attribute functions out to be able to generate this `doc(cfg())` attribute inside the macro call on the `struct` (and just
the `struct`, not the `impl` blocks and anything else `bitflags!` generates) while still having the `#[cfg]` guard the entire macro call.

codegen/flags: Put doc attribute on struct instead of macro calls

---

src/codegen/general.rs
src/codegen/object.rs
src/codegen/record.rs

Fix #1221
Currently, `Default` is only implemented for objects that don't take parameters in their `new()` function. This PR adds `Default` implementations for all objects that take parameters in their `new()` function. This makes the workaround  using `Object::builder().build()` obsolete.
The generated code looks like this:
```rust
impl Default for Box {
fn default() -> Self {
match glib::object::Object::new::<Self>(&[]) {
Ok(obj) => obj,
Err(err) => panic!(
"Can't construct Box object with default parameters: {}",
err
),
}
}
}
```

Add default impls for all objects

---

src/analysis/bounds.rs
src/analysis/child_properties.rs
src/codegen/bound.rs
src/codegen/function.rs
src/codegen/object.rs
src/codegen/parameter.rs
src/codegen/trampoline.rs

For https://github.com/gtk-rs/gtk-rs-core/pull/89#issuecomment-846516935
---
`impl` is quite a bit more concise and readable when a type parameter with trait bound is only used once.  Aside that, this simplifies some of the type handling in trampolines by using `P: IsA<>` directly instead of through a `where P: ...` indirection.
---
Related MRs:
https://gitlab.freedesktop.org/gstreamer/gstreamer-rs/-/merge_requests/778
https://github.com/gtk-rs/gtk-rs-core/pull/95
https://github.com/gtk-rs/gtk3-rs/pull/547
https://github.com/gtk-rs/gtk4-rs/pull/404

Use `impl Trait` instead of generic type names with trait bound

---

build.rs

We already ran into the issue of git hashes not updating when checked out to a branch, because the `HEAD` file doesn't change.  `HEAD` does however tell us what branch (ref) the user is checked out to, which is a file much like `HEAD` containing the hash of the commit it is currently pointing to, and will inevitably change if the user "moves around" (ie.  rebasing or committing).  Emitting a `rerun-if-changed` on this file should make the git hash much more reliable.

build: Emit rerun-if-changed for branch file on `ref: ` HEAD

---

src/analysis/info_base.rs
src/analysis/object.rs
src/analysis/record.rs

Previously we would infer the minimum version of a type by the minimum
version of all its functions if not type version information was
available. This causes unnecessarily high minimum version constraints if
the type was available without functions before and later got functions.
Instead this should be fixed in the C library's annotations, and for now
this can also be overridden via Gir.toml if needed.

Remove type version heuristics

---

src/analysis/object.rs
src/analysis/supertypes.rs
src/codegen/general.rs
src/codegen/object.rs
src/config/functions.rs
src/config/members.rs
src/config/properties.rs
src/version.rs

In that case it is necessary to create multiple glib::wrapper! calls
with the different sets of the supertypes.
----
Also a fix for the `Version` type in general. This has no effect at all on the gtk-rs crates but in GStreamer has this important diff:
```diff
diff --git a/gstreamer-editing-services/src/auto/uri_clip_asset.rs b/gstreamer-editing-services/src/auto/uri_clip_asset.rs
index 1b55c5b8..28c5757c 100644
--- a/gstreamer-editing-services/src/auto/uri_clip_asset.rs
+++ b/gstreamer-editing-services/src/auto/uri_clip_asset.rs
@@ -1,11 +1,13 @@
// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// from gst-gir-files (https://gitlab.freedesktop.org/gstreamer/gir-files-rs.git)
// DO NOT EDIT
use crate::Asset;
use …
```

Handle objects correctly where a supertype has a newer version than the type itself

---

src/codegen/general.rs

If the constructor method is deprecated, the builder pattern should have a guard
as well
Needed for gtk4-rs

codgen: generate deprecated cfg attribute for Default trait

---

src/codegen/general.rs

the deprecated guard has no effect on impl

Revert #1248

---

src/codegen/property_body.rs
src/codegen/signal.rs

This PR simplifies the properties getters/setters generation code so we don't go through ffi and use ObjectExt trait directly. This drops a huge amount of code.
It also adapts emit_signal_by_name usages so they are "compatible" with changes in https://github.com/gtk-rs/gtk-rs-core/pull/323
The generated code looks fine, it needs ObjectExt trait to be in-scope, something I have to figure out first before getting this one merged.
Note, this merge request, at least the first commit of it is required for https://github.com/gtk-rs/gtk-rs-core/pull/323 to be merged. As otherwise almost all the usages of the emit_$signal in generated code will panic.

codgen: simplify properties getters/setters

---

src/codegen/general.rs

If no version is set for another crate name, we should always add a guard
This caused some guards to be missing in the builder pattern generation

codgen: fix a logic issue in version_condition_no_doc

---

src/codegen/child_properties.rs

libraries such as libhandy have those
Fixes #1096

codgen: don't assume child props are gtk only

---

src/codegen/object.rs

they are available nowadays through Type::builder method
cc @sdroege

codgen: don't re-export builder types on crate root

---

src/codegen/mod.rs
src/codegen/object.rs
src/codegen/objects.rs

This is a workaround to make sure the builders are usable from outside
without making the modules public nor clutering the main root docs

codgen: generate builders inside a builders module

---

src/codegen/functions.rs

Noticed that in https://gtk-rs.org/gtk4-rs/git/docs/gsk4/functions/index.html

codgen: don't generate a functions mod if it's empty

---

src/codegen/sys/lib_.rs
tests/sys/atk-sys/Cargo.toml
tests/sys/gdk-pixbuf-sys/Cargo.toml
tests/sys/gdk-sys/Cargo.toml
tests/sys/gio-sys/Cargo.toml
tests/sys/gobject-sys/Cargo.toml
tests/sys/gtk-sys/Cargo.toml
tests/sys/pango-sys/Cargo.toml
tests/sys/sys_build/Cargo.toml
tests/sys/sys_build/src/main.rs

As per other 2018 edition changes, the renames should be done on Cargo.toml instead
Fixes #998

codegen: stop renaming crates inside sys generated code

---

book/src/config_api.md
src/codegen/doc/format.rs
src/config/config.rs

The PR moves gi-docgen from always being run along with gtk-doc parser to being optional and opt-in. This way only one of the two is run and avoids the whole issue of what I tried to workaround in https://github.com/gtk-rs/gir/pull/1268
Closes both #1268 & Fixes #1200

Mark gi-docgen as optional

---

src/analysis/bounds.rs
src/codegen/doc/gi_docgen.rs
src/codegen/object.rs
src/config/config.rs
src/version.rs

They don't do anything on their own and must be built to have any effect.
Fixes https://github.com/gtk-rs/gir/issues/1278

Add `#[must_use]` to the autogenerated builder types

---

src/chunk/chunk.rs
src/codegen/function_body_chunk.rs
src/writer/to_code.rs

This introduces an assertion in generated code for FFI logic
making use of GError.
When the wrapped function returns an error code, there are some
idioms like `g_return_val_if_fail (..., FALSE)` where the GError
does not get properly set and the two mechanisms end up disagreeing.
Such case is considered undefined behavior by glib, and may indeed
result in buggy execution flow not detected as such.
In order to avoid that, gir now cross-checks the returned code and
the GError value before proceeding further.
Closes: https://github.com/gtk-rs/gir/issues/1279

codegen/function: assert sane GError behavior

---

src/codegen/doc/format.rs

as it's a derive macro and a struct, specify the generated docs as a struct.
Tested locally and it works fine :)

docs: work around glib::Variant case

---

src/analysis/functions.rs
src/codegen/doc/mod.rs

Allow documenting global functions in a specific trait by making use of `doc_trait_name` and rustdoc-stripper takes care of the rest.
Fixes #799

 docs: allow documenting global functions in traits 

---

book/src/config_api.md
src/analysis/functions.rs
src/codegen/doc/mod.rs
src/config/functions.rs

Some of those are moved to a different struct in some cases
like gdk::Key and would be nice to have them documented

docs: allow to set doc_struct_name for global functions

---

src/writer/to_code.rs

This makes the check on return code stricter, by using the actual
gboolean value.
Ref: https://github.com/gtk-rs/gtk3-rs/pull/691#issuecomment-992355228

writer: check return code as gboolean

---

src/codegen/doc/mod.rs

There are still some cases left like when a function has a getter but the getter was renamed to something else so we can't do a match between the "expected getter name" & the one we get at the end.

docs: avoid generating docs for uneeded properties getters/setters

---

src/parser.rs

This should fix the generation of gtk3 using the latest gir files
As some private structs lack a type on their fields, so better ignore them

parser: ignore private records

---

book/src/config_api.md
src/analysis/enums.rs
src/analysis/flags.rs
src/analysis/functions.rs
src/analysis/info_base.rs
src/analysis/object.rs
src/analysis/record.rs
src/analysis/special_functions.rs
src/codegen/enums.rs
src/codegen/flags.rs
src/codegen/function.rs
src/codegen/general.rs
src/codegen/mod.rs
src/codegen/object.rs
src/codegen/record.rs
src/codegen/special_functions.rs
src/codegen/visibility.rs
src/config/functions.rs
src/config/gobjects.rs

This PR allows to tweak the visibility of functions/enums/flags & also objects/records. For global functions that are marked as non-public, they also have a `#[allow(dead_code)]` guard added to avoid any clippy complaints.
Fixes #1238 
cc @lucab

Allow tweaking visibility 

---

src/analysis/record_type.rs
src/analysis/rust_type.rs
src/library.rs

Currently, gir generates the following &[&SomeCopyType] instead of &[SomeCopyType]
Fixes #1247

analysis: don't take a slice of copy types by ref

---

src/codegen/special_functions.rs
src/codegen/visibility.rs

Originally the `visibility` modifier contained this space ("pub ") to keep indentation in check.  A recent change however formats the visibility modifier from configuration directly into the file, without inserting the necessary trailing space, resulting in the text `pubfn` in `special_functions`, which is invalid syntax.
Since output is almost always formatted with rustfmt anyway, this indentation mismatch is irrelevant to allocate a string for here.
Fixes: e3bd76a3 ("replace FunctionVisibility with hidden/commented attributes"), cc @bilelmoussaoui

codegen/special_functions: Add missing space between `pub` and `fn`

---

src/codegen/function_body_chunk.rs
src/codegen/trampoline_from_glib.rs

Needed for https://github.com/gtk-rs/gtk-rs-core/pull/600, but doesn't depend on it (this PR shouldn't break anything)

codegen: Use GString::as_str instead of Option<GString>::as_deref

---

src/analysis/object.rs

Fixes a few links like [here](https://gtk-rs.org/gtk-rs-core/stable/latest/docs/glib/struct.ParamFlags.html#associatedconstant.EXPLICIT_NOTIFY) and [here](https://gtk-rs.org/gtk-rs-core/stable/latest/docs/glib/struct.Binding.html#method.unbind)
There's still some left that refer to nonexisting rust functions however, like `ObjectExt::set` and `ObjectSet::bind_property_full`

docs: Never use ExtManual trait with GObject

---

src/analysis/out_parameters.rs
src/codegen/function_body_chunk.rs

Hi,
As I filed #1331 , gir v0.15 or later inserts assertion for result of throw function even if the function returns void. It's based on GNOME convention that throw function should return boolean value to express whether GError argument is set or not. However we have some libraries which don't follow to the convention yet.
This patchset adds enumeration to express the strategy of return value for throw function,
then suppress the insertion for throw function returning void. As a result, the generated code is almost the same as the one generated gir v0.14 or before in regards of throw function to return void.

suppress insertion of assertion for result of throw function to return void

---

src/config/constants.rs
src/config/gobjects.rs

Unlike what we feared, it was only impacting the error messages.

Fix error message for constant parsing

---

src/git.rs

not sure the new Windows related code is 100% correct
we will see...
fixes https://github.com/gtk-rs/gir/issues/1360

git: add non unix fallback for creating PathBuf from Vec<u8>

---

src/codegen/function.rs

Leftover from the Rust 2018 update long ago.

Fix `BoolError` import when being used from glib directly

---

src/analysis/bounds.rs
src/analysis/function_parameters.rs

Insert the `as_ref()` calls before `len()` when the array parameter has trait bounds. Needed for https://github.com/gtk-rs/gtk-rs-core/pull/708, fixes this error:
```
error[E0599]: no method named `len` found for type parameter `impl AsRef<std::path::Path>` in the current scope
--> glib/src/auto/functions.rs:348:27
|
348 |     let len = opsysstring.len() as isize;
|                           ^^^ method not found in `impl AsRef<std::path::Path>`
```
Error source: https://github.com/gtk-rs/gtk-rs-core/runs/6910586265?check_suite_focus=true#step:15:81

analysis: Call extra to_glib functions in array len transformation

---

src/codegen/sys/tests.rs

In GStreamer's Vulkan bindings (`GstVulkan-1.0.gir`) we have a string constant that starts and ends with a space.  When the C program emits the value of this constant through `printf()`, an erroneous `.trim()` call here in Rust strips the trailing whitespace and causes the test for this particular constant to fail:
---- cross_validate_constants_with_c stdout ----
Constant value mismatch for GST_VULKAN_SWAPPER_VIDEO_FORMATS
Rust: " { RGBA, BGRA, RGB, BGR } "
C:    " { RGBA, BGRA, RGB, BGR }"
Address this by removing the `.trim()`, and simplifying some of the iterator code away with a `.split_once()`.
All tests on at least GStreamer succeed, leading to believe that this `.trim()` serves no purpose as the argument is already split on newlines; any additional whitespace is hence part of the …

codegen/sys/tests: Don't trim whitespace on C constant output

---

src/analysis/functions.rs

If no version is set for a dependency requirement, we should not ignore those functions.
Related to https://github.com/gtk-rs/gtk4-rs/issues/1054

analysis: Fix logic when analysing a function

---

src/analysis/bounds.rs
src/analysis/function_parameters.rs

By calling to_owned() on the result of as_ref() as the into_glib_ptr requires Self and AsRef returns &Self

analysis: Handle move configuration in Ext trait

---

src/codegen/flags.rs
src/codegen/function_body_chunk.rs
src/codegen/sys/build.rs
src/codegen/sys/lib_.rs
src/codegen/translate_from_glib.rs
src/writer/to_code.rs

It fixes two warnings:
``warning: variables can be used directly in the `format!` string`` and `unneeded cast`.

Fix new clippy lints

---

src/config/gobjects.rs

Resolves [this issue](https://github.com/gtk-rs/gir/issues/1400).

Fix incorrect 'missing from library' warning when generating in sys mode

---

src/codegen/constants.rs
src/codegen/enums.rs
src/codegen/flags.rs
src/codegen/function.rs
src/codegen/general.rs
src/codegen/object.rs

Gets rid of all the annoying warnings for `gio::TlsRehandshakeMode`, `pango::BidiType`, etc

codegen: silence deprecation warnings in impls for deprecated types/functions

---

src/analysis/function_parameters.rs

We don't have a clear path forward implement yet for handling those cases.

analysis: Don't use IntoGlibPtr for Vec<T> parameters

---

src/codegen/sys/cargo_toml.rs
src/codegen/sys/lib_.rs
src/parser.rs

For example with [gsettings-desktop-schemas-rs](https://gitlab.gnome.org/vlinkz/gsettings-desktop-schemas-rs), there is no library bound. At the moment `sys/lib.rs` generates with the following at the end:
```rust
#[link(name = "")]
extern "C" {
}
```
which leads to the error:
```
error[E0454]: link name must not be empty
--> gsettings-desktop-schemas/sys/src/lib.rs:199:15
|
199 | #[link(name = "")]
|               ^^ empty link name
```

Fix generation without any shared libraries

---

src/codegen/constants.rs
src/codegen/sys/lib_.rs

This gets rid of all the `once_cell` `Lazy` usage and allows using them as NUL-terminated strings in more places.

Generate string constants as `&'static GStr` / `[u8]`

---

book/src/config_api.md
src/codegen/enums.rs
src/config/gobjects.rs

This allows them to be represented as a plain `i32` instead of a 5-byte big enum, which in turn allows direct casting between the C and Rust type and fitting the value into a register on 32 bit systems, or even a `Result` on 64 bit systems.
----
Example generated code for an example in GStreamer
```rust
#[must_use]
#[derive(Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Clone, Copy)]
#[repr(i32)]
#[doc(alias = "GstFlowReturn")]
pub enum FlowReturn {
#[doc(alias = "GST_FLOW_CUSTOM_SUCCESS_2")]
CustomSuccess2 = ffi::GST_FLOW_CUSTOM_SUCCESS_2,
#[doc(alias = "GST_FLOW_CUSTOM_SUCCESS_1")]
CustomSuccess1 = ffi::GST_FLOW_CUSTOM_SUCCESS_1,
#[doc(alias = "GST_FLOW_CUSTOM_SUCCESS")]
CustomSuccess = ffi::GST_FLOW_CUSTOM_SUCCESS,
#[doc(alias = "GST_FLOW_OK")]
Ok = ffi::GST_FLOW_OK,
#[doc(alias = …
```

Add configuration for exhaustive enums

---

src/codegen/general.rs

The latter is about to be renamed to the former.
See https://github.com/gtk-rs/gtk-rs-core/issues/913

Use `Object::new()` instead of `Object::new_default()`

---

src/analysis/functions.rs
src/analysis/object.rs
src/analysis/supertypes.rs
src/codegen/function_body_chunk.rs
src/codegen/object.rs

Allows to drop the following from `gtk4/auto`
```rust
#[allow(clippy::let_and_return)]
#[allow(clippy::clone_on_copy)]
```

Generate less clippy warnings code

---

src/analysis/function_parameters.rs

When generating bindings for a specific type using a debug build of the gir tool, I got
```
thread 'main' panicked at 'attempt to subtract with overflow', src/analysis/function_parameters.rs:449:20
stack backtrace:
0: rust_begin_unwind
at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
1: core::panicking::panic_fmt
at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
2: core::panicking::panic
at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:48:5
3: libgir::analysis::function_parameters::detect_length
at /Users/marcomp/git/oss/gir/src/analysis/function_parameters.rs:449:20
4: libgir::analysis::function_parameters::analyze
at /Users/marcomp/git/oss/gir/src/analysis/function_parameters.rs:263 …
```

Fixes an overflow bug that may occasionally panic if gir is built in debug

---

src/codegen/property_body.rs

codegen: Avoid useless borrows for properties setters

---

src/codegen/general.rs
src/config/config.rs

Many gtk-rs crates have license issues with their docs, so they exclude most docs from their source and build their documentation separately. However, doc.rs will always build the documentation, even if Cargo.toml specifies a different doc url.Sites like [lib.rs](https://lib.rs/crates/gtk4) even list the doc.rs docs as "API reference" and list it before the actual documentation. So overall, it's not unlikely for new users to end up on docs.rs and wonder why the docs are so bad. 
Further, SEO is a real problem with the docs. Searching for [libadwaita docs](https://duckduckgo.com/?q=libadwaita+docs) gives you the link to the Flutter rip-off, then an Arch package and then the docs built for Relm4 (which are just as bad the docs.rs docs). You can't even find the actual docs through DDG it …

Add external docs url config option

---

book/src/tutorial/generate_docs.md
book/src/tutorial/high_level_rust_api.md
src/codegen/general.rs
src/codegen/object.rs
src/codegen/sys/build.rs
src/codegen/sys/cargo_toml.rs
src/codegen/sys/statics.rs
tests/sys/atk-sys/Cargo.toml
tests/sys/gdk-pixbuf-sys/Cargo.toml
tests/sys/gdk-sys/Cargo.toml
tests/sys/gio-sys/Cargo.toml
tests/sys/glib-sys/Cargo.toml
tests/sys/gobject-sys/Cargo.toml
tests/sys/gtk-sys/Cargo.toml
tests/sys/pango-sys/Cargo.toml

Fixes #1454 
I think this should be all from the gir side.
I've tested this branch on gtk4-rs and everything looked and worked great so far.
Let me know if I should submit PRs for various gtk-rs crates once this is merged.

Replace dox feature with docsrs attribute

---

book/src/tutorial/generate_docs.md
book/src/tutorial/high_level_rust_api.md
src/codegen/general.rs
tests/sys/atk-sys/Cargo.toml
tests/sys/gdk-pixbuf-sys/Cargo.toml
tests/sys/gdk-sys/Cargo.toml
tests/sys/gio-sys/Cargo.toml
tests/sys/glib-sys/Cargo.toml
tests/sys/gobject-sys/Cargo.toml
tests/sys/gtk-sys/Cargo.toml
tests/sys/pango-sys/Cargo.toml

Removing the "dox" feature caused some unexpected complications because some crates, cairo in particular, used the "dox" feature as replacement for `--all-features`. In other words, "dox" did not only enable the typical documentation configuration, but also pulled in additional dependencies and effectively overwrote some feature flags (with `#[cfg(any(feature = "...", feature = "dox"))]`). This behavior was matched with the `docsrs` attribute so far, but of course the attribute can't activate dependencies in Cargo.toml.
My proposed solution would be to never use the `docsrs` attribute to interact with feature flags and conditional compilation. If someone wants to document everything `--all-features` would be the way to go. This makes sure that conditional compilation is the same in …

Make features independent from docsrs attribute

---

src/codegen/general.rs

@sdroege in the previous PR, I've accidentally missed one occurrence of docsrs used for conditional compilation. Once merged, all blockers for the gtk-rs-core PR should be resolved.

Remove docsrs attr for conditional compilation

---

src/codegen/general.rs

any was used at the time we had the dox feature. Nowadays it is only a single feature so the usage of any is useless

codegen: Drop useless any on a single feature

---

src/parser.rs

This tag is somewhat obscure and only occurs when there is a boxed GType without a public struct definition. In gtk4-rs this is only used once with `GtkTreeRowData`:
```
[WARN  libgir::parser] <boxed name=Some("TreeRowData")>
```
Which is buggy and deprecated and there was never a binding for it anyway, so let's just silence these warnings. Fixes #1456

parser: ignore `boxed` elements

---

src/codegen/object.rs

Is there some reason this is not done already? It seems to reduce code size in gtk4-rs by about 5-6%.

codegen: only generate trait signatures once

---

src/codegen/child_properties.rs
src/codegen/function.rs
src/codegen/properties.rs
src/codegen/signal.rs

Follow up to #1461, I forgot to add the doc and deprecated attributes back in

codegen: generate attributes on trait fns

---

book/src/config/api.md
src/analysis/mod.rs
src/analysis/object.rs
src/codegen/doc/format.rs
src/codegen/doc/gi_docgen.rs
src/codegen/doc/mod.rs
src/config/functions.rs
src/config/gobjects.rs
src/config/mod.rs
src/config/virtual_methods.rs
src/library.rs
src/parser.rs

The intention behind this PR is not to add code generation for subclassing code but it does a good step forward. 
What the PR does currently:
- Parse virtual-methods from the gir file 
- Add configuration options for `[object.virtual_method]`
- Embed the docs for virtual methods
- Working docs links witth gi-docgen
Before
After
TODO: 
Parts of #1319

Implement basic virtual methods support

---

src/analysis/object.rs

For two reasons:
- Once we generate subclassing traits, they wouldn't share imports with the "normal" methods
- They end up breaking unused imports lint

analysis: Don't fill imports from virtual methods

---

book/src/tutorial/generate_docs.md
book/src/tutorial/high_level_rust_api.md

See https://github.com/gtk-rs/gtk-rs-core/pull/1092

Fix docs for docsrs attribute

---

src/parser.rs

Regenerating libadwaita-rs errors out otherwise

parser: ignore source-position in virtual methods

---

src/analysis/function_parameters.rs
src/analysis/functions.rs

Fixes a debug build of GIR panicking when processing non-static async methods.
```
thread 'main' panicked at 'attempt to subtract with overflow', ...\gtk-rs-gir\src\analysis\function_parameters.rs:243:46
stack backtrace:
0: rust_begin_unwind
at /rustc/4087deaccd8bceb458c9610d29744d5f3504c5c0/library\std\src/panicking.rs:577:5
1: core::panicking::panic_fmt
at /rustc/4087deaccd8bceb458c9610d29744d5f3504c5c0/library\core\src/panicking.rs:67:14
2: core::panicking::panic
at /rustc/4087deaccd8bceb458c9610d29744d5f3504c5c0/library\core\src/panicking.rs:117:5
3: libgir::analysis::function_parameters::analyze
4: libgir::analysis::functions::analyze_function
5: libgir::analysis::functions::analyze
6: libgir::analysis::object::interface
7: libgir::analysis::analyze
8: libgir::analysis::run
9: …
```

analysis: Avoid overflow when determining whether to emit a parameter

---

src/codegen/general.rs

Silences the new beta clippy warning

codegen: Only use any if scope constraints > 1

---

src/codegen/sys/tests.rs

They work fine on FreeBSD, it was annoying to see tests just gone when updating from 0.15.x to 0.17.x..

codegen: build tests on all unix platforms

---

src/codegen/trampoline.rs

As it had the same semantics as glib::Continue which we replaced

codegen: Switch from Inhibit to ControlFlow

---

src/codegen/sys/cargo_toml.rs
src/config/config.rs

This PR includes a few improvements/cleanups regarding building docs on docs.rs:
- The `docs_rs_features` option in the `Gir.toml` was removed. I searched on Github if anybody was using it and I couldn't find anyone. It was also not documented so I don't think anyone used it. It would have complicated with the last point.
- Since the removal of the dox feature, a few rustc args need to get set in order to build the docs without linking the libraries. They are always the same so we can set them by default in the `Cargo.toml` of the sys crate.
- Automatically activate all features of the sys crate so that they all get documented.

Fix docsrs

---

book/src/config/api.md

I had a naming conflict with a generated trait and could not find a solution in the docs. Better to add it to the book to avoid the same [question](https://github.com/gtk-rs/gir/issues/1488) in the future

Add trait_name to API docs

---

src/codegen/sys/cargo_toml.rs

Without this PR, this is what is added to the `Cargo.toml` of the sys crate:
```
[package.metadata.docs.rs]
all-features = "true"
```
With the fix the type is correct:
```
[package.metadata.docs.rs]
all-features = true
```
Sorry about that

Fix inserting all-features in Cargo.toml for docs.rs

---

src/codegen/sys/tests.rs

The generated tests for `sys` crates sometimes call `Command::output`. It is used to find CFLAGS arguments for tested packages and run the executables created from `constant.c` and `layout.c` tests. `Command::output`, by default, captures `stdout` and `stderr`. This means that, by default, no feedback for why the tests fail will be printed. The only information shown to the end-user is the command that was ran.
You could copy/paste and run yourself the command printed in the error message, but it might not be evident as a "next step" for users.
This is unlike the compilation command, which uses `cmd.spawn()?.wait()?`. We can see compilation error messages, but not pkg-config error messages.
To solve this, we:
1. Inherit `stderr` from the parent descriptor. This will print the command's …

Generated sys tests: Better command error handling

---

book/src/config/api.md
src/analysis/enums.rs
src/analysis/flags.rs
src/analysis/functions.rs
src/analysis/object.rs
src/analysis/out_parameters.rs
src/analysis/properties.rs
src/analysis/signals.rs
src/analysis/special_functions.rs
src/codegen/enums.rs
src/codegen/flags.rs
src/codegen/object.rs
src/codegen/objects.rs
src/codegen/trait_impls.rs
src/config/config.rs
src/config/gobjects.rs
src/writer/to_code.rs

- objects: It uses to print the type name: not useful at all
- enums: It does print what a debug impl would print
- flags: It does print what a debug impl would print
So just get rid of that generated code and let the bindings generate a display impl manually when it makes sense

config/codegen: Stop generating useless Display impls

---

src/codegen/enums.rs
src/codegen/flags.rs

this allows finding *_type() functions using their c names
See https://github.com/gtk-rs/gtk4-rs/pull/383 for the end result

codgen: generate doc_alias for static_type

---

book/src/tutorial/handling_errors.md
book/src/tutorial/high_level_rust_api.md
src/analysis/mod.rs
src/codegen/functions.rs
src/codegen/mod.rs
src/codegen/sys/functions.rs
src/codegen/sys/lib_.rs
src/config/constants.rs
src/config/error.rs
src/config/functions.rs
src/config/members.rs
src/config/properties.rs
src/config/signals.rs
src/config/virtual_methods.rs
src/parser.rs
src/update_version.rs

Currently clippy would complain about a pub mod in auto having the same name as the outer mod. We should just make these mods `pub(crate)` and ask the user to explicitly re-export them.  This solves the clippy lint complaint without having to rename any  files.

Make auto builders/traits/functions `pub(crate)`

---

src/parser.rs

As gtk4 now has a record that contains a union without a name/c-type

parser: Don't require name/type for record types

---

src/analysis/types.rs
src/codegen/sys/lib_.rs
src/library.rs
src/library_postprocessing.rs
src/parser.rs

Disguised types are not pointers, they're just typedefs to a private struct, while pointer types are typedef to a pointer to a private struct. Generate the right code for each.
In C, there are 2 types of "disguised" typdefs:
`typedef struct _Blob *Blob`
and
`typedef struct _Blob Blob`
In Gir files, they're both called "disguised", but the first kind also has the "pointer" property set. The current generator only knows about the pointer type.
Currently, it generates 
`pub type Blob = *mut _Blob;`
But , it should do `pub type Blob = _Blob` for the non-pointer type.
The effect of this bug is that the rest of the code gen will think that the type is a pointer to a pointer.
So it will generate functions with a signature of `fn func(*mut *mut blob)` instead of `fn func(*mut blob)`

record: Differentiate disguised vs pointer types

---

Cargo.lock
Cargo.toml
src/codegen/doc/format.rs
src/codegen/doc/gi_docgen.rs
src/codegen/doc/mod.rs
src/codegen/enums.rs
src/codegen/sys/functions.rs
src/nameutil.rs

See also https://github.com/gtk-rs/gtk-rs-core/pull/1289

Replace `once_cell` crate with `std::sync::OnceLock`

---

src/codegen/sys/cargo_toml.rs
src/codegen/sys/lib_.rs

In the past, this seemed like a decent idea but the switch to using cargo workspace proves it wasn't as we now have conflicting crates with the same names

codegen/sys: Don't expect the crates are renamed

---

src/analysis/constants.rs
src/analysis/functions.rs
src/analysis/namespaces.rs
src/analysis/object.rs
src/analysis/record.rs
src/codegen/sys/fields.rs
src/codegen/sys/functions.rs
src/codegen/sys/lib_.rs
src/config/functions.rs
src/config/gobjects.rs
src/config/members.rs
src/config/mod.rs
src/config/virtual_methods.rs
src/lib.rs
src/update_cfgs.rs

You can take a look at the result [here](https://github.com/gtk-rs/gtk-rs-core/compare/master...GuillaumeGomez:gtk-rs-core:regen-with-cfg?expand=1) (I didn't remove all unneeded `cfg_condition` yet).

Automatically assume that `win32_` and `unix_` should use the related cfg

---

src/codegen/sys/tests.rs

Realized that there was a regression when I removed `cfg_condition` from glib as well. As far as I can see, it's the last one.
Follow-up of https://github.com/gtk-rs/gir/pull/1540.

Correctly generate cfg condition for ABI tests

---

src/library_postprocessing.rs
src/parser.rs

If final="1" is set we skip the heuristic to determine whether a class is final.
Fixes: https://github.com/gtk-rs/gir/issues/1204

Use final annotation

---

src/analysis/enums.rs
src/analysis/flags.rs
src/analysis/functions.rs
src/analysis/imports.rs
src/analysis/mod.rs
src/analysis/object.rs
src/analysis/record.rs
src/codegen/constants.rs
src/codegen/enums.rs
src/codegen/flags.rs
src/codegen/function.rs
src/codegen/general.rs
src/codegen/object.rs
src/codegen/record.rs

As we would like to define those crates in the main workspace file to simplify the release process
Needs a gtk4-rs/gtk-rs-core regen first, to ensure everything is still working as expected.

codegen: Stop renaming ffi crate

---

src/codegen/function.rs

If both the setter and getter for a property have the same annotation we would add the same alias twice.
e.g. get_property or org.gtk.get_property set on the setter, the we would add the doc alias twice.

codegen: Avoid double alias on badly annotated fn

---

src/analysis/bounds.rs
src/analysis/functions.rs
src/library.rs
src/parser.rs

To get the correct name of the finish function if any.

Support finish-func annotation

---

src/codegen/doc/mod.rs

Otherwise functions like match_ don't get documented

codegen: Handle mangled types names

---

src/codegen/function.rs

Currently, the future body generated is something like:
```rust
pub fn probe_endpoints_future(
my_slice: &[MyObject],
) -> Pin<
Box_<dyn std::future::Future<Output = Result<_, glib::Error>> + 'static>,
> {
skip_assert_initialized!();
let my_slice = my_slice.map(ToOwned::to_owned);   // if my_slice is declared as nullable
// or
let my_slice = my_slice.clone();                  // if my_slice is not declared as nullable
Box_::pin(gio::GioFuture::new(&(), move |_obj, cancellable, send| {
// ...
}
```
both approaches fail to compile as:
* `.map` does not exist for `slice` type (it is not an `Option`)
* `.clone()` does not really give ownership of the data slice, as `clone` only copies the wide-pointer.
- This is an issue as the future closure need to move something which needs '`static` …

codegen/function: body future handles ownership of slice argument

---

src/codegen/sys/lib_.rs

We're only using them by pointer and they're constructed from the C side, but clippy gives warnings:
```
warning: struct `GDoubleIEEE754` is never constructed
--> glib/sys/src/lib.rs:1013:12
|
1013 | pub struct GDoubleIEEE754 {
|            ^^^^^^^^^^^^^^
|
= note: `#[warn(dead_code)]` on by default
```

Allow `dead_code` lint for opaque structs

---

generator.py

Currently, the script just guesses a target path based on the default config. This fails if the project or the user has configured a different target directory.
This code is shorter and more correct.

generator.py: Use cargo run instead of guessing path

---

src/codegen/sys/cargo_toml.rs
src/codegen/sys/lib_.rs
src/nameutil.rs

Follow up to #1475. Motivated by work at `gtk-rs-core` and `gstreamer-rs` to override library linking.
At the moment a `#[link]` attribute is being generated for every `extern "C"` code block. This is not generally needed since `system-deps` already handles linking libraries, and it makes overriding dependencies difficult from higher up crates.
The only exception is one edge case when using Windows and static constants, but that is a limitation of the compiler. To handle this case, allow to use custom `build.rs` scripts by not overriding the package field.
All of the context for this change and all of the alternatives we considered are explained in gtk-rs/gtk-rs-core#1508.
- Remove `#[link]` attribute generation.
- Allow custom build scripts. If the `package.build` key doesn't exist in …

Remove link attribute generation

---

book/src/tutorial/high_level_rust_api.md

Hi,
at first let me thanks you for this nice project that is quite useful. I use it to setup some first draft for using gobject API from rust for my project and when I follow instructions in book and failed to compile it. After debugging I found that `use ffi;` in lib.rs solve my issue with generated code and I think it should be part of book so others do not need to face it.
Thanks

[book] Add note to use ffi

---

src/codegen/object.rs

This reverts commit b0cfba0d135803f7895ba514dd4639d239b85176.
This is not actually necessary because IsA<T> is a requirement for the extension trait, and IsA is an unsafe trait and must only be implemented on types that are actually conforming.
----
CC @felinira as discussed.

Revert "codegen: seal Ext traits"

---

src/codegen/object.rs

Fixes https://github.com/gtk-rs/gir/issues/1590

codegen/builder: Assert the main thread is initalized

---

src/analysis/safety_assertion_mode.rs
src/codegen/function.rs
src/codegen/object.rs
src/writer/mod.rs
src/writer/to_code.rs

codegen/object: Check for generate_safety_asserts when generating builders

---

src/analysis/rust_type.rs

Fixes https://github.com/gtk-rs/gir/issues/1605
Without this change, the safe wrappers are not generated

analysis: Support more target dependant types

---

src/codegen/function_body_chunk.rs

Building `userdata` for `FnMut` callbacks consisted in taking an immutable reference to the user provided function, before converting it to a mutable pointer. This was UB and could lead to future optimizations considering a closure's captured context is immutable.
See also:
* gtk4-rs update: https://github.com/gtk-rs/gtk4-rs/pull/1902
* gstreamer-rs update: https://gitlab.freedesktop.org/gstreamer/gstreamer-rs/-/merge_requests/1585

fix userdata mutability for FnMut callbacks

---

generator.py

In commit c6ba79ed ("generator.py: Use cargo run instead of guessing path") the `cargo build` command on the default (hardcoded) `"gir"` directory was replaced with a single `cargo run` for correctly finding the right executable.
This isn't an issue given that `cargo run` also builds the tool, and above all makes it easier / more correct to find the binary as the primary reason for that commit, but it does make us lose the build log as a progress indicator (thanks to `--quiet` and capturing `stderr`). In addition, it causes the first `` => Looking in path `xxx` `` item to take a very long time without aforementioned progres indication, making the user wonder what is going on.
By building `gir` again with a separate `cargo build` invocation before running, this issue is alleviated …

generator.py: Restore pre-building `gir` with build/progress output

---

src/analysis/signals.rs

Related to #772
This is needed because `use glib::prelude::*` will not pull in `ObjectType` (even though we only need the trait in scope) because it's shadowed.
Another way to fix this is by using a fully-qualified path to `ObjectType` at the call-site (happy to submit another PR for that if that's preferred, I do have one somewhere...), but this is more consistent with what's already being done.

signals: work-around ObjectType shadowing

---

book/src/config/api.md

As very briefly discussed on `#rust:gnome.org`, this updates the documentation for specifying explicit `#[derive(...)]` clauses in `Gir.toml`.
As anticipated on the chat, the behavior of derives is a bit inconsistent depending on the type. This documentation should reflect the current reality (to the best of my knowledge).

Improved the documentation for derive clauses in API configuration

---

src/writer/to_code.rs

NUL-terminated  strings are  currently  generated  as b"<string>\0"  for signal names rather than as c"<string>" as recommended in:
https://rust-lang.github.io/rust-clippy/master/index.html#manual_c_str_literals

Address clippy warning
